JUCE: AudioUnitHelpers::CoreAudioBufferList Class Reference
AudioUnitHelpers::CoreAudioBufferList Class Reference
Public Member Functions
CoreAudioBufferList ()
void prepare (int inChannels, int outChannels, int maxFrames)
void release ()
void reset () noexcept
float * setBuffer (const int idx, float *ptr=nullptr) noexcept
float * push () noexcept
void push (AudioBufferList &bufferList, const int *channelMap) noexcept
float * pop () noexcept
void pop (AudioBufferList &buffer, const int *channelMap) noexcept
AudioSampleBuffer & getBuffer (UInt32 frames) noexcept
Constructor & Destructor Documentation
AudioUnitHelpers::CoreAudioBufferList::CoreAudioBufferList ()
References reset().
Member Function Documentation
void AudioUnitHelpers::CoreAudioBufferList::prepare (int inChannels, int outChannels, int maxFrames)
References HeapBlock< ElementType, throwOnFailure >::calloc(), jmax(), reset(), and AudioBuffer< Type >::setSize().
void AudioUnitHelpers::CoreAudioBufferList::release ()
References HeapBlock< ElementType, throwOnFailure >::free(), and AudioBuffer< Type >::setSize().
void AudioUnitHelpers::CoreAudioBufferList::reset () noexcept
References HeapBlock< ElementType, throwOnFailure >::getData(), AudioBuffer< Type >::getNumChannels(), and zeromem().
Referenced by CoreAudioBufferList(), and prepare().
float* AudioUnitHelpers::CoreAudioBufferList::setBuffer (const int idx, float * ptr = nullptr) noexcept
References AudioBuffer< Type >::getNumChannels(), and jassert.
float* AudioUnitHelpers::CoreAudioBufferList::push () noexcept
References AudioBuffer< Type >::getNumChannels(), and jassert.
Referenced by push().
void AudioUnitHelpers::CoreAudioBufferList::push (AudioBufferList & bufferList, const int * channelMap) noexcept
References AudioUnitHelpers::copyAudioBuffer(), AudioBuffer< Type >::getNumChannels(), AudioUnitHelpers::isAudioBufferInterleaved(), jassert, and push().
float* AudioUnitHelpers::CoreAudioBufferList::pop () noexcept
References AudioBuffer< Type >::getNumChannels(), and jassert.
Referenced by pop().
void AudioUnitHelpers::CoreAudioBufferList::pop (AudioBufferList & buffer, const int * channelMap) noexcept
References AudioUnitHelpers::copyAudioBuffer(), AudioUnitHelpers::isAudioBufferInterleaved(), and pop().
AudioSampleBuffer& AudioUnitHelpers::CoreAudioBufferList::getBuffer (UInt32 frames) noexcept
References AudioBuffer< Type >::getNumChannels(), jassert, and AudioBuffer< Type >::setDataToReferTo().
The documentation for this class was generated from the following file:
juce_AU_Shared.h