JUCE: TableHeaderComponent::Listener Class Reference
TableHeaderComponent::Listener Class Reference abstract
juce_gui_basics » widgets
Receives events from a TableHeaderComponent when columns are resized, moved, etc.
Public Member Functions
Listener ()=default
virtual ~Listener ()=default
Destructor.
virtual void tableColumnsChanged (TableHeaderComponent *tableHeader)=0
This is called when some of the table's columns are added, removed, hidden, or rearranged.
virtual void tableColumnsResized (TableHeaderComponent *tableHeader)=0
This is called when one or more of the table's columns are resized.
virtual void tableSortOrderChanged (TableHeaderComponent *tableHeader)=0
This is called when the column by which the table should be sorted is changed.
virtual void tableColumnDraggingChanged (TableHeaderComponent *tableHeader, int columnIdNowBeingDragged)
This is called when the user begins or ends dragging one of the columns around.
Detailed Description
Receives events from a TableHeaderComponent when columns are resized, moved, etc.
You can register one of these objects for table events using TableHeaderComponent::addListener() and TableHeaderComponent::removeListener().
See also
TableHeaderComponent
Constructor & Destructor Documentation
Listener()
TableHeaderComponent::Listener::Listener () default
~Listener()
virtual TableHeaderComponent::Listener::~Listener () virtual default
Destructor.
Member Function Documentation
tableColumnsChanged()
virtual void TableHeaderComponent::Listener::tableColumnsChanged (TableHeaderComponent * tableHeader) pure virtual
This is called when some of the table's columns are added, removed, hidden, or rearranged.
Implemented in TableListBox.
Referenced by TableListBox::isAutoSizeMenuOptionShown().
tableColumnsResized()
virtual void TableHeaderComponent::Listener::tableColumnsResized (TableHeaderComponent * tableHeader) pure virtual
This is called when one or more of the table's columns are resized.
Implemented in TableListBox.
Referenced by TableListBox::isAutoSizeMenuOptionShown().
tableSortOrderChanged()
virtual void TableHeaderComponent::Listener::tableSortOrderChanged (TableHeaderComponent * tableHeader) pure virtual
This is called when the column by which the table should be sorted is changed.
Implemented in TableListBox.
Referenced by TableListBox::isAutoSizeMenuOptionShown().
tableColumnDraggingChanged()
virtual void TableHeaderComponent::Listener::tableColumnDraggingChanged (TableHeaderComponent * tableHeader, int columnIdNowBeingDragged) virtual
This is called when the user begins or ends dragging one of the columns around.
When the user starts dragging a column, this is called with the ID of that column. When they finish dragging, it is called again with 0 as the ID.
Reimplemented in TableListBox.
Referenced by TableListBox::isAutoSizeMenuOptionShown().
The documentation for this class was generated from the following file:
juce_TableHeaderComponent.h