JUCE: AudioBlock< SampleType > Class Template Reference
AudioBlock< SampleType > Class Template Reference
Minimal and lightweight data-structure which contains a list of pointers to channels containing some kind of sample data.
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
Public Member Functions
forcedinline AudioBlock () noexcept
Create a zero-sized AudioBlock.
forcedinline AudioBlock (SampleType *const *channelData, size_t numberOfChannels, size_t numberOfSamples) noexcept
Creates an AudioBlock from a pointer to an array of channels.
forcedinline AudioBlock (SampleType *const *channelData, size_t numberOfChannels, size_t startSampleIndex, size_t numberOfSamples) noexcept
Creates an AudioBlock from a pointer to an array of channels.
AudioBlock (HeapBlock< char > &heapBlockToUseForAllocation, size_t numberOfChannels, size_t numberOfSamples) noexcept
Allocates a suitable amount of space in a HeapBlock, and initialises this object to point into it.
AudioBlock (AudioBuffer< SampleType > &buffer) noexcept
Creates an AudioBlock that points to the data in an AudioBuffer.
AudioBlock (AudioBuffer< SampleType > &buffer, size_t startSampleIndex) noexcept
Creates an AudioBlock that points to the data in an AudioBuffer.
AudioBlock (const AudioBlock &other) noexcept=default
AudioBlock & operator= (const AudioBlock &other) noexcept=default
forcedinline size_t getNumSamples () const noexcept
forcedinline size_t getNumChannels () const noexcept
forcedinline const SampleType * getChannelPointer (size_t channel) const noexcept
Returns a raw pointer into one of the channels in this block.
forcedinline SampleType * getChannelPointer (size_t channel) noexcept
Returns a raw pointer into one of the channels in this block.
forcedinline AudioBlock
< SampleType > getSingleChannelBlock (size_t channel) const noexcept
Returns an AudioBlock that represents one of the channels in this block.
forcedinline AudioBlock
< SampleType > getSubsetChannelBlock (size_t channelStart, size_t numChannelsToUse) noexcept
Returns a subset of continguous channels.
forcedinline AudioBlock & clear () noexcept
Clear the memory described by this AudioBlock.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE fill (SampleType value) noexcept
Fill memory with value.
forcedinline AudioBlock & copy (const AudioBlock &src) noexcept
Copy the values in src to the receiver.
forcedinline AudioBlock & move (size_t srcPos, size_t dstPos, size_t numElements=std::numeric_limits< size_t >::max()) noexcept
Move memory within the receiver from the position srcPos to the position dstPos.
AudioBlock getSubBlock (size_t newOffset, size_t newLength) const noexcept
Return a new AudioBlock pointing to a sub-block inside the receiver.
AudioBlock getSubBlock (size_t newOffset) const noexcept
Return a new AudioBlock pointing to a sub-block inside the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE add (SampleType value) noexcept
Adds a fixed value to the receiver.
forcedinline AudioBlock & add (const AudioBlock &src) noexcept
Adds the source values to the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE add (const AudioBlock &src, SampleType value) noexcept
Adds a fixed value to each source value and stores it in the destination array of the receiver.
forcedinline AudioBlock & add (const AudioBlock &src1, const AudioBlock &src2) noexcept
Adds each source1 value to the corresponding source2 value and stores it in the destination array of the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE subtract (SampleType value) noexcept
Subtracts a fixed value from the receiver.
forcedinline AudioBlock & subtract (const AudioBlock &src) noexcept
Subtracts the source values from the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE subtract (const AudioBlock &src, SampleType value) noexcept
Subtracts a fixed value from each source value and stores it in the destination array of the receiver.
forcedinline AudioBlock & subtract (const AudioBlock &src1, const AudioBlock &src2) noexcept
Subtracts each source2 value from the corresponding source1 value and stores it in the destination array of the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE multiply (SampleType value) noexcept
Multiplies a fixed value to the receiver.
forcedinline AudioBlock & multiply (const AudioBlock &src) noexcept
Multiplies the source values to the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE multiply (const AudioBlock &src, SampleType value) noexcept
Multiplies a fixed value to each source value and stores it in the destination array of the receiver.
forcedinline AudioBlock & multiply (const AudioBlock &src1, const AudioBlock &src2) noexcept
Multiplies each source1 value to the corresponding source2 value and stores it in the destination array of the receiver.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE addWithMultiply (const AudioBlock &src, SampleType factor) noexcept
Multiplies each value in src with factor and adds the result to the receiver.
forcedinline AudioBlock & addWithMultiply (const AudioBlock &src1, const AudioBlock &src2) noexcept
Multiplies each value in srcA with the corresponding value in srcB and adds the result to the receiver.
forcedinline AudioBlock & negate () noexcept
Negates each value of the receiver.
forcedinline AudioBlock & replaceWithNegativeOf (const AudioBlock &src) noexcept
Negates each value of source and stores it in the receiver.
forcedinline AudioBlock & replaceWithAbsoluteValueOf (const AudioBlock &src) noexcept
Takes the absolute value of each element of src and stores it inside the receiver.
forcedinline AudioBlock & min (const AudioBlock &src1, const AudioBlock &src2) noexcept
Each element of receiver will be the minimum of the corresponding element of the source arrays.
forcedinline AudioBlock & max (AudioBlock src1, AudioBlock src2) noexcept
Each element of the receiver will be the maximum of the corresponding element of the source arrays.
forcedinline Range< NumericType > findMinAndMax () const noexcept
Finds the minimum and maximum value of the buffer.
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE operator+= (SampleType src) noexcept
forcedinline AudioBlock & operator+= (AudioBlock src) noexcept
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE operator-= (SampleType src) noexcept
forcedinline AudioBlock & operator-= (AudioBlock src) noexcept
forcedinline AudioBlock
&JUCE_VECTOR_CALLTYPE operator*= (SampleType src) noexcept
forcedinline AudioBlock & operator*= (AudioBlock src) noexcept
Static Public Member Functions
template<typename FunctionType >
static void process (const AudioBlock< SampleType > &inBlock, AudioBlock< SampleType > &outBlock, const FunctionType &function)
Detailed Description
template<typename SampleType>
class AudioBlock< SampleType >
Minimal and lightweight data-structure which contains a list of pointers to channels containing some kind of sample data.
This class doesn't own any of the data which it points to, it's simply a view into data that is owned elsewhere. You can construct one from some raw data that you've allocated yourself, or give it a HeapBlock to use, or give it an AudioSampleBuffer which it can refer to, but in all cases the user is responsible for making sure that the data doesn't get deleted while there's still an AudioBlock using it.
Member Typedef Documentation
template<typename SampleType> using AudioBlock< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
Constructor & Destructor Documentation
template<typename SampleType> forcedinline AudioBlock< SampleType >::AudioBlock () noexcept
Create a zero-sized AudioBlock.
Referenced by AudioBlock< float >::getSingleChannelBlock(), AudioBlock< float >::getSubBlock(), and AudioBlock< float >::getSubsetChannelBlock().
template<typename SampleType> forcedinline AudioBlock< SampleType >::AudioBlock (SampleType *const * channelData, size_t numberOfChannels, size_t numberOfSamples) noexcept
Creates an AudioBlock from a pointer to an array of channels.
AudioBlock does not copy nor own the memory pointed to by dataToUse. Therefore it is the user's responsibility to ensure that the memory is retained throughout the life-time of the AudioBlock and released when no longer needed.
template<typename SampleType> forcedinline AudioBlock< SampleType >::AudioBlock (SampleType *const * channelData, size_t numberOfChannels, size_t startSampleIndex, size_t numberOfSamples) noexcept
Creates an AudioBlock from a pointer to an array of channels.
AudioBlock does not copy nor own the memory pointed to by dataToUse. Therefore it is the user's responsibility to ensure that the memory is retained throughout the life-time of the AudioBlock and released when no longer needed.
template<typename SampleType> AudioBlock< SampleType >::AudioBlock (HeapBlock< char > & heapBlockToUseForAllocation, size_t numberOfChannels, size_t numberOfSamples) noexcept
Allocates a suitable amount of space in a HeapBlock, and initialises this object to point into it.
The HeapBlock must of course not be freed or re-allocated while this object is still in use, because it will be referencing its data.
template<typename SampleType> AudioBlock< SampleType >::AudioBlock (AudioBuffer< SampleType > & buffer) noexcept
Creates an AudioBlock that points to the data in an AudioBuffer.
AudioBlock does not copy nor own the memory pointed to by dataToUse. Therefore it is the user's responsibility to ensure that the buffer is retained throughout the life-time of the AudioBlock without being modified.
template<typename SampleType> AudioBlock< SampleType >::AudioBlock (AudioBuffer< SampleType > & buffer, size_t startSampleIndex) noexcept
Creates an AudioBlock that points to the data in an AudioBuffer.
AudioBlock does not copy nor own the memory pointed to by dataToUse. Therefore it is the user's responsibility to ensure that the buffer is retained throughout the life-time of the AudioBlock without being modified.
template<typename SampleType> AudioBlock< SampleType >::AudioBlock (const AudioBlock< SampleType > & other) default noexcept
Member Function Documentation
template<typename SampleType> AudioBlock& AudioBlock< SampleType >::operator= (const AudioBlock< SampleType > & other) default noexcept
template<typename SampleType> forcedinline size_t AudioBlock< SampleType >::getNumSamples () const noexcept
Referenced by AudioBlock< float >::getSubBlock(), and AudioBlock< float >::process().
template<typename SampleType> forcedinline size_t AudioBlock< SampleType >::getNumChannels () const noexcept
Referenced by AudioBlock< float >::process().
template<typename SampleType> forcedinline const SampleType* AudioBlock< SampleType >::getChannelPointer (size_t channel) const noexcept
Returns a raw pointer into one of the channels in this block.
Referenced by AudioBlock< float >::move(), and AudioBlock< float >::process().
template<typename SampleType> forcedinline SampleType* AudioBlock< SampleType >::getChannelPointer (size_t channel) noexcept
Returns a raw pointer into one of the channels in this block.
template<typename SampleType> forcedinline AudioBlock<SampleType> AudioBlock< SampleType >::getSingleChannelBlock (size_t channel) const noexcept
Returns an AudioBlock that represents one of the channels in this block.
template<typename SampleType> forcedinline AudioBlock<SampleType> AudioBlock< SampleType >::getSubsetChannelBlock (size_t channelStart, size_t numChannelsToUse) noexcept
Returns a subset of continguous channels.
Parameters
channelStart First channel of the subset
numChannelsToUse Count of channels in the subset
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::clear () noexcept
Clear the memory described by this AudioBlock.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::fill (SampleType value) noexcept
Fill memory with value.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::copy (const AudioBlock< SampleType > & src) noexcept
Copy the values in src to the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::move (size_t srcPos, size_t dstPos, size_t numElements = std::numeric_limits<size_t>::max()) noexcept
Move memory within the receiver from the position srcPos to the position dstPos.
If numElements is not specified then move will move the maximum amount of memory.
template<typename SampleType> AudioBlock AudioBlock< SampleType >::getSubBlock (size_t newOffset, size_t newLength) const noexcept
Return a new AudioBlock pointing to a sub-block inside the receiver.
This function does not copy the memory and you must ensure that the original memory pointed to by the receiver remains valid through-out the life-time of the returned sub-block.
Parameters
newOffset The index of an element inside the reciever which will will become the first element of the return value.
newLength The number of elements of the newly created sub-block.
Referenced by AudioBlock< float >::getSubBlock().
template<typename SampleType> AudioBlock AudioBlock< SampleType >::getSubBlock (size_t newOffset) const noexcept
Return a new AudioBlock pointing to a sub-block inside the receiver.
This function does not copy the memory and you must ensure that the original memory pointed to by the receiver remains valid through-out the life-time of the returned sub-block.
Parameters
newOffset The index of an element inside the reciever which will will become the first element of the return value. The return value will include all subsequent elements of the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::add (SampleType value) noexcept
Adds a fixed value to the receiver.
Referenced by AudioBlock< float >::operator+=(), and AudioBlock< float >::subtract().
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::add (const AudioBlock< SampleType > & src) noexcept
Adds the source values to the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::add (const AudioBlock< SampleType > & src, SampleType value) noexcept
Adds a fixed value to each source value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::add (const AudioBlock< SampleType > & src1, const AudioBlock< SampleType > & src2) noexcept
Adds each source1 value to the corresponding source2 value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::subtract (SampleType value) noexcept
Subtracts a fixed value from the receiver.
Referenced by AudioBlock< float >::operator-=().
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::subtract (const AudioBlock< SampleType > & src) noexcept
Subtracts the source values from the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::subtract (const AudioBlock< SampleType > & src, SampleType value) noexcept
Subtracts a fixed value from each source value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::subtract (const AudioBlock< SampleType > & src1, const AudioBlock< SampleType > & src2) noexcept
Subtracts each source2 value from the corresponding source1 value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::multiply (SampleType value) noexcept
Multiplies a fixed value to the receiver.
Referenced by AudioBlock< float >::negate(), and AudioBlock< float >::operator*=().
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::multiply (const AudioBlock< SampleType > & src) noexcept
Multiplies the source values to the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::multiply (const AudioBlock< SampleType > & src, SampleType value) noexcept
Multiplies a fixed value to each source value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::multiply (const AudioBlock< SampleType > & src1, const AudioBlock< SampleType > & src2) noexcept
Multiplies each source1 value to the corresponding source2 value and stores it in the destination array of the receiver.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::addWithMultiply (const AudioBlock< SampleType > & src, SampleType factor) noexcept
Multiplies each value in src with factor and adds the result to the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::addWithMultiply (const AudioBlock< SampleType > & src1, const AudioBlock< SampleType > & src2) noexcept
Multiplies each value in srcA with the corresponding value in srcB and adds the result to the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::negate () noexcept
Negates each value of the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::replaceWithNegativeOf (const AudioBlock< SampleType > & src) noexcept
Negates each value of source and stores it in the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::replaceWithAbsoluteValueOf (const AudioBlock< SampleType > & src) noexcept
Takes the absolute value of each element of src and stores it inside the receiver.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::min (const AudioBlock< SampleType > & src1, const AudioBlock< SampleType > & src2) noexcept
Each element of receiver will be the minimum of the corresponding element of the source arrays.
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::max (AudioBlock< SampleType > src1, AudioBlock< SampleType > src2) noexcept
Each element of the receiver will be the maximum of the corresponding element of the source arrays.
template<typename SampleType> forcedinline Range<NumericType> AudioBlock< SampleType >::findMinAndMax () const noexcept
Finds the minimum and maximum value of the buffer.
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::operator+= (SampleType src) noexcept
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::operator+= (AudioBlock< SampleType > src) noexcept
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::operator-= (SampleType src) noexcept
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::operator-= (AudioBlock< SampleType > src) noexcept
template<typename SampleType> forcedinline AudioBlock& JUCE_VECTOR_CALLTYPE AudioBlock< SampleType >::operator*= (SampleType src) noexcept
template<typename SampleType> forcedinline AudioBlock& AudioBlock< SampleType >::operator*= (AudioBlock< SampleType > src) noexcept
template<typename SampleType> template<typename FunctionType > static void AudioBlock< SampleType >::process (const AudioBlock< SampleType > & inBlock, AudioBlock< SampleType > & outBlock, const FunctionType & function) static
Referenced by WaveShaper< FloatType, Function >::process().
The documentation for this class was generated from the following file:
juce_AudioBlock.h