JUCE: Gain< FloatType > Class Template Reference
Gain< FloatType > Class Template Reference
Applies a gain to audio samples as single samples or AudioBlocks.
Public Member Functions
Gain () noexcept
void setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
void setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
FloatType getGainLinear () const noexcept
Returns the current gain as a linear value.
FloatType getGainDecibels () const noexcept
Returns the current gain in decibels.
void setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
double getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
Resets the internal state of the gain.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType s) noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Detailed Description
template<typename FloatType>
class Gain< FloatType >
Applies a gain to audio samples as single samples or AudioBlocks.
Constructor & Destructor Documentation
template<typename FloatType > Gain< FloatType >::Gain () noexcept
Member Function Documentation
template<typename FloatType > void Gain< FloatType >::setGainLinear (FloatType newGain) noexcept
Applies a new gain as a linear value.
Referenced by Gain< FloatType >::setGainDecibels().
template<typename FloatType > void Gain< FloatType >::setGainDecibels (FloatType newGainDecibels) noexcept
Applies a new gain as a decibel value.
References Gain< FloatType >::setGainLinear().
template<typename FloatType > FloatType Gain< FloatType >::getGainLinear () const noexcept
Returns the current gain as a linear value.
Referenced by Gain< FloatType >::getGainDecibels().
template<typename FloatType > FloatType Gain< FloatType >::getGainDecibels () const noexcept
Returns the current gain in decibels.
References Gain< FloatType >::getGainLinear().
template<typename FloatType > void Gain< FloatType >::setRampDurationSeconds (double newDurationSeconds) noexcept
Sets the length of the ramp used for smoothing gain changes.
References Gain< FloatType >::reset().
template<typename FloatType > double Gain< FloatType >::getRampDurationSeconds () const noexcept
Returns the ramp duration in seconds.
template<typename FloatType > bool Gain< FloatType >::isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
template<typename FloatType > void Gain< FloatType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
References Gain< FloatType >::reset().
template<typename FloatType > void Gain< FloatType >::reset () noexcept
Resets the internal state of the gain.
Referenced by Gain< FloatType >::prepare(), and Gain< FloatType >::setRampDurationSeconds().
template<typename FloatType > template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE Gain< FloatType >::processSample (SampleType s) noexcept
Returns the result of processing a single sample.
template<typename FloatType > template<typename ProcessContext > void Gain< FloatType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References jassert, and FloatVectorOperations::multiply().
The documentation for this class was generated from the following file:
juce_Gain.h