JUCE: NewLine Class Reference
NewLine Class Reference
juce_core » text
This class is used for represent a new-line character sequence.
Public Member Functions
operator String () const
Returns the default new-line sequence that the library uses.
operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
Static Public Member Functions
static const char * getDefault () noexcept
Returns the default new-line sequence that the library uses.
Detailed Description
This class is used for represent a new-line character sequence.
To write a new-line to a stream, you can use the predefined 'newLine' variable, e.g.
myOutputStream << "Hello World" << newLine << newLine;
The exact character sequence that will be used for the new-line can be set and retrieved with OutputStream::setNewLineString() and OutputStream::getNewLineString().
Member Function Documentation
getDefault()
static const char* NewLine::getDefault () static noexcept
Returns the default new-line sequence that the library uses.
See also
OutputStream::setNewLineString()
Referenced by operator+(), operator+=(), and operator<<().
operator String()
NewLine::operator String () const
Returns the default new-line sequence that the library uses.
See also
getDefault()
operator StringRef()
NewLine::operator StringRef () const noexcept
Returns the default new-line sequence that the library uses.
See also
OutputStream::setNewLineString()
References newLine.
The documentation for this class was generated from the following file:
juce_NewLine.h