JUCE: ScopedPointer< ObjectType > Class Template Reference
ScopedPointer< ObjectType > Class Template Reference
juce_core » memory
This class is deprecated.
Public Member Functions
ScopedPointer () noexcept
Creates a ScopedPointer containing a null pointer.
ScopedPointer (decltype(nullptr)) noexcept
Creates a ScopedPointer containing a null pointer.
ScopedPointer (ObjectType *objectToTakePossessionOf) noexcept
Creates a ScopedPointer that owns the specified object.
ScopedPointer (ScopedPointer &objectToTransferFrom) noexcept
Creates a ScopedPointer that takes its pointer from another ScopedPointer.
~ScopedPointer ()
Destructor.
ScopedPointer & operator= (ScopedPointer &objectToTransferFrom)
Changes this ScopedPointer to point to a new object.
ScopedPointer & operator= (ObjectType *newObjectToTakePossessionOf)
Changes this ScopedPointer to point to a new object.
ScopedPointer (ScopedPointer &&other) noexcept
Take ownership of another ScopedPointer.
ScopedPointer & operator= (ScopedPointer &&other) noexcept
Take ownership of another ScopedPointer.
operator ObjectType * () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType * get () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType & operator* () const noexcept
Returns the object that this ScopedPointer refers to.
ObjectType * operator-> () const noexcept
Lets you access methods and properties of the object that this ScopedPointer refers to.
void reset ()
Clears this pointer, deleting the object it points to if there is one.
void reset (ObjectType *newObject)
Sets this pointer to a new object, deleting the old object that it was previously pointing to if there was one.
void reset (ScopedPointer &newObject)
Sets this pointer to a new object, deleting the old object that it was previously pointing to if there was one.
ObjectType * release () noexcept
Detaches and returns the current object from this ScopedPointer without deleting it.
void swapWith (ScopedPointer< ObjectType > &other) noexcept
Swaps this object with that of another ScopedPointer.
ObjectType * createCopy () const
If the pointer is non-null, this will attempt to return a new copy of the object that is pointed to.
Detailed Description
template<class ObjectType>
class ScopedPointer< ObjectType >
This class is deprecated.
You should use std::unique_ptr instead.
A ScopedPointer holds a pointer that is automatically deleted when the ScopedPointer goes out of scope.
Once a pointer has been passed to a ScopedPointer, it will make sure that the pointer gets deleted when the ScopedPointer is deleted. Using the ScopedPointer on the stack or as member variables is a good way to use RAII to avoid accidentally leaking dynamically created objects.
A ScopedPointer can be used in pretty much the same way that you'd use a normal pointer to an object. If you use the assignment operator to assign a different object to a ScopedPointer, the old one will be automatically deleted.
Important note: The class is designed to hold a pointer to an object, NOT to an array! It calls delete on its payload, not delete[], so do not give it an array to hold! For that kind of purpose, you should be using HeapBlock or Array instead.
A const ScopedPointer is guaranteed not to lose ownership of its object or change the object to which it points during its lifetime. This means that making a copy of a const ScopedPointer is impossible, as that would involve the new copy taking ownership from the old one.
If you need to get a pointer out of a ScopedPointer without it being deleted, you can use the release() method.
Constructor & Destructor Documentation
ScopedPointer() [1/5]
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer () noexcept
Creates a ScopedPointer containing a null pointer.
Referenced by ScopedPointer< OutputStream >::createCopy().
ScopedPointer() [2/5]
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (decltype(nullptr)) noexcept
Creates a ScopedPointer containing a null pointer.
ScopedPointer() [3/5]
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ObjectType * objectToTakePossessionOf) noexcept
Creates a ScopedPointer that owns the specified object.
ScopedPointer() [4/5]
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ScopedPointer< ObjectType > & objectToTransferFrom) noexcept
Creates a ScopedPointer that takes its pointer from another ScopedPointer.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
~ScopedPointer()
template<class ObjectType> ScopedPointer< ObjectType >::~ScopedPointer ()
Destructor.
If the ScopedPointer currently refers to an object, it'll be deleted.
ScopedPointer() [5/5]
template<class ObjectType> ScopedPointer< ObjectType >::ScopedPointer (ScopedPointer< ObjectType > && other) noexcept
Take ownership of another ScopedPointer.
Member Function Documentation
operator=() [1/3]
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ScopedPointer< ObjectType > & objectToTransferFrom)
Changes this ScopedPointer to point to a new object.
Because a pointer can only belong to one ScopedPointer, this transfers the pointer from the other object to this one, and the other object is reset to be a null pointer.
If this ScopedPointer already points to an object, that object will first be deleted.
Referenced by ScopedPointer< OutputStream >::createCopy().
operator=() [2/3]
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ObjectType * newObjectToTakePossessionOf)
Changes this ScopedPointer to point to a new object.
If this ScopedPointer already points to an object, that object will first be deleted. The pointer that you pass in may be a nullptr.
operator=() [3/3]
template<class ObjectType> ScopedPointer& ScopedPointer< ObjectType >::operator= (ScopedPointer< ObjectType > && other) noexcept
Take ownership of another ScopedPointer.
operator ObjectType *()
template<class ObjectType> ScopedPointer< ObjectType >::operator ObjectType * () const noexcept
Returns the object that this ScopedPointer refers to.
get()
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::get () const noexcept
Returns the object that this ScopedPointer refers to.
Referenced by operator!=(), and operator==().
operator*()
template<class ObjectType> ObjectType& ScopedPointer< ObjectType >::operator* () const noexcept
Returns the object that this ScopedPointer refers to.
operator->()
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::operator-> () const noexcept
Lets you access methods and properties of the object that this ScopedPointer refers to.
reset() [1/3]
template<class ObjectType> void ScopedPointer< ObjectType >::reset ()
Clears this pointer, deleting the object it points to if there is one.
Referenced by ScopedPointer< OutputStream >::operator=(), ScopedPointer< OutputStream >::reset(), and ScopedPointer< OutputStream >::~ScopedPointer().
reset() [2/3]
template<class ObjectType> void ScopedPointer< ObjectType >::reset (ObjectType * newObject)
Sets this pointer to a new object, deleting the old object that it was previously pointing to if there was one.
reset() [3/3]
template<class ObjectType> void ScopedPointer< ObjectType >::reset (ScopedPointer< ObjectType > & newObject)
Sets this pointer to a new object, deleting the old object that it was previously pointing to if there was one.
release()
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::release () noexcept
Detaches and returns the current object from this ScopedPointer without deleting it.
This will return the current object, and set the ScopedPointer to a null pointer.
Referenced by ScopedPointer< OutputStream >::operator=(), and ScopedPointer< OutputStream >::reset().
swapWith()
template<class ObjectType> void ScopedPointer< ObjectType >::swapWith (ScopedPointer< ObjectType > & other) noexcept
Swaps this object with that of another ScopedPointer.
The two objects simply exchange their pointers.
createCopy()
template<class ObjectType> ObjectType* ScopedPointer< ObjectType >::createCopy () const
If the pointer is non-null, this will attempt to return a new copy of the object that is pointed to.
If the pointer is null, this will safely return a nullptr.
The documentation for this class was generated from the following file:
juce_ScopedPointer.h