JUCE: FIR::Filter< SampleType > Class Template Reference
FIR::Filter< SampleType > Class Template Reference
A processing class that can perform FIR filtering on an audio signal, in the time domain.
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Public Member Functions
Filter ()
This will create a filter which will produce silence.
Filter (Coefficients< NumericType > *coefficientsToUse)
Creates a filter with a given set of coefficients.
Filter (const Filter &)=default
Creates a copy of another filter.
Filter (Filter &&)=default
Creates a copy of another filter.
Filter & operator= (const Filter &)=default
Assignment operator.
Filter & operator= (Filter &&)=default
Assignment operator.
void prepare (const ProcessSpec &spec) noexcept
Prepare this filter for processing.
void reset ()
Resets the filter's processing pipeline, ready to start a new stream of data.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes as a block of samples.
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType sample) noexcept
Processes a single sample, without any locking.
Public Attributes
Coefficients< NumericType >::Ptr coefficients
The coefficients of the FIR filter.
Detailed Description
template<typename SampleType>
class FIR::Filter< SampleType >
A processing class that can perform FIR filtering on an audio signal, in the time domain.
Using FIRFilter is fast enough for FIRCoefficients with a size lower than 128 samples. For longer filters, it might be more efficient to use the class Convolution instead, which does the same processing in the frequency domain thanks to FFT.
See Also
FIRFilter::Coefficients, Convolution, FFT
Member Typedef Documentation
template<typename SampleType > using FIR::Filter< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Constructor & Destructor Documentation
template<typename SampleType > FIR::Filter< SampleType >::Filter ()
This will create a filter which will produce silence.
References FIR::Filter< SampleType >::reset().
template<typename SampleType > FIR::Filter< SampleType >::Filter (Coefficients< NumericType > * coefficientsToUse)
Creates a filter with a given set of coefficients.
References FIR::Filter< SampleType >::reset().
template<typename SampleType > FIR::Filter< SampleType >::Filter (const Filter< SampleType > &) default
Creates a copy of another filter.
template<typename SampleType > FIR::Filter< SampleType >::Filter (Filter< SampleType > &&) default
Creates a copy of another filter.
Member Function Documentation
template<typename SampleType > Filter& FIR::Filter< SampleType >::operator= (const Filter< SampleType > &) default
Assignment operator.
template<typename SampleType > Filter& FIR::Filter< SampleType >::operator= (Filter< SampleType > &&) default
Assignment operator.
template<typename SampleType > void FIR::Filter< SampleType >::prepare (const ProcessSpec & spec) noexcept
Prepare this filter for processing.
References ignoreUnused(), jassert, and FIR::Filter< SampleType >::reset().
template<typename SampleType > void FIR::Filter< SampleType >::reset ()
Resets the filter's processing pipeline, ready to start a new stream of data.
Note that this clears the processing state, but the type of filter and its coefficients aren't changed. To disable the filter, call setEnabled (false).
References FIR::Filter< SampleType >::coefficients, HeapBlock< ElementType, throwOnFailure >::getData(), jmax(), HeapBlock< ElementType, throwOnFailure >::malloc(), and snapPointerToAlignment().
Referenced by FIR::Filter< SampleType >::Filter(), and FIR::Filter< SampleType >::prepare().
template<typename SampleType > template<typename ProcessContext > void FIR::Filter< SampleType >::process (const ProcessContext & context) noexcept
Processes as a block of samples.
References FIR::Filter< SampleType >::coefficients, and jassert.
template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE FIR::Filter< SampleType >::processSample (SampleType sample) noexcept
Processes a single sample, without any locking.
Use this if you need processing of a single value.
References FIR::Filter< SampleType >::coefficients.
Member Data Documentation
template<typename SampleType > Coefficients<NumericType>::Ptr FIR::Filter< SampleType >::coefficients
The coefficients of the FIR filter.
It's up to the called to ensure that these coefficients are modified in a thread-safe way.
If you change the order of the coefficients then you must call reset after modifying them.
Referenced by FIR::Filter< SampleType >::process(), FIR::Filter< SampleType >::processSample(), and FIR::Filter< SampleType >::reset().
The documentation for this class was generated from the following file:
juce_FIRFilter.h