JUCE: TableListBox Class Reference
TableListBox Class Reference
juce_gui_basics » widgets
A table of cells, using a TableHeaderComponent as its header.
Public Member Functions
TableListBox (const String &componentName=String(), TableListBoxModel *model=nullptr)
Creates a TableListBox.
~TableListBox () override
Destructor.
void setModel (TableListBoxModel *newModel)
Changes the TableListBoxModel that is being used for this table.
TableListBoxModel * getModel () const noexcept
Returns the model currently in use.
TableHeaderComponent & getHeader () const noexcept
Returns the header component being used in this table.
void setHeader (TableHeaderComponent *newHeader)
Sets the header component to use for the table.
void setHeaderHeight (int newHeight)
Changes the height of the table header component.
int getHeaderHeight () const noexcept
Returns the height of the table header.
void autoSizeColumn (int columnId)
Resizes a column to fit its contents.
void autoSizeAllColumns ()
Calls autoSizeColumn() for all columns in the table.
void setAutoSizeMenuOptionShown (bool shouldBeShown) noexcept
Enables or disables the auto size options on the popup menu.
bool isAutoSizeMenuOptionShown () const noexcept
True if the auto-size options should be shown on the menu.
Rectangle< int > getCellPosition (int columnId, int rowNumber, bool relativeToComponentTopLeft) const
Returns the position of one of the cells in the table.
Component * getCellComponent (int columnId, int rowNumber) const
Returns the component that currently represents a given cell.
void scrollToEnsureColumnIsOnscreen (int columnId)
Scrolls horizontally if necessary to make sure that a particular column is visible.
int getNumRows () override
void paintListBoxItem (int, Graphics &, int, int, bool) override
Component * refreshComponentForRow (int rowNumber, bool isRowSelected, Component *existingComponentToUpdate) override
void selectedRowsChanged (int row) override
void deleteKeyPressed (int currentSelectedRow) override
void returnKeyPressed (int currentSelectedRow) override
void backgroundClicked (const MouseEvent &) override
void listWasScrolled () override
void tableColumnsChanged (TableHeaderComponent *) override
void tableColumnsResized (TableHeaderComponent *) override
void tableSortOrderChanged (TableHeaderComponent *) override
void tableColumnDraggingChanged (TableHeaderComponent *, int) override
void resized () override
Public Member Functions inherited from ListBox
ListBox (const String &componentName=String(), ListBoxModel *model=nullptr)
Creates a ListBox.
~ListBox () override
Destructor.
void setModel (ListBoxModel *newModel)
Changes the current data model to display.
ListBoxModel * getModel () const noexcept
Returns the current list model.
void updateContent ()
Causes the list to refresh its content.
void setMultipleSelectionEnabled (bool shouldBeEnabled) noexcept
Turns on multiple-selection of rows.
void setClickingTogglesRowSelection (bool flipRowSelection) noexcept
If enabled, this makes the listbox flip the selection status of each row that the user clicks, without affecting other selected rows.
void setRowSelectedOnMouseDown (bool isSelectedOnMouseDown) noexcept
Sets whether a row should be selected when the mouse is pressed or released.
void setMouseMoveSelectsRows (bool shouldSelect)
Makes the list react to mouse moves by selecting the row that the mouse if over.
void selectRow (int rowNumber, bool dontScrollToShowThisRow=false, bool deselectOthersFirst=true)
Selects a row.
void selectRangeOfRows (int firstRow, int lastRow, bool dontScrollToShowThisRange=false)
Selects a set of rows.
void deselectRow (int rowNumber)
Deselects a row.
void deselectAllRows ()
Deselects any currently selected rows.
void flipRowSelection (int rowNumber)
Selects or deselects a row.
SparseSet< int > getSelectedRows () const
Returns a sparse set indicating the rows that are currently selected.
void setSelectedRows (const SparseSet< int > &setOfRowsToBeSelected, NotificationType sendNotificationEventToModel=sendNotification)
Sets the rows that should be selected, based on an explicit set of ranges.
bool isRowSelected (int rowNumber) const
Checks whether a row is selected.
int getNumSelectedRows () const
Returns the number of rows that are currently selected.
int getSelectedRow (int index=0) const
Returns the row number of a selected row.
int getLastRowSelected () const
Returns the last row that the user selected.
void selectRowsBasedOnModifierKeys (int rowThatWasClickedOn, ModifierKeys modifiers, bool isMouseUpEvent)
Multiply-selects rows based on the modifier keys.
void setVerticalPosition (double newProportion)
Scrolls the list to a particular position.
double getVerticalPosition () const
Returns the current vertical position as a proportion of the total.
void scrollToEnsureRowIsOnscreen (int row)
Scrolls if necessary to make sure that a particular row is visible.
ScrollBar & getVerticalScrollBar () const noexcept
Returns a reference to the vertical scrollbar.
ScrollBar & getHorizontalScrollBar () const noexcept
Returns a reference to the horizontal scrollbar.
int getRowContainingPosition (int x, int y) const noexcept
Finds the row index that contains a given x,y position.
int getInsertionIndexForPosition (int x, int y) const noexcept
Finds a row index that would be the most suitable place to insert a new item for a given position.
Rectangle< int > getRowPosition (int rowNumber, bool relativeToComponentTopLeft) const noexcept
Returns the position of one of the rows, relative to the top-left of the listbox.
Component * getComponentForRowNumber (int rowNumber) const noexcept
Finds the row component for a given row in the list.
int getRowNumberOfComponent (Component *rowComponent) const noexcept
Returns the row number that the given component represents.
int getVisibleRowWidth () const noexcept
Returns the width of a row (which may be less than the width of this component if there's a scrollbar).
void setRowHeight (int newHeight)
Sets the height of each row in the list.
int getRowHeight () const noexcept
Returns the height of a row in the list.
int getNumRowsOnScreen () const noexcept
Returns the number of rows actually visible.
void setOutlineThickness (int outlineThickness)
Sets the thickness of a border that will be drawn around the box.
int getOutlineThickness () const noexcept
Returns the thickness of outline that will be drawn around the listbox.
void setHeaderComponent (Component *newHeaderComponent)
Sets a component that the list should use as a header.
Component * getHeaderComponent () const noexcept
Returns whatever header component was set with setHeaderComponent().
void setMinimumContentWidth (int newMinimumWidth)
Changes the width of the rows in the list.
int getVisibleContentWidth () const noexcept
Returns the space currently available for the row items, taking into account borders, scrollbars, etc.
void repaintRow (int rowNumber) noexcept
Repaints one of the rows.
virtual Image createSnapshotOfRows (const SparseSet< int > &rows, int &x, int &y)
This fairly obscure method creates an image that shows the row components specified in rows (for example, these could be the currently selected row components).
Viewport * getViewport () const noexcept
Returns the viewport that this ListBox uses.
bool keyPressed (const KeyPress &) override
bool keyStateChanged (bool isKeyDown) override
void paint (Graphics &) override
void paintOverChildren (Graphics &) override
void visibilityChanged () override
void mouseWheelMove (const MouseEvent &, const MouseWheelDetails &) override
void mouseUp (const MouseEvent &) override
void colourChanged () override
void parentHierarchyChanged () override
void startDragAndDrop (const MouseEvent &, const SparseSet< int > &rowsToDrag, const var &dragDescription, bool allowDraggingToOtherWindows)
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
~Component () override
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
virtual void setName (const String &newName)
Sets the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
bool isShowing () const
Tests whether this component and all its parents are visible.
virtual void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr)
Makes this component appear as a window on the desktop.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsRelative (Rectangle< float > proportionalArea)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (Rectangle< int > targetArea, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
bool isPaintingUnclipped () const noexcept
Returns true if this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
virtual void lookAndFeelChanged ()
Called to let the component react to a change in the look-and-feel setting.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparancy level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
void mouseDown (const MouseEvent &event) override
Called when a mouse button is pressed.
void mouseDrag (const MouseEvent &event) override
Called when the mouse is moved while a button is held down.
void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
void mouseMagnify (const MouseEvent &event, float scaleFactor) override
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
virtual void focusOfChildComponentChanged (FocusChangeType cause)
Called to indicate a change in whether or not this component is the parent of the currently-focused component.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown (bool includeChildren=false) const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void moved ()
Called when this component's position has been changed.
virtual void childBoundsChanged (Component *child)
Called when one of this component's children is moved or resized.
virtual void parentSizeChanged ()
Called when this component's immediate parent has been resized.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourID, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourID, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourID)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourID) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()=default
Destructor.
Public Member Functions inherited from SettableTooltipClient
~SettableTooltipClient () override=default
Destructor.
virtual void setTooltip (const String &newTooltip)
Assigns a new tooltip to this object.
String getTooltip () override
Returns the tooltip assigned to this object.
Public Member Functions inherited from TooltipClient
virtual ~TooltipClient ()=default
Destructor.
Additional Inherited Members
Public Types inherited from ListBox
enum ColourIds { backgroundColourId = 0x1002800, outlineColourId = 0x1002810, textColourId = 0x1002820 }
A set of colour IDs to use to change the colour of various aspects of the label.
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusGained() and focusLost() methods.
Static Public Member Functions inherited from Component
static float JUCE_CALLTYPE getApproximateScaleFactorForComponent (Component *targetComponent)
Returns the approximate scale factor for a given component by traversing its parent hierarchy and applying each transform and finally scaling this by the global scale factor.
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Protected Member Functions inherited from SettableTooltipClient
SettableTooltipClient ()=default
Detailed Description
A table of cells, using a TableHeaderComponent as its header.
This component makes it easy to create a table by providing a TableListBoxModel as the data source.
See also
TableListBoxModel, TableHeaderComponent
Constructor & Destructor Documentation
TableListBox()
TableListBox::TableListBox (const String & componentName = String(), TableListBoxModel * model = nullptr)
Creates a TableListBox.
The model pointer passed-in can be null, in which case you can set it later with setModel(). The TableListBox does not take ownership of the model - it's the caller's responsibility to manage its lifetime and make sure it doesn't get deleted while still being used.
~TableListBox()
TableListBox::~TableListBox () override
Destructor.
Member Function Documentation
setModel()
void TableListBox::setModel (TableListBoxModel * newModel)
Changes the TableListBoxModel that is being used for this table.
The TableListBox does not take ownership of the model - it's the caller's responsibility to manage its lifetime and make sure it doesn't get deleted while still being used.
getModel()
TableListBoxModel* TableListBox::getModel () const noexcept
Returns the model currently in use.
getHeader()
TableHeaderComponent& TableListBox::getHeader () const noexcept
Returns the header component being used in this table.
setHeader()
void TableListBox::setHeader (TableHeaderComponent * newHeader)
Sets the header component to use for the table.
The table will take ownership of the component that you pass in, and will delete it when it's no longer needed. The pointer passed in may not be null.
setHeaderHeight()
void TableListBox::setHeaderHeight (int newHeight)
Changes the height of the table header component.
See also
getHeaderHeight
getHeaderHeight()
int TableListBox::getHeaderHeight () const noexcept
Returns the height of the table header.
See also
setHeaderHeight
autoSizeColumn()
void TableListBox::autoSizeColumn (int columnId)
Resizes a column to fit its contents.
This uses TableListBoxModel::getColumnAutoSizeWidth() to find the best width, and applies that to the column.
See also
autoSizeAllColumns, TableHeaderComponent::setColumnWidth
autoSizeAllColumns()
void TableListBox::autoSizeAllColumns ()
Calls autoSizeColumn() for all columns in the table.
setAutoSizeMenuOptionShown()
void TableListBox::setAutoSizeMenuOptionShown (bool shouldBeShown) noexcept
Enables or disables the auto size options on the popup menu.
By default, these are enabled.
isAutoSizeMenuOptionShown()
bool TableListBox::isAutoSizeMenuOptionShown () const noexcept
True if the auto-size options should be shown on the menu.
See also
setAutoSizeMenuOptionShown
References ListBoxModel::backgroundClicked(), ListBoxModel::deleteKeyPressed(), ListBoxModel::getNumRows(), JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, ListBoxModel::listWasScrolled(), ListBoxModel::paintListBoxItem(), ListBoxModel::refreshComponentForRow(), ListBox::resized(), ListBoxModel::returnKeyPressed(), ListBoxModel::selectedRowsChanged(), TableHeaderComponent::Listener::tableColumnDraggingChanged(), TableHeaderComponent::Listener::tableColumnsChanged(), TableHeaderComponent::Listener::tableColumnsResized(), and TableHeaderComponent::Listener::tableSortOrderChanged().
getCellPosition()
Rectangle<int> TableListBox::getCellPosition (int columnId, int rowNumber, bool relativeToComponentTopLeft) const
Returns the position of one of the cells in the table.
If relativeToComponentTopLeft is true, the coordinates are relative to the table component's top-left. The row number isn't checked to see if it's in-range, but the column ID must exist or this will return an empty rectangle.
If relativeToComponentTopLeft is false, the coordinates are relative to the top-left of the table's top-left cell.
getCellComponent()
Component* TableListBox::getCellComponent (int columnId, int rowNumber) const
Returns the component that currently represents a given cell.
If the component for this cell is off-screen or if the position is out-of-range, this may return nullptr.
See also
getCellPosition
scrollToEnsureColumnIsOnscreen()
void TableListBox::scrollToEnsureColumnIsOnscreen (int columnId)
Scrolls horizontally if necessary to make sure that a particular column is visible.
See also
ListBox::scrollToEnsureRowIsOnscreen
getNumRows()
int TableListBox::getNumRows () override virtual
Implements ListBoxModel.
paintListBoxItem()
void TableListBox::paintListBoxItem (int , Graphics & , int , int , bool) override virtual
Implements ListBoxModel.
refreshComponentForRow()
Component* TableListBox::refreshComponentForRow (int rowNumber, bool isRowSelected, Component * existingComponentToUpdate) override virtual
Reimplemented from ListBoxModel.
selectedRowsChanged()
void TableListBox::selectedRowsChanged (int row) override virtual
Reimplemented from ListBoxModel.
deleteKeyPressed()
void TableListBox::deleteKeyPressed (int currentSelectedRow) override virtual
Reimplemented from ListBoxModel.
returnKeyPressed()
void TableListBox::returnKeyPressed (int currentSelectedRow) override virtual
Reimplemented from ListBoxModel.
backgroundClicked()
void TableListBox::backgroundClicked (const MouseEvent &) override virtual
Reimplemented from ListBoxModel.
listWasScrolled()
void TableListBox::listWasScrolled () override virtual
Reimplemented from ListBoxModel.
tableColumnsChanged()
void TableListBox::tableColumnsChanged (TableHeaderComponent *) override virtual
Implements TableHeaderComponent::Listener.
tableColumnsResized()
void TableListBox::tableColumnsResized (TableHeaderComponent *) override virtual
Implements TableHeaderComponent::Listener.
tableSortOrderChanged()
void TableListBox::tableSortOrderChanged (TableHeaderComponent *) override virtual
Implements TableHeaderComponent::Listener.
tableColumnDraggingChanged()
void TableListBox::tableColumnDraggingChanged (TableHeaderComponent * , int) override virtual
Reimplemented from TableHeaderComponent::Listener.
resized()
void TableListBox::resized () override virtual
Reimplemented from ListBox.
The documentation for this class was generated from the following file:
juce_TableListBox.h