JUCE: dsp::LadderFilter< Type > Class Template Reference
dsp::LadderFilter< Type > Class Template Reference
juce_dsp » processors
Multi-mode filter based on the Moog ladder filter.
Public Types
enum Mode { Mode::LPF12, Mode::HPF12, Mode::LPF24, Mode::HPF24 }
Public Member Functions
LadderFilter ()
Creates an uninitialised filter.
void setEnabled (bool newValue) noexcept
Enables or disables the filter.
void setMode (Mode newValue) noexcept
Sets filter mode.
void prepare (const juce::dsp::ProcessSpec &spec)
Initialises the filter.
size_t getNumChannels () const noexcept
Returns the current number of channels.
void reset () noexcept
Resets the internal state variables of the filter.
void setCutoffFrequencyHz (Type newValue) noexcept
Sets the cutoff frequency of the filter.
void setResonance (Type newValue) noexcept
Sets the resonance of the filter.
void setDrive (Type newValue) noexcept
Sets the amound of saturation in the filter.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Protected Member Functions
Type processSample (Type inputValue, size_t channelToUse) noexcept
void updateSmoothers () noexcept
Detailed Description
template<typename Type>
class dsp::LadderFilter< Type >
Multi-mode filter based on the Moog ladder filter.
Member Enumeration Documentation
Mode
template<typename Type > enum dsp::LadderFilter::Mode strong
Enumerator
LPF12
HPF12
LPF24
HPF24
Constructor & Destructor Documentation
LadderFilter()
template<typename Type > dsp::LadderFilter< Type >::LadderFilter ()
Creates an uninitialised filter.
Call prepare() before first use.
Member Function Documentation
setEnabled()
template<typename Type > void dsp::LadderFilter< Type >::setEnabled (bool newValue) noexcept
Enables or disables the filter.
If disabled it will simply pass through the input signal.
References dsp::LadderFilter< Type >::prepare(), and dsp::LadderFilter< Type >::setMode().
setMode()
template<typename Type > void dsp::LadderFilter< Type >::setMode (Mode newValue) noexcept
Sets filter mode.
Referenced by dsp::LadderFilter< Type >::setEnabled().
prepare()
template<typename Type > void dsp::LadderFilter< Type >::prepare (const juce::dsp::ProcessSpec & spec)
Initialises the filter.
Referenced by dsp::LadderFilter< Type >::setEnabled().
getNumChannels()
template<typename Type > size_t dsp::LadderFilter< Type >::getNumChannels () const noexcept
Returns the current number of channels.
References dsp::LadderFilter< Type >::reset(), dsp::LadderFilter< Type >::setCutoffFrequencyHz(), dsp::LadderFilter< Type >::setDrive(), and dsp::LadderFilter< Type >::setResonance().
Referenced by dsp::LadderFilter< Type >::process().
reset()
template<typename Type > void dsp::LadderFilter< Type >::reset () noexcept
Resets the internal state variables of the filter.
Referenced by dsp::LadderFilter< Type >::getNumChannels().
setCutoffFrequencyHz()
template<typename Type > void dsp::LadderFilter< Type >::setCutoffFrequencyHz (Type newValue) noexcept
Sets the cutoff frequency of the filter.
Parameters
newValue cutoff frequency in Hz
Referenced by dsp::LadderFilter< Type >::getNumChannels().
setResonance()
template<typename Type > void dsp::LadderFilter< Type >::setResonance (Type newValue) noexcept
Sets the resonance of the filter.
Parameters
newValue a value between 0 and 1; higher values increase the resonance and can result in self oscillation!
Referenced by dsp::LadderFilter< Type >::getNumChannels().
setDrive()
template<typename Type > void dsp::LadderFilter< Type >::setDrive (Type newValue) noexcept
Sets the amound of saturation in the filter.
Parameters
newValue saturation amount; it can be any number greater than or equal to one. Higher values result in more distortion.
Referenced by dsp::LadderFilter< Type >::getNumChannels().
process()
template<typename Type > template<typename ProcessContext > void dsp::LadderFilter< Type >::process (const ProcessContext & context) noexcept
References dsp::LadderFilter< Type >::getNumChannels(), jassert, jmap(), dsp::LadderFilter< Type >::processSample(), SmoothedValue< FloatType, SmoothingType >::setTargetValue(), and dsp::LadderFilter< Type >::updateSmoothers().
processSample()
template<typename Type > Type dsp::LadderFilter< Type >::processSample (Type inputValue, size_t channelToUse) protected noexcept
Referenced by dsp::LadderFilter< Type >::process().
updateSmoothers()
template<typename Type > void dsp::LadderFilter< Type >::updateSmoothers () protected noexcept
Referenced by dsp::LadderFilter< Type >::process().
The documentation for this class was generated from the following file:
juce_LadderFilter.h