JUCE: Oscillator< SampleType > Class Template Reference
Oscillator< SampleType > Class Template Reference
Generates a signal based on a user-supplied function.
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Public Member Functions
Oscillator (const std::function< NumericType(NumericType)> &function, size_t lookupTableNumPoints=0)
Creates an oscillator with a periodic input function (-pi..pi).
void setFrequency (NumericType newGain) noexcept
Sets the frequency of the oscillator.
NumericType getFrequency () const noexcept
Returns the current frequency of the oscillator.
void prepare (const ProcessSpec &spec) noexcept
Called before processing starts.
void reset () noexcept
Resets the internal state of the oscillator.
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType) noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
Processes the input and output buffers supplied in the processing context.
Detailed Description
template<typename SampleType>
class Oscillator< SampleType >
Generates a signal based on a user-supplied function.
Member Typedef Documentation
template<typename SampleType > using Oscillator< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Constructor & Destructor Documentation
template<typename SampleType > Oscillator< SampleType >::Oscillator (const std::function< NumericType(NumericType)> & function, size_t lookupTableNumPoints = 0)
Creates an oscillator with a periodic input function (-pi..pi).
If lookup table is not zero, then the function will be approximated with a lookup table.
References double_Pi.
Member Function Documentation
template<typename SampleType > void Oscillator< SampleType >::setFrequency (NumericType newGain) noexcept
Sets the frequency of the oscillator.
References LinearSmoothedValue< FloatType >::setValue().
template<typename SampleType > NumericType Oscillator< SampleType >::getFrequency () const noexcept
Returns the current frequency of the oscillator.
References LinearSmoothedValue< FloatType >::getTargetValue().
template<typename SampleType > void Oscillator< SampleType >::prepare (const ProcessSpec & spec) noexcept
Called before processing starts.
References Oscillator< SampleType >::reset(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::resize().
template<typename SampleType > void Oscillator< SampleType >::reset () noexcept
Resets the internal state of the oscillator.
References LinearSmoothedValue< FloatType >::reset().
Referenced by Oscillator< SampleType >::prepare().
template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE Oscillator< SampleType >::processSample (SampleType) noexcept
Returns the result of processing a single sample.
References double_Pi, and LinearSmoothedValue< FloatType >::getNextValue().
template<typename SampleType > template<typename ProcessContext > void Oscillator< SampleType >::process (const ProcessContext & context) noexcept
Processes the input and output buffers supplied in the processing context.
References double_Pi, LinearSmoothedValue< FloatType >::getNextValue(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer(), LinearSmoothedValue< FloatType >::isSmoothing(), jassert, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
The documentation for this class was generated from the following file:
juce_Oscillator.h