JUCE: AudioCDBurner::BurnProgressListener Class Reference
AudioCDBurner::BurnProgressListener Class Reference abstract
juce_audio_utils » audio_cd
Receives progress callbacks during a cd-burn operation.
Public Member Functions
BurnProgressListener () noexcept
virtual ~BurnProgressListener ()
virtual bool audioCDBurnProgress (float proportionComplete)=0
Called at intervals to report on the progress of the AudioCDBurner.
Detailed Description
Receives progress callbacks during a cd-burn operation.
See also
AudioCDBurner::burn()
Constructor & Destructor Documentation
BurnProgressListener()
AudioCDBurner::BurnProgressListener::BurnProgressListener () noexcept
~BurnProgressListener()
virtual AudioCDBurner::BurnProgressListener::~BurnProgressListener () virtual
References AudioCDBurner::abortBurn(), audioCDBurnProgress(), AudioCDBurner::burn(), and JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR.
Member Function Documentation
audioCDBurnProgress()
virtual bool AudioCDBurner::BurnProgressListener::audioCDBurnProgress (float proportionComplete) pure virtual
Called at intervals to report on the progress of the AudioCDBurner.
To cancel the burn, return true from this method.
Referenced by ~BurnProgressListener().
The documentation for this class was generated from the following file:
juce_AudioCDBurner.h