JUCE: Polynomial< FloatingType > Class Template Reference
Polynomial< FloatingType > Class Template Reference
A class representing a polynomial.
Public Member Functions
Polynomial ()
Creates a new polynomial which will always evaluate to zero.
Polynomial (const FloatingType *coefficients, int numCoefficients)
Creates a new polynomial with given coefficients.
Polynomial (const Polynomial &)=default
Creates a copy of another polynomial.
Polynomial (Polynomial &&)=default
Creates a copy of another polynomial.
Polynomial & operator= (const Polynomial &)=default
Creates a copy of another polynomial.
Polynomial & operator= (Polynomial &&)=default
Creates a copy of another polynomial.
template<typename TypeToCreateFrom >
Polynomial (const std::initializer_list< TypeToCreateFrom > &items)
Creates a new polynomial with coefficients by a C++11 initializer list.
FloatingType operator[] (int index) const noexcept
Returns a single coefficient of the receiver for reading.
FloatingType & operator[] (int index) noexcept
Returns a single coefficient of the receiver for modifying.
FloatingType operator() (FloatingType x) const noexcept
Evaluates the value of the polynomial at a single point x.
int getOrder () noexcept
Returns the order of the polynomial.
Polynomial< FloatingType > withGain (double gain) const
Returns the polynomial with all its coefficients multiplied with a gain factor.
Polynomial< FloatingType > getSumWith (const Polynomial< FloatingType > &other) const
Returns the sum of this polynomial with another.
Polynomial< FloatingType > getProductWith (const Polynomial< FloatingType > &other) const
computes the product of two polynomials and return the result
Detailed Description
template<typename FloatingType>
class Polynomial< FloatingType >
A class representing a polynomial.
Constructor & Destructor Documentation
template<typename FloatingType> Polynomial< FloatingType >::Polynomial ()
Creates a new polynomial which will always evaluate to zero.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (const FloatingType * coefficients, int numCoefficients)
Creates a new polynomial with given coefficients.
Parameters
numCoefficients The number of coefficients stored in coefficients. This is also the order of the returned polynomial.
coefficients The coefficients which will be used by the newly created polynomial. The Polynomial class will keep a private copy of the coefficients.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::isEmpty(), and jassert.
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (const Polynomial< FloatingType > &) default
Creates a copy of another polynomial.
template<typename FloatingType> Polynomial< FloatingType >::Polynomial (Polynomial< FloatingType > &&) default
Creates a copy of another polynomial.
template<typename FloatingType> template<typename TypeToCreateFrom > Polynomial< FloatingType >::Polynomial (const std::initializer_list< TypeToCreateFrom > & items)
Creates a new polynomial with coefficients by a C++11 initializer list.
This function can be used in the following way: Polynomial<float> p ({0.5f, -0.3f, 0.2f});
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::isEmpty(), and jassert.
Member Function Documentation
template<typename FloatingType> Polynomial& Polynomial< FloatingType >::operator= (const Polynomial< FloatingType > &) default
Creates a copy of another polynomial.
template<typename FloatingType> Polynomial& Polynomial< FloatingType >::operator= (Polynomial< FloatingType > &&) default
Creates a copy of another polynomial.
template<typename FloatingType> FloatingType Polynomial< FloatingType >::operator[] (int index) const noexcept
Returns a single coefficient of the receiver for reading.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked().
template<typename FloatingType> FloatingType& Polynomial< FloatingType >::operator[] (int index) noexcept
Returns a single coefficient of the receiver for modifying.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference().
template<typename FloatingType> FloatingType Polynomial< FloatingType >::operator() (FloatingType x) const noexcept
Evaluates the value of the polynomial at a single point x.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename FloatingType> int Polynomial< FloatingType >::getOrder () noexcept
Returns the order of the polynomial.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::withGain (double gain) const
Returns the polynomial with all its coefficients multiplied with a gain factor.
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::getSumWith (const Polynomial< FloatingType > & other) const
Returns the sum of this polynomial with another.
References Polynomial< FloatingType >::getSumWith(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by Polynomial< FloatingType >::getSumWith().
template<typename FloatingType> Polynomial<FloatingType> Polynomial< FloatingType >::getProductWith (const Polynomial< FloatingType > & other) const
computes the product of two polynomials and return the result
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick(), jmax(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
The documentation for this class was generated from the following file:
juce_Polynomial.h