JUCE: LogSmoothedValue< FloatType > Class Template Reference
LogSmoothedValue< FloatType > Class Template Reference
juce_audio_basics » utilities
Utility class for logarithmically smoothed values.
Public Member Functions
LogSmoothedValue ()=default
Constructor.
LogSmoothedValue (FloatType initialValue) noexcept
Constructor.
void setLogParameters (FloatType midPointAmplitudedB, bool rateOfChangeShouldIncrease) noexcept
Sets the behaviour of the log ramp.
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
void reset (int numSteps) noexcept
Set a new ramp length directly in samples.
void setTargetValue (FloatType newValue) noexcept
Set a new target value.
FloatType getNextValue () noexcept
Compute the next value.
FloatType skip (int numSamples) noexcept
Skip the next numSamples samples.
Public Member Functions inherited from SmoothedValueBase< LogSmoothedValue, FloatType >
SmoothedValueBase ()=default
Constructor.
bool isSmoothing () const noexcept
Returns true if the current value is currently being interpolated.
FloatType getCurrentValue () const noexcept
Returns the current value of the ramp.
FloatType getTargetValue () const noexcept
Returns the target value towards which the smoothed value is currently moving.
void setCurrentAndTargetValue (FloatType newValue)
Sets the current value and the target value.
void applyGain (FloatType *samples, int numSamples) noexcept
Applies a smoothed gain to a stream of samples S[i] *= gain.
void applyGain (FloatType *samplesOut, const FloatType *samplesIn, int numSamples) noexcept
Computes output as a smoothed gain applied to a stream of samples.
void applyGain (AudioBuffer< FloatType > &buffer, int numSamples) noexcept
Applies a smoothed gain to a buffer.
Additional Inherited Members
Protected Member Functions inherited from SmoothedValueBase< LogSmoothedValue, FloatType >
void reset (double sampleRate, double rampLengthInSeconds) noexcept
Protected Attributes inherited from SmoothedValueBase< LogSmoothedValue, FloatType >
FloatType currentValue
FloatType target
int countdown
Detailed Description
template<typename FloatType>
class LogSmoothedValue< FloatType >
Utility class for logarithmically smoothed values.
Logarithmically smoothed values can be more relevant than linear ones for specific cases such as algorithm change smoothing, using two of them in opposite directions.
See also
LinearSmoothedValue
Constructor & Destructor Documentation
LogSmoothedValue() [1/2]
template<typename FloatType > LogSmoothedValue< FloatType >::LogSmoothedValue () default
Constructor.
LogSmoothedValue() [2/2]
template<typename FloatType > LogSmoothedValue< FloatType >::LogSmoothedValue (FloatType initialValue) noexcept
Constructor.
References SmoothedValueBase< SmoothedValueClass, FloatType >::currentValue, and SmoothedValueBase< SmoothedValueClass, FloatType >::target.
Member Function Documentation
setLogParameters()
template<typename FloatType > void LogSmoothedValue< FloatType >::setLogParameters (FloatType midPointAmplitudedB, bool rateOfChangeShouldIncrease) noexcept
Sets the behaviour of the log ramp.
Parameters
midPointAmplitudedB Sets the amplitude of the mid point in decibels, with the target value at 0 dB and the initial value at -inf dB
rateOfChangeShouldIncrease If true then the ramp starts shallow and gets progressively steeper, if false then the ramp is initially steep and flattens out as you approach the target value
References Decibels::decibelsToGain(), and jassert.
reset() [1/2]
template<typename FloatType > void LogSmoothedValue< FloatType >::reset (double sampleRate, double rampLengthInSeconds) noexcept
Reset to a new sample rate and ramp length.
Parameters
sampleRate The sample rate
rampLengthInSeconds The duration of the ramp in seconds
References jassert, and SmoothedValueBase< SmoothedValueClass, FloatType >::reset().
reset() [2/2]
template<typename FloatType > void LogSmoothedValue< FloatType >::reset (int numSteps) noexcept
Set a new ramp length directly in samples.
Parameters
numSteps The number of samples over which the ramp should be active
increasingRateOfChange If the log behaviour makes the ramp increase slowly at the beginning, rather than at the end
References SmoothedValueBase< SmoothedValueClass, FloatType >::setCurrentAndTargetValue(), and SmoothedValueBase< SmoothedValueClass, FloatType >::target.
setTargetValue()
template<typename FloatType > void LogSmoothedValue< FloatType >::setTargetValue (FloatType newValue) noexcept
Set a new target value.
Parameters
newValue The new target value
force If true, the value will be set immediately, bypassing the ramp
References SmoothedValueBase< SmoothedValueClass, FloatType >::countdown, SmoothedValueBase< SmoothedValueClass, FloatType >::currentValue, SmoothedValueBase< SmoothedValueClass, FloatType >::setCurrentAndTargetValue(), and SmoothedValueBase< SmoothedValueClass, FloatType >::target.
getNextValue()
template<typename FloatType > FloatType LogSmoothedValue< FloatType >::getNextValue () noexcept
Compute the next value.
Returns
Smoothed value
References SmoothedValueBase< SmoothedValueClass, FloatType >::countdown, SmoothedValueBase< SmoothedValueClass, FloatType >::currentValue, SmoothedValueBase< SmoothedValueClass, FloatType >::isSmoothing(), jmap(), and SmoothedValueBase< SmoothedValueClass, FloatType >::target.
skip()
template<typename FloatType > FloatType LogSmoothedValue< FloatType >::skip (int numSamples) noexcept
Skip the next numSamples samples.
This is identical to calling getNextValue numSamples times.
See also
getNextValue
References SmoothedValueBase< SmoothedValueClass, FloatType >::countdown, SmoothedValueBase< SmoothedValueClass, FloatType >::currentValue, Decibels::decibelsToGain(), jmap(), SmoothedValueBase< SmoothedValueClass, FloatType >::setCurrentAndTargetValue(), and SmoothedValueBase< SmoothedValueClass, FloatType >::target.
The documentation for this class was generated from the following file:
juce_SmoothedValues.h