JUCE: MPEZoneLayout Class Reference
MPEZoneLayout Class Reference
juce_audio_basics » mpe
This class represents the current MPE zone layout of a device capable of handling MPE.
Classes
class Listener
Listener class.
struct Zone
This struct represents an MPE zone.
Public Member Functions
MPEZoneLayout () noexcept
Default constructor.
MPEZoneLayout (const MPEZoneLayout &other)
Copy constuctor.
MPEZoneLayout & operator= (const MPEZoneLayout &other)
Copy assignment operator.
void setLowerZone (int numMemberChannels=0, int perNotePitchbendRange=48, int masterPitchbendRange=2) noexcept
Sets the lower zone of this layout.
void setUpperZone (int numMemberChannels=0, int perNotePitchbendRange=48, int masterPitchbendRange=2) noexcept
Sets the upper zone of this layout.
const Zone getLowerZone () const noexcept
Returns a struct representing the lower MPE zone.
const Zone getUpperZone () const noexcept
Returns a struct representing the upper MPE zone.
void clearAllZones ()
Clears the lower and upper zones of this layout, making them both inactive and disabling MPE mode.
void processNextMidiEvent (const MidiMessage &message)
Pass incoming MIDI messages to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
void processNextMidiBuffer (const MidiBuffer &buffer)
Pass incoming MIDI buffers to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
void addListener (Listener *const listenerToAdd) noexcept
Adds a listener.
void removeListener (Listener *const listenerToRemove) noexcept
Removes a listener.
Detailed Description
This class represents the current MPE zone layout of a device capable of handling MPE.
An MPE device can have up to two zones: a lower zone with master channel 1 and allocated MIDI channels increasing from channel 2, and an upper zone with master channel 16 and allocated MIDI channels decreasing from channel 15. MPE mode is enabled on a device when one of these zones is active and disabled when both are inactive.
Use the MPEMessages helper class to convert the zone layout represented by this object to MIDI message sequences that you can send to an Expressive MIDI device to set its zone layout, add zones etc.
See also
MPEInstrument
Constructor & Destructor Documentation
MPEZoneLayout() [1/2]
MPEZoneLayout::MPEZoneLayout () noexcept
Default constructor.
This will create a layout with inactive lower and upper zones, representing a device with MPE mode disabled.
You can set the lower or upper MPE zones using the setZone() method.
See also
setZone
MPEZoneLayout() [2/2]
MPEZoneLayout::MPEZoneLayout (const MPEZoneLayout & other)
Copy constuctor.
This will not copy the listeners registered to the MPEZoneLayout.
Member Function Documentation
operator=()
MPEZoneLayout& MPEZoneLayout::operator= (const MPEZoneLayout & other)
Copy assignment operator.
This will not copy the listeners registered to the MPEZoneLayout.
setLowerZone()
void MPEZoneLayout::setLowerZone (int numMemberChannels = 0, int perNotePitchbendRange = 48, int masterPitchbendRange = 2) noexcept
Sets the lower zone of this layout.
setUpperZone()
void MPEZoneLayout::setUpperZone (int numMemberChannels = 0, int perNotePitchbendRange = 48, int masterPitchbendRange = 2) noexcept
Sets the upper zone of this layout.
getLowerZone()
const Zone MPEZoneLayout::getLowerZone () const noexcept
Returns a struct representing the lower MPE zone.
getUpperZone()
const Zone MPEZoneLayout::getUpperZone () const noexcept
Returns a struct representing the upper MPE zone.
References clearAllZones(), processNextMidiBuffer(), and processNextMidiEvent().
clearAllZones()
void MPEZoneLayout::clearAllZones ()
Clears the lower and upper zones of this layout, making them both inactive and disabling MPE mode.
Referenced by getUpperZone().
processNextMidiEvent()
void MPEZoneLayout::processNextMidiEvent (const MidiMessage & message)
Pass incoming MIDI messages to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
MPEMessages::rpnNumber will add or remove zones; RPN 0 will set the per-note or master pitchbend ranges.
Any other MIDI messages will be ignored by this class.
See also
MPEMessages
Referenced by getUpperZone().
processNextMidiBuffer()
void MPEZoneLayout::processNextMidiBuffer (const MidiBuffer & buffer)
Pass incoming MIDI buffers to an object of this class if you want the zone layout to properly react to MPE RPN messages like an MPE device.
MPEMessages::rpnNumber will add or remove zones; RPN 0 will set the per-note or master pitchbend ranges.
Any other MIDI messages will be ignored by this class.
See also
MPEMessages
Referenced by getUpperZone().
addListener()
void MPEZoneLayout::addListener (Listener *const listenerToAdd) noexcept
Adds a listener.
removeListener()
void MPEZoneLayout::removeListener (Listener *const listenerToRemove) noexcept
Removes a listener.
The documentation for this class was generated from the following file:
juce_MPEZoneLayout.h