JUCE: PluginHostType Class Reference
PluginHostType Class Reference
juce_audio_plugin_client » utility
A useful utility class to determine the host or DAW in which your plugin is loaded.
Public Types
enum HostType {
UnknownHost, AbletonLive6, AbletonLive7, AbletonLive8,
AbletonLiveGeneric, AdobeAudition, AdobePremierePro, AppleGarageBand,
AppleLogic, AppleMainStage, Ardour, AvidProTools,
BitwigStudio, CakewalkSonar8, CakewalkSonarGeneric, DaVinciResolve,
DigitalPerformer, FinalCut, FruityLoops, JUCEPluginHost,
MagixSamplitude, MagixSequoia, MergingPyramix, MuseReceptorGeneric,
Reaper, Renoise, SADiE, SteinbergCubase4,
SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7,
SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric,
SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric,
SteinbergWavelab5, SteinbergWavelab6, SteinbergWavelab7, SteinbergWavelab8,
SteinbergWavelabGeneric, SteinbergTestHost, StudioOne, Tracktion3,
TracktionGeneric, TracktionWaveform, VBVSTScanner, WaveBurner
}
Represents the host type and also its version for some hosts.
Public Member Functions
PluginHostType ()
PluginHostType (const PluginHostType &other) noexcept
PluginHostType & operator= (const PluginHostType &other) noexcept
bool isAbletonLive () const noexcept
Returns true if the host is any version of Ableton Live.
bool isAdobeAudition () const noexcept
Returns true if the host is Adobe Audition.
bool isArdour () const noexcept
Returns true if the host is Ardour.
bool isBitwigStudio () const noexcept
Returns true if the host is Bitwig Studio.
bool isCubase () const noexcept
Returns true if the host is any version of Steinberg Cubase.
bool isCubase7orLater () const noexcept
Returns true if the host is Steinberg Cubase 7 or later.
bool isCubaseBridged () const noexcept
Returns true if the host is Steinberg Cubase 5 Bridged.
bool isDaVinciResolve () const noexcept
Returns true if the host is DaVinci Resolve.
bool isDigitalPerformer () const noexcept
Returns true if the host is Digital Performer.
bool isFinalCut () const noexcept
Returns true if the host is Apple Final Cut Pro.
bool isFruityLoops () const noexcept
Returns true if the host is Fruity Loops.
bool isGarageBand () const noexcept
Returns true if the host is Apple GarageBand.
bool isJUCEPluginHost () const noexcept
Returns true if the host is the JUCE AudioPluginHost.
bool isLogic () const noexcept
Returns true if the host is Apple Logic Pro.
bool isMainStage () const noexcept
Returns true if the host is Apple MainStage.
bool isNuendo () const noexcept
Returns true if the host is any version of Steinberg Nuendo.
bool isPremiere () const noexcept
Returns true if the host is Adobe Premiere Pro.
bool isProTools () const noexcept
Returns true if the host is Avid Pro Tools.
bool isPyramix () const noexcept
Returns true if the host is Merging Pyramix.
bool isReceptor () const noexcept
Returns true if the host is Muse Receptor.
bool isReaper () const noexcept
Returns true if the host is Cockos Reaper.
bool isRenoise () const noexcept
Returns true if the host is Renoise.
bool isSADiE () const noexcept
Returns true if the host is SADiE.
bool isSamplitude () const noexcept
Returns true if the host is Magix Samplitude.
bool isSequoia () const noexcept
Returns true if the host is Magix Sequoia.
bool isSonar () const noexcept
Returns true if the host is any version of Cakewalk Sonar.
bool isSteinbergTestHost () const noexcept
Returns true if the host is Steinberg's VST3 Test Host.
bool isSteinberg () const noexcept
Returns true if the host is any product from Steinberg.
bool isStudioOne () const noexcept
Returns true if the host is PreSonus Studio One.
bool isTracktion () const noexcept
Returns true if the host is any version of Tracktion.
bool isTracktionWaveform () const noexcept
Returns true if the host is Tracktion Waveform.
bool isVBVSTScanner () const noexcept
Returns true if the host is VB Audio VST Scanner.
bool isWaveBurner () const noexcept
Returns true if the host is Apple WaveBurner.
bool isWavelab () const noexcept
Returns true if the host is any version of Steinberg WaveLab.
bool isWavelabLegacy () const noexcept
Returns true if the host is Steinberg WaveLab 6 or below.
const char * getHostDescription () const noexcept
Returns a human-readable description of the host.
bool isInterAppAudioConnected () const
Returns true if the plugin is connected with Inter-App Audio on iOS.
void switchToHostApplication () const
Switches to the host application when Inter-App Audio is used on iOS.
Static Public Member Functions
static String getHostPath ()
Returns the complete absolute path of the host application executable.
static AudioProcessor::WrapperType getPluginLoadedAs () noexcept
Returns the plug-in format via which the plug-in file was loaded.
Public Attributes
HostType type
Detailed Description
A useful utility class to determine the host or DAW in which your plugin is loaded.
Declare a PluginHostType object in your class to use it.
{Audio}
Member Enumeration Documentation
HostType
enum PluginHostType::HostType
Represents the host type and also its version for some hosts.
Enumerator
UnknownHost
Represents an unknown host.
AbletonLive6
Represents Ableton Live 6.
AbletonLive7
Represents Ableton Live 7.
AbletonLive8
Represents Ableton Live 8.
AbletonLiveGeneric
Represents Ableton Live.
AdobeAudition
Represents Adobe Audition.
AdobePremierePro
Represents Adobe Premiere Pro.
AppleGarageBand
Represents Apple GarageBand.
AppleLogic
Represents Apple Logic Pro.
AppleMainStage
Represents Apple Main Stage.
Ardour
Represents Ardour.
AvidProTools
Represents Avid Pro Tools.
BitwigStudio
Represents Bitwig Studio.
CakewalkSonar8
Represents Cakewalk Sonar 8.
CakewalkSonarGeneric
Represents Cakewalk Sonar.
DaVinciResolve
Represents DaVinci Resolve.
DigitalPerformer
Represents Digital Performer.
FinalCut
Represents Apple Final Cut Pro.
FruityLoops
Represents Fruity Loops.
JUCEPluginHost
Represents the JUCE AudioPluginHost.
MagixSamplitude
Represents Magix Samplitude.
MagixSequoia
Represents Magix Sequoia.
MergingPyramix
Represents Merging Pyramix.
MuseReceptorGeneric
Represents Muse Receptor.
Reaper
Represents Cockos Reaper.
Renoise
Represents Renoise.
SADiE
Represents SADiE.
SteinbergCubase4
Represents Steinberg Cubase 4.
SteinbergCubase5
Represents Steinberg Cubase 5.
SteinbergCubase5Bridged
Represents Steinberg Cubase 5 Bridged.
SteinbergCubase6
Represents Steinberg Cubase 6.
SteinbergCubase7
Represents Steinberg Cubase 7.
SteinbergCubase8
Represents Steinberg Cubase 8.
SteinbergCubase8_5
Represents Steinberg Cubase 8.5.
SteinbergCubase9
Represents Steinberg Cubase 9.
SteinbergCubaseGeneric
Represents Steinberg Cubase.
SteinbergNuendo3
Represents Steinberg Nuendo 3.
SteinbergNuendo4
Represents Steinberg Nuendo 4.
SteinbergNuendo5
Represents Steinberg Nuendo 5.
SteinbergNuendoGeneric
Represents Steinberg Nuendo.
SteinbergWavelab5
Represents Steinberg Wavelab 5.
SteinbergWavelab6
Represents Steinberg Wavelab 6.
SteinbergWavelab7
Represents Steinberg Wavelab 7.
SteinbergWavelab8
Represents Steinberg Wavelab 8.
SteinbergWavelabGeneric
Represents Steinberg Wavelab.
SteinbergTestHost
Represents Steinberg's VST3 Test Host.
StudioOne
Represents PreSonus Studio One.
Tracktion3
Represents Tracktion 3.
TracktionGeneric
Represents Tracktion.
TracktionWaveform
Represents Tracktion Waveform.
VBVSTScanner
Represents VB Audio VST Scanner.
WaveBurner
Represents Apple WaveBurner.
Constructor & Destructor Documentation
PluginHostType() [1/2]
PluginHostType::PluginHostType ()
PluginHostType() [2/2]
PluginHostType::PluginHostType (const PluginHostType & other) noexcept
Member Function Documentation
operator=()
PluginHostType& PluginHostType::operator= (const PluginHostType & other) noexcept
References type.
isAbletonLive()
bool PluginHostType::isAbletonLive () const noexcept
Returns true if the host is any version of Ableton Live.
References AbletonLive6, AbletonLive7, AbletonLive8, and AbletonLiveGeneric.
isAdobeAudition()
bool PluginHostType::isAdobeAudition () const noexcept
Returns true if the host is Adobe Audition.
References AdobeAudition.
isArdour()
bool PluginHostType::isArdour () const noexcept
Returns true if the host is Ardour.
References Ardour.
isBitwigStudio()
bool PluginHostType::isBitwigStudio () const noexcept
Returns true if the host is Bitwig Studio.
References BitwigStudio.
isCubase()
bool PluginHostType::isCubase () const noexcept
Returns true if the host is any version of Steinberg Cubase.
References SteinbergCubase4, SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7, SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, and SteinbergCubaseGeneric.
Referenced by isCubase7orLater(), and isSteinberg().
isCubase7orLater()
bool PluginHostType::isCubase7orLater () const noexcept
Returns true if the host is Steinberg Cubase 7 or later.
References isCubase(), SteinbergCubase4, SteinbergCubase5, and SteinbergCubase6.
isCubaseBridged()
bool PluginHostType::isCubaseBridged () const noexcept
Returns true if the host is Steinberg Cubase 5 Bridged.
References SteinbergCubase5Bridged.
isDaVinciResolve()
bool PluginHostType::isDaVinciResolve () const noexcept
Returns true if the host is DaVinci Resolve.
References DaVinciResolve.
isDigitalPerformer()
bool PluginHostType::isDigitalPerformer () const noexcept
Returns true if the host is Digital Performer.
References DigitalPerformer.
isFinalCut()
bool PluginHostType::isFinalCut () const noexcept
Returns true if the host is Apple Final Cut Pro.
References FinalCut.
isFruityLoops()
bool PluginHostType::isFruityLoops () const noexcept
Returns true if the host is Fruity Loops.
References FruityLoops.
isGarageBand()
bool PluginHostType::isGarageBand () const noexcept
Returns true if the host is Apple GarageBand.
References AppleGarageBand.
isJUCEPluginHost()
bool PluginHostType::isJUCEPluginHost () const noexcept
Returns true if the host is the JUCE AudioPluginHost.
References JUCEPluginHost.
isLogic()
bool PluginHostType::isLogic () const noexcept
Returns true if the host is Apple Logic Pro.
References AppleLogic.
isMainStage()
bool PluginHostType::isMainStage () const noexcept
Returns true if the host is Apple MainStage.
References AppleMainStage.
isNuendo()
bool PluginHostType::isNuendo () const noexcept
Returns true if the host is any version of Steinberg Nuendo.
References SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, and SteinbergNuendoGeneric.
Referenced by isSteinberg().
isPremiere()
bool PluginHostType::isPremiere () const noexcept
Returns true if the host is Adobe Premiere Pro.
References AdobePremierePro.
isProTools()
bool PluginHostType::isProTools () const noexcept
Returns true if the host is Avid Pro Tools.
References AvidProTools.
isPyramix()
bool PluginHostType::isPyramix () const noexcept
Returns true if the host is Merging Pyramix.
References MergingPyramix.
isReceptor()
bool PluginHostType::isReceptor () const noexcept
Returns true if the host is Muse Receptor.
References MuseReceptorGeneric.
isReaper()
bool PluginHostType::isReaper () const noexcept
Returns true if the host is Cockos Reaper.
References Reaper.
isRenoise()
bool PluginHostType::isRenoise () const noexcept
Returns true if the host is Renoise.
References Renoise.
isSADiE()
bool PluginHostType::isSADiE () const noexcept
Returns true if the host is SADiE.
References SADiE.
isSamplitude()
bool PluginHostType::isSamplitude () const noexcept
Returns true if the host is Magix Samplitude.
References MagixSamplitude.
isSequoia()
bool PluginHostType::isSequoia () const noexcept
Returns true if the host is Magix Sequoia.
References MagixSequoia.
isSonar()
bool PluginHostType::isSonar () const noexcept
Returns true if the host is any version of Cakewalk Sonar.
References CakewalkSonar8, and CakewalkSonarGeneric.
isSteinbergTestHost()
bool PluginHostType::isSteinbergTestHost () const noexcept
Returns true if the host is Steinberg's VST3 Test Host.
References SteinbergTestHost.
Referenced by isSteinberg().
isSteinberg()
bool PluginHostType::isSteinberg () const noexcept
Returns true if the host is any product from Steinberg.
References isCubase(), isNuendo(), isSteinbergTestHost(), and isWavelab().
isStudioOne()
bool PluginHostType::isStudioOne () const noexcept
Returns true if the host is PreSonus Studio One.
References StudioOne.
isTracktion()
bool PluginHostType::isTracktion () const noexcept
Returns true if the host is any version of Tracktion.
References isTracktionWaveform(), Tracktion3, and TracktionGeneric.
isTracktionWaveform()
bool PluginHostType::isTracktionWaveform () const noexcept
Returns true if the host is Tracktion Waveform.
References TracktionWaveform.
Referenced by isTracktion().
isVBVSTScanner()
bool PluginHostType::isVBVSTScanner () const noexcept
Returns true if the host is VB Audio VST Scanner.
References VBVSTScanner.
isWaveBurner()
bool PluginHostType::isWaveBurner () const noexcept
Returns true if the host is Apple WaveBurner.
References WaveBurner.
isWavelab()
bool PluginHostType::isWavelab () const noexcept
Returns true if the host is any version of Steinberg WaveLab.
References isWavelabLegacy(), SteinbergWavelab7, SteinbergWavelab8, and SteinbergWavelabGeneric.
Referenced by isSteinberg().
isWavelabLegacy()
bool PluginHostType::isWavelabLegacy () const noexcept
Returns true if the host is Steinberg WaveLab 6 or below.
References SteinbergWavelab5, and SteinbergWavelab6.
Referenced by isWavelab().
getHostDescription()
const char* PluginHostType::getHostDescription () const noexcept
Returns a human-readable description of the host.
References AbletonLive6, AbletonLive7, AbletonLive8, AbletonLiveGeneric, AdobeAudition, AdobePremierePro, AppleGarageBand, AppleLogic, AppleMainStage, Ardour, AvidProTools, BitwigStudio, CakewalkSonar8, CakewalkSonarGeneric, DaVinciResolve, DigitalPerformer, FinalCut, FruityLoops, isInterAppAudioConnected(), JUCEPluginHost, MagixSamplitude, MagixSequoia, MergingPyramix, MuseReceptorGeneric, Reaper, Renoise, SADiE, SteinbergCubase4, SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7, SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric, SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric, SteinbergTestHost, SteinbergWavelab5, SteinbergWavelab6, SteinbergWavelab7, SteinbergWavelab8, SteinbergWavelabGeneric, StudioOne, switchToHostApplication(), Tracktion3, TracktionGeneric, TracktionWaveform, VBVSTScanner, and WaveBurner.
isInterAppAudioConnected()
bool PluginHostType::isInterAppAudioConnected () const
Returns true if the plugin is connected with Inter-App Audio on iOS.
Referenced by getHostDescription().
switchToHostApplication()
void PluginHostType::switchToHostApplication () const
Switches to the host application when Inter-App Audio is used on iOS.
Referenced by getHostDescription().
getHostPath()
static String PluginHostType::getHostPath () static
Returns the complete absolute path of the host application executable.
References File::getFullPathName(), File::getSpecialLocation(), and File::hostApplicationPath.
Referenced by getPluginLoadedAs().
getPluginLoadedAs()
static AudioProcessor::WrapperType PluginHostType::getPluginLoadedAs () static noexcept
Returns the plug-in format via which the plug-in file was loaded.
This value is identical to AudioProcessor::wrapperType of the main audio processor of this plug-in. This function is useful for code that does not have access to the plug-in's main audio processor.
See also
AudioProcessor::wrapperType
References AbletonLive6, AbletonLive7, AbletonLive8, AbletonLiveGeneric, AdobeAudition, AdobePremierePro, AppleGarageBand, AppleLogic, AppleMainStage, Ardour, AvidProTools, BitwigStudio, CakewalkSonar8, CakewalkSonarGeneric, DaVinciResolve, DigitalPerformer, FinalCut, FruityLoops, File::getFileName(), getHostPath(), JUCEPluginHost, MagixSamplitude, MagixSequoia, MergingPyramix, MuseReceptorGeneric, Reaper, Renoise, SADiE, SteinbergCubase4, SteinbergCubase5, SteinbergCubase5Bridged, SteinbergCubase6, SteinbergCubase7, SteinbergCubase8, SteinbergCubase8_5, SteinbergCubase9, SteinbergCubaseGeneric, SteinbergNuendo3, SteinbergNuendo4, SteinbergNuendo5, SteinbergNuendoGeneric, SteinbergTestHost, SteinbergWavelab5, SteinbergWavelab6, SteinbergWavelab7, SteinbergWavelab8, SteinbergWavelabGeneric, StudioOne, Tracktion3, TracktionGeneric, TracktionWaveform, UnknownHost, VBVSTScanner, and WaveBurner.
Referenced by StandalonePluginHolder::getInstance().
Member Data Documentation
type
HostType PluginHostType::type
Referenced by operator=().
The documentation for this class was generated from the following file:
juce_PluginHostType.h