JUCE: PhysicalTopologySource Class Reference
PhysicalTopologySource Class Reference
juce_blocks_basics » topology
This topology source manages the topology of the physical Blocks devices that are currently connected.
Classes
struct DeviceConnection
For custom transport systems, this represents a connected device.
struct DeviceDetector
For custom transport systems, this represents a connected device.
Public Member Functions
PhysicalTopologySource (bool startDetached=false)
Constructor.
~PhysicalTopologySource () override
Destructor.
BlockTopology getCurrentTopology () const override
Returns the current physical topology.
void cancelAllActiveTouches () noexcept override
Reset all touches.
void setActive (bool shouldBeActive) override
Sets the TopologySource as active, occupying the midi port and trying to connect to the block devices.
bool isActive () const override
Returns true, if the TopologySource is currently trying to connect the block devices.
bool isLockedFromOutside () const
This method will tell, if an other PhysicalTopologySource has locked the Midi connection.
PhysicalTopologySource (DeviceDetector &detectorToUse, bool startDetached=false)
Constructor for custom transport systems.
Public Member Functions inherited from TopologySource
virtual ~TopologySource ()=default
Destructor.
void addListener (Listener *l)
void removeListener (Listener *l)
Static Public Member Functions
static const char *const * getStandardLittleFootFunctions () noexcept
Protected Member Functions
virtual bool hasOwnServiceTimer () const
virtual void handleTimerTick ()
Additional Inherited Members
Protected Attributes inherited from TopologySource
ListenerList< Listener > listeners
Detailed Description
This topology source manages the topology of the physical Blocks devices that are currently connected.
It maintains a list of them and tells listeners when physical devices are added or removed.
Constructor & Destructor Documentation
PhysicalTopologySource() [1/2]
PhysicalTopologySource::PhysicalTopologySource (bool startDetached = false)
Constructor.
Referenced by PhysicalTopologySource::DeviceDetector::isLockedFromOutside().
~PhysicalTopologySource()
PhysicalTopologySource::~PhysicalTopologySource () override
Destructor.
PhysicalTopologySource() [2/2]
PhysicalTopologySource::PhysicalTopologySource (DeviceDetector & detectorToUse, bool startDetached = false)
Constructor for custom transport systems.
Member Function Documentation
getCurrentTopology()
BlockTopology PhysicalTopologySource::getCurrentTopology () const override virtual
Returns the current physical topology.
Implements TopologySource.
cancelAllActiveTouches()
void PhysicalTopologySource::cancelAllActiveTouches () override virtual noexcept
Reset all touches.
Reimplemented from TopologySource.
setActive()
void PhysicalTopologySource::setActive (bool shouldBeActive) override virtual
Sets the TopologySource as active, occupying the midi port and trying to connect to the block devices.
Implements TopologySource.
isActive()
bool PhysicalTopologySource::isActive () const override virtual
Returns true, if the TopologySource is currently trying to connect the block devices.
Implements TopologySource.
isLockedFromOutside()
bool PhysicalTopologySource::isLockedFromOutside () const
This method will tell, if an other PhysicalTopologySource has locked the Midi connection.
getStandardLittleFootFunctions()
static const char* const* PhysicalTopologySource::getStandardLittleFootFunctions () static noexcept
Referenced by PhysicalTopologySource::DeviceDetector::isLockedFromOutside().
hasOwnServiceTimer()
virtual bool PhysicalTopologySource::hasOwnServiceTimer () const protected virtual
Referenced by PhysicalTopologySource::DeviceDetector::isLockedFromOutside().
handleTimerTick()
virtual void PhysicalTopologySource::handleTimerTick () protected virtual
Referenced by PhysicalTopologySource::DeviceDetector::isLockedFromOutside().
The documentation for this class was generated from the following file:
juce_PhysicalTopologySource.h