JUCE: StateVariableFilter::Filter< SampleType > Class Template Reference
StateVariableFilter::Filter< SampleType > Class Template Reference
Public Types
using NumericType = typename SampleTypeHelpers::ElementType< SampleType >::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Public Member Functions
Filter ()
Creates a filter with default parameters.
Filter (Parameters< NumericType > *paramtersToUse)
Filter (const Filter &)=default
Creates a copy of another filter.
Filter (Filter &&)=default
Move constructor.
void prepare (const ProcessSpec &) noexcept
Initialization of the filter.
void reset () noexcept
Resets the filter's processing pipeline.
template<typename ProcessContext >
void process (const ProcessContext &context) noexcept
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType sample) noexcept
Processes a single sample, without any locking or checking.
Public Attributes
Parameters< NumericType >::Ptr parameters
The parameters of the state variable filter.
Member Typedef Documentation
template<typename SampleType > using StateVariableFilter::Filter< SampleType >::NumericType = typename SampleTypeHelpers::ElementType<SampleType>::Type
The NumericType is the underlying primitive type used by the SampleType (which could be either a primitive or vector)
Constructor & Destructor Documentation
template<typename SampleType > StateVariableFilter::Filter< SampleType >::Filter ()
Creates a filter with default parameters.
References StateVariableFilter::Filter< SampleType >::reset().
template<typename SampleType > StateVariableFilter::Filter< SampleType >::Filter (Parameters< NumericType > * paramtersToUse)
References StateVariableFilter::Filter< SampleType >::reset().
template<typename SampleType > StateVariableFilter::Filter< SampleType >::Filter (const Filter< SampleType > &) default
Creates a copy of another filter.
template<typename SampleType > StateVariableFilter::Filter< SampleType >::Filter (Filter< SampleType > &&) default
Move constructor.
Member Function Documentation
template<typename SampleType > void StateVariableFilter::Filter< SampleType >::prepare (const ProcessSpec &) noexcept
Initialization of the filter.
References StateVariableFilter::Filter< SampleType >::reset().
template<typename SampleType > void StateVariableFilter::Filter< SampleType >::reset () noexcept
Resets the filter's processing pipeline.
Referenced by StateVariableFilter::Filter< SampleType >::Filter(), and StateVariableFilter::Filter< SampleType >::prepare().
template<typename SampleType > template<typename ProcessContext > void StateVariableFilter::Filter< SampleType >::process (const ProcessContext & context) noexcept
References jassert, jassertfalse, and StateVariableFilter::Filter< SampleType >::parameters.
template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE StateVariableFilter::Filter< SampleType >::processSample (SampleType sample) noexcept
Processes a single sample, without any locking or checking.
Use this if you need processing of a single value.
References jassertfalse, and StateVariableFilter::Filter< SampleType >::parameters.
Member Data Documentation
template<typename SampleType > Parameters<NumericType>::Ptr StateVariableFilter::Filter< SampleType >::parameters
The parameters of the state variable filter.
It's up to the called to ensure that these parameters are modified in a thread-safe way.
Referenced by StateVariableFilter::Filter< SampleType >::process(), and StateVariableFilter::Filter< SampleType >::processSample().
The documentation for this class was generated from the following file:
juce_StateVariableFilter.h