JUCE: ValueTree::Listener Class Reference
ValueTree::Listener Class Reference abstract
juce_data_structures » values
Listener class for events that happen to a ValueTree.
Public Member Functions
virtual ~Listener ()=default
Destructor.
virtual void valueTreePropertyChanged (ValueTree &treeWhosePropertyHasChanged, const Identifier &property)=0
This method is called when a property of this tree (or of one of its sub-trees) is changed.
virtual void valueTreeChildAdded (ValueTree &parentTree, ValueTree &childWhichHasBeenAdded)=0
This method is called when a child sub-tree is added.
virtual void valueTreeChildRemoved (ValueTree &parentTree, ValueTree &childWhichHasBeenRemoved, int indexFromWhichChildWasRemoved)=0
This method is called when a child sub-tree is removed.
virtual void valueTreeChildOrderChanged (ValueTree &parentTreeWhoseChildrenHaveMoved, int oldIndex, int newIndex)=0
This method is called when a tree's children have been re-shuffled.
virtual void valueTreeParentChanged (ValueTree &treeWhoseParentHasChanged)=0
This method is called when a tree has been added or removed from a parent.
virtual void valueTreeRedirected (ValueTree &treeWhichHasBeenChanged)
This method is called when a tree is made to point to a different internal shared object.
Detailed Description
Listener class for events that happen to a ValueTree.
To get events from a ValueTree, make your class implement this interface, and use ValueTree::addListener() and ValueTree::removeListener() to register it.
Constructor & Destructor Documentation
~Listener()
virtual ValueTree::Listener::~Listener () virtual default
Destructor.
Member Function Documentation
valueTreePropertyChanged()
virtual void ValueTree::Listener::valueTreePropertyChanged (ValueTree & treeWhosePropertyHasChanged, const Identifier & property) pure virtual
This method is called when a property of this tree (or of one of its sub-trees) is changed.
Note that when you register a listener to a tree, it will receive this callback for property changes in that tree, and also for any of its children, (recursively, at any depth). If your tree has sub-trees but you only want to know about changes to the top level tree, simply check the tree parameter in this callback to make sure it's the tree you're interested in.
Referenced by ValueTreeSynchroniser::getRoot().
valueTreeChildAdded()
virtual void ValueTree::Listener::valueTreeChildAdded (ValueTree & parentTree, ValueTree & childWhichHasBeenAdded) pure virtual
This method is called when a child sub-tree is added.
Note that when you register a listener to a tree, it will receive this callback for child changes in both that tree and any of its children, (recursively, at any depth). If your tree has sub-trees but you only want to know about changes to the top level tree, just check the parentTree parameter to make sure it's the one that you're interested in.
Referenced by ValueTreeSynchroniser::getRoot().
valueTreeChildRemoved()
virtual void ValueTree::Listener::valueTreeChildRemoved (ValueTree & parentTree, ValueTree & childWhichHasBeenRemoved, int indexFromWhichChildWasRemoved) pure virtual
This method is called when a child sub-tree is removed.
Note that when you register a listener to a tree, it will receive this callback for child changes in both that tree and any of its children, (recursively, at any depth). If your tree has sub-trees but you only want to know about changes to the top level tree, just check the parentTree parameter to make sure it's the one that you're interested in.
Referenced by ValueTreeSynchroniser::getRoot().
valueTreeChildOrderChanged()
virtual void ValueTree::Listener::valueTreeChildOrderChanged (ValueTree & parentTreeWhoseChildrenHaveMoved, int oldIndex, int newIndex) pure virtual
This method is called when a tree's children have been re-shuffled.
Note that when you register a listener to a tree, it will receive this callback for child changes in both that tree and any of its children, (recursively, at any depth). If your tree has sub-trees but you only want to know about changes to the top level tree, just check the parameter to make sure it's the tree that you're interested in.
Referenced by ValueTreeSynchroniser::getRoot().
valueTreeParentChanged()
virtual void ValueTree::Listener::valueTreeParentChanged (ValueTree & treeWhoseParentHasChanged) pure virtual
This method is called when a tree has been added or removed from a parent.
This callback happens when the tree to which the listener was registered is added or removed from a parent. Unlike the other callbacks, it applies only to the tree to which the listener is registered, and not to any of its children.
Referenced by ValueTreeSynchroniser::getRoot().
valueTreeRedirected()
virtual void ValueTree::Listener::valueTreeRedirected (ValueTree & treeWhichHasBeenChanged) virtual
This method is called when a tree is made to point to a different internal shared object.
When operator= is used to make a ValueTree refer to a different object, this callback will be made.
The documentation for this class was generated from the following file:
juce_ValueTree.h