JUCE: Block Class Reference
Block Class Reference abstract
juce_blocks_basics » blocks
Represents an individual BLOCKS device.
Inherits ReferenceCountedObject.
Classes
struct BlockArea
A simple struct representing the area of a block.
struct ConfigMetaData
Metadata for a given config item.
struct ConnectionPort
These are the edge-connectors that a device may have.
struct DataInputPortListener
Interface for objects listening to input data port.
struct Program
A program that can be loaded onto a block.
struct ProgramEventListener
Interface for objects listening to custom program events.
struct ProgramEventMessage
A message that can be sent to the currently loaded program.
Public Types
enum Type {
unknown = 0, lightPadBlock, liveBlock, loopBlock,
developerControlBlock, touchBlock, seaboardBlock
}
The different block types.
using Ptr = juce::ReferenceCountedObjectPtr< Block >
The Block class is reference-counted, so always use a Block::Ptr when you are keeping references to them.
using Array = juce::ReferenceCountedArray< Block >
The Block class is reference-counted, so Block::Array is useful when you are storing lists of them.
using UID = uint64
This type is used for the unique block identifier.
using Timestamp = uint32
This type is used for timestamping events.
Public Member Functions
~Block () override
Destructor.
bool operator== (const Block &other) const noexcept
Two blocks are considered equal if they have the same UID.
bool operator!= (const Block &other) const noexcept
Two blocks are considered equal if they have the same UID.
virtual Type getType () const =0
Returns the type of this device.
bool isControlBlock () const
Returns true if this a control block.
virtual juce::String getDeviceDescription () const =0
Returns a human-readable description of this device type.
virtual float getBatteryLevel () const =0
Returns the battery level in the range 0.0 to 1.0.
virtual bool isBatteryCharging () const =0
Returns true if the battery is charging.
virtual bool isConnected () const =0
Returns true if this block is connected and active.
virtual bool isMasterBlock () const =0
Returns true if this block is directly connected to the application, as opposed to only being connected to a different block via a connection port.
virtual UID getConnectedMasterUID () const =0
Returns the UID of the master block this block is connected to.
virtual int getWidth () const =0
Returns the width of the device in logical device units.
virtual int getHeight () const =0
Returns the height of the device in logical device units.
virtual bool isHardwareBlock () const =0
Returns true if the device is a physical hardware block (i.e.
virtual float getMillimetersPerUnit () const =0
Returns the length of one logical device unit as physical millimeters.
virtual BlockArea getBlockAreaWithinLayout () const =0
Returns the area that this block covers within the layout of the group as a whole.
virtual int getRotation () const =0
Returns the rotation of this block relative to the master block in 90 degree steps clockwise.
virtual LEDGrid * getLEDGrid () const =0
If this block has a grid of LEDs, this will return an object to control it.
virtual LEDRow * getLEDRow ()=0
If this block has a row of LEDs, this will return an object to control it.
virtual juce::Array< StatusLight * > getStatusLights () const =0
If this block has any status LEDs, this will return an array of objects to control them.
virtual TouchSurface * getTouchSurface () const =0
If this block has a pressure-sensitive surface, this will return an object to access its data.
virtual juce::Array< ControlButton * > getButtons () const =0
If this block has any control buttons, this will return an array of objects to control them.
virtual bool supportsGraphics () const =0
This returns true if the block supports generating graphics by drawing into a JUCE Graphics context.
virtual juce::Array< ConnectionPort > getPorts () const =0
Returns a list of the connectors that this device has.
virtual juce::Result setProgram (Program *)=0
Sets the Program to run on this block.
virtual Program * getProgram () const =0
Returns a pointer to the currently loaded program.
virtual void sendProgramEvent (const ProgramEventMessage &)=0
Sends a message to the currently loaded program.
virtual void addProgramEventListener (ProgramEventListener *)
Adds a new listener for custom program events from the block.
virtual void removeProgramEventListener (ProgramEventListener *)
Removes a listener for custom program events from the block.
virtual uint32 getMemorySize ()=0
Returns the overall memory of the block.
virtual uint32 getHeapMemorySize ()=0
Returns the size of the data block that setDataByte and other functions can write to.
virtual void setDataByte (size_t offset, uint8 value)=0
Sets a single byte on the littlefoot heap.
virtual void setDataBytes (size_t offset, const void *data, size_t num)=0
Sets multiple bytes on the littlefoot heap.
virtual void setDataBits (uint32 startBit, uint32 numBits, uint32 value)=0
Sets multiple bits on the littlefoot heap.
virtual uint8 getDataByte (size_t offset)=0
Gets a byte from the littlefoot heap.
virtual void saveProgramAsDefault ()=0
Sets the current program as the block's default state.
virtual uint32 getMaxConfigIndex ()=0
Returns the maximum number of config items available.
virtual bool isValidUserConfigIndex (uint32 item)=0
Determine if this is a valid config item index.
virtual int32 getLocalConfigValue (uint32 item)=0
Get local config item value.
virtual void setLocalConfigValue (uint32 item, int32 value)=0
Set local config item value.
virtual void setLocalConfigRange (uint32 item, int32 min, int32 max)=0
Set local config item range.
virtual void setLocalConfigItemActive (uint32 item, bool isActive)=0
Set if config item is active or not.
virtual bool isLocalConfigItemActive (uint32 item)=0
Determine if config item is active or not.
virtual ConfigMetaData getLocalConfigMetaData (uint32 item)=0
Get config item metadata.
virtual void requestFactoryConfigSync ()=0
Request sync of factory config with block.
virtual void resetConfigListActiveStatus ()=0
Reset all items active status.
virtual void factoryReset ()=0
Perform factory reset on Block.
virtual void blockReset ()=0
Reset this Block.
virtual bool setName (const juce::String &name)=0
Set Block name.
virtual void setLogger (std::function< void(const String &)> loggingCallback)=0
Allows the user to provide a function that will receive log messages from the block.
virtual bool sendFirmwareUpdatePacket (const uint8 *data, uint8 size, std::function< void(uint8, uint32)> packetAckCallback)=0
Sends a firmware update packet to a block, and waits for a reply.
virtual void setConfigChangedCallback (std::function< void(Block &, const ConfigMetaData &, uint32)>)=0
Provides a callback that will be called when a config changes.
virtual void setProgramLoadedCallback (std::function< void(Block &)> programLoaded)=0
Provides a callback that will be called when a prgoram has been loaded.
virtual void addDataInputPortListener (DataInputPortListener *)
Adds a new listener for the data input port.
virtual void removeDataInputPortListener (DataInputPortListener *)
Removes a listener for the data input port.
virtual void sendMessage (const void *messageData, size_t messageSize)=0
Sends a message to the block.
Static Public Member Functions
static bool isControlBlock (Block::Type)
Returns true if Block::Type is a control block.
Public Attributes
const juce::String serialNumber
The Block's serial number.
juce::String versionNumber
The Block's version number.
juce::String name
The Block's name.
const UID uid
This Block's UID.
Protected Member Functions
Block (const juce::String &serialNumberToUse)
Block (const juce::String &serial, const juce::String &version, const juce::String &name)
Protected Attributes
juce::ListenerList< DataInputPortListener > dataInputPortListeners
juce::ListenerList< ProgramEventListener > programEventListeners
Detailed Description
Represents an individual BLOCKS device.
Member Typedef Documentation
Ptr
using Block::Ptr = juce::ReferenceCountedObjectPtr<Block>
The Block class is reference-counted, so always use a Block::Ptr when you are keeping references to them.
Array
using Block::Array = juce::ReferenceCountedArray<Block>
The Block class is reference-counted, so Block::Array is useful when you are storing lists of them.
UID
using Block::UID = uint64
This type is used for the unique block identifier.
Timestamp
using Block::Timestamp = uint32
This type is used for timestamping events.
It represents a number of milliseconds since the block device was booted.
Member Enumeration Documentation
Type
enum Block::Type
The different block types.
See also
Block::getType()
Enumerator
unknown
Unknown block type.
lightPadBlock
Lightpad block type.
liveBlock
Live control block type.
loopBlock
Loop control block type.
developerControlBlock
Developer control block type.
touchBlock
Touch control block type.
seaboardBlock
Seaboard block type.
Constructor & Destructor Documentation
~Block()
Block::~Block () override
Destructor.
Block() [1/2]
Block::Block (const juce::String & serialNumberToUse) protected
Block() [2/2]
Block::Block (const juce::String & serial, const juce::String & version, const juce::String & name) protected
Member Function Documentation
operator==()
bool Block::operator== (const Block & other) const noexcept
Two blocks are considered equal if they have the same UID.
operator!=()
bool Block::operator!= (const Block & other) const noexcept
Two blocks are considered equal if they have the same UID.
References getBatteryLevel(), getConnectedMasterUID(), getDeviceDescription(), getHeight(), getMillimetersPerUnit(), getType(), getWidth(), isBatteryCharging(), isConnected(), isControlBlock(), isHardwareBlock(), and isMasterBlock().
getType()
virtual Type Block::getType () const pure virtual
Returns the type of this device.
See also
Block::Type
Referenced by operator!=().
isControlBlock() [1/2]
bool Block::isControlBlock () const
Returns true if this a control block.
Referenced by operator!=().
isControlBlock() [2/2]
static bool Block::isControlBlock (Block::Type) static
Returns true if Block::Type is a control block.
getDeviceDescription()
virtual juce::String Block::getDeviceDescription () const pure virtual
Returns a human-readable description of this device type.
Referenced by operator!=().
getBatteryLevel()
virtual float Block::getBatteryLevel () const pure virtual
Returns the battery level in the range 0.0 to 1.0.
Referenced by operator!=().
isBatteryCharging()
virtual bool Block::isBatteryCharging () const pure virtual
Returns true if the battery is charging.
Referenced by operator!=().
isConnected()
virtual bool Block::isConnected () const pure virtual
Returns true if this block is connected and active.
Referenced by operator!=().
isMasterBlock()
virtual bool Block::isMasterBlock () const pure virtual
Returns true if this block is directly connected to the application, as opposed to only being connected to a different block via a connection port.
See also
ConnectionPort
Referenced by operator!=().
getConnectedMasterUID()
virtual UID Block::getConnectedMasterUID () const pure virtual
Returns the UID of the master block this block is connected to.
Referenced by operator!=().
getWidth()
virtual int Block::getWidth () const pure virtual
Returns the width of the device in logical device units.
Referenced by operator!=().
getHeight()
virtual int Block::getHeight () const pure virtual
Returns the height of the device in logical device units.
Referenced by operator!=().
isHardwareBlock()
virtual bool Block::isHardwareBlock () const pure virtual
Returns true if the device is a physical hardware block (i.e.
not a virtual block).
Referenced by operator!=().
getMillimetersPerUnit()
virtual float Block::getMillimetersPerUnit () const pure virtual
Returns the length of one logical device unit as physical millimeters.
Referenced by operator!=().
getBlockAreaWithinLayout()
virtual BlockArea Block::getBlockAreaWithinLayout () const pure virtual
Returns the area that this block covers within the layout of the group as a whole.
The coordinates are in logical block units, and are relative to the origin, which is the master block's top-left corner.
getRotation()
virtual int Block::getRotation () const pure virtual
Returns the rotation of this block relative to the master block in 90 degree steps clockwise.
getLEDGrid()
virtual LEDGrid* Block::getLEDGrid () const pure virtual
If this block has a grid of LEDs, this will return an object to control it.
Note that the pointer that is returned belongs to this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If there are no LEDs, then this method will return nullptr.
getLEDRow()
virtual LEDRow* Block::getLEDRow () pure virtual
If this block has a row of LEDs, this will return an object to control it.
Note that the pointer that is returned belongs to this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If there are no LEDs, then this method will return nullptr.
getStatusLights()
virtual juce::Array<StatusLight*> Block::getStatusLights () const pure virtual
If this block has any status LEDs, this will return an array of objects to control them.
Note that the objects in the array belong to this Block object, and the caller must neither delete them or use them after the lifetime of this Block object has finished.
getTouchSurface()
virtual TouchSurface* Block::getTouchSurface () const pure virtual
If this block has a pressure-sensitive surface, this will return an object to access its data.
Note that the pointer returned does is owned by this object, and the caller must neither delete it or use it after the lifetime of this Block object has finished. If the device is not touch-sensitive, then this method will return nullptr.
getButtons()
virtual juce::Array<ControlButton*> Block::getButtons () const pure virtual
If this block has any control buttons, this will return an array of objects to control them.
Note that the objects in the array belong to this Block object, and the caller must neither delete them or use them after the lifetime of this Block object has finished.
supportsGraphics()
virtual bool Block::supportsGraphics () const pure virtual
This returns true if the block supports generating graphics by drawing into a JUCE Graphics context.
This should only be true for virtual on-screen blocks; hardware blocks will instead use the LED Grid for visuals.
getPorts()
virtual juce::Array<ConnectionPort> Block::getPorts () const pure virtual
Returns a list of the connectors that this device has.
setProgram()
virtual juce::Result Block::setProgram (Program *) pure virtual
Sets the Program to run on this block.
The supplied Program's lifetime will be managed by this class, so do not use the Program in other places in your code.
getProgram()
virtual Program* Block::getProgram () const pure virtual
Returns a pointer to the currently loaded program.
sendProgramEvent()
virtual void Block::sendProgramEvent (const ProgramEventMessage &) pure virtual
Sends a message to the currently loaded program.
To receive the message the program must provide a littlefoot function called handleMessage with the following form:
void handleMessage (int param1, int param2, int param3)
{
    // Do something with the two integer parameters that the app has sent...
}
addProgramEventListener()
virtual void Block::addProgramEventListener (ProgramEventListener *) virtual
Adds a new listener for custom program events from the block.
removeProgramEventListener()
virtual void Block::removeProgramEventListener (ProgramEventListener *) virtual
Removes a listener for custom program events from the block.
getMemorySize()
virtual uint32 Block::getMemorySize () pure virtual
Returns the overall memory of the block.
getHeapMemorySize()
virtual uint32 Block::getHeapMemorySize () pure virtual
Returns the size of the data block that setDataByte and other functions can write to.
setDataByte()
virtual void Block::setDataByte (size_t offset, uint8 value) pure virtual
Sets a single byte on the littlefoot heap.
setDataBytes()
virtual void Block::setDataBytes (size_t offset, const void * data, size_t num) pure virtual
Sets multiple bytes on the littlefoot heap.
setDataBits()
virtual void Block::setDataBits (uint32 startBit, uint32 numBits, uint32 value) pure virtual
Sets multiple bits on the littlefoot heap.
getDataByte()
virtual uint8 Block::getDataByte (size_t offset) pure virtual
Gets a byte from the littlefoot heap.
saveProgramAsDefault()
virtual void Block::saveProgramAsDefault () pure virtual
Sets the current program as the block's default state.
getMaxConfigIndex()
virtual uint32 Block::getMaxConfigIndex () pure virtual
Returns the maximum number of config items available.
isValidUserConfigIndex()
virtual bool Block::isValidUserConfigIndex (uint32 item) pure virtual
Determine if this is a valid config item index.
getLocalConfigValue()
virtual int32 Block::getLocalConfigValue (uint32 item) pure virtual
Get local config item value.
setLocalConfigValue()
virtual void Block::setLocalConfigValue (uint32 item, int32 value) pure virtual
Set local config item value.
setLocalConfigRange()
virtual void Block::setLocalConfigRange (uint32 item, int32 min, int32 max) pure virtual
Set local config item range.
setLocalConfigItemActive()
virtual void Block::setLocalConfigItemActive (uint32 item, bool isActive) pure virtual
Set if config item is active or not.
isLocalConfigItemActive()
virtual bool Block::isLocalConfigItemActive (uint32 item) pure virtual
Determine if config item is active or not.
getLocalConfigMetaData()
virtual ConfigMetaData Block::getLocalConfigMetaData (uint32 item) pure virtual
Get config item metadata.
requestFactoryConfigSync()
virtual void Block::requestFactoryConfigSync () pure virtual
Request sync of factory config with block.
resetConfigListActiveStatus()
virtual void Block::resetConfigListActiveStatus () pure virtual
Reset all items active status.
factoryReset()
virtual void Block::factoryReset () pure virtual
Perform factory reset on Block.
blockReset()
virtual void Block::blockReset () pure virtual
Reset this Block.
setName()
virtual bool Block::setName (const juce::String & name) pure virtual
Set Block name.
setLogger()
virtual void Block::setLogger (std::function< void(const String &)> loggingCallback) pure virtual
Allows the user to provide a function that will receive log messages from the block.
sendFirmwareUpdatePacket()
virtual bool Block::sendFirmwareUpdatePacket (const uint8 * data, uint8 size, std::function< void(uint8, uint32)> packetAckCallback) pure virtual
Sends a firmware update packet to a block, and waits for a reply.
Returns an error code.
setConfigChangedCallback()
virtual void Block::setConfigChangedCallback (std::function< void(Block &, const ConfigMetaData &, uint32)>) pure virtual
Provides a callback that will be called when a config changes.
setProgramLoadedCallback()
virtual void Block::setProgramLoadedCallback (std::function< void(Block &)> programLoaded) pure virtual
Provides a callback that will be called when a prgoram has been loaded.
addDataInputPortListener()
virtual void Block::addDataInputPortListener (DataInputPortListener *) virtual
Adds a new listener for the data input port.
removeDataInputPortListener()
virtual void Block::removeDataInputPortListener (DataInputPortListener *) virtual
Removes a listener for the data input port.
sendMessage()
virtual void Block::sendMessage (const void * messageData, size_t messageSize) pure virtual
Sends a message to the block.
Member Data Documentation
serialNumber
const juce::String Block::serialNumber
The Block's serial number.
versionNumber
juce::String Block::versionNumber
The Block's version number.
name
juce::String Block::name
The Block's name.
uid
const UID Block::uid
This Block's UID.
This will be globally unique, and remains constant for a particular device.
dataInputPortListeners
juce::ListenerList<DataInputPortListener> Block::dataInputPortListeners protected
programEventListeners
juce::ListenerList<ProgramEventListener> Block::programEventListeners protected
The documentation for this class was generated from the following file:
juce_Block.h