JUCE: Reverb Class Reference
Reverb Class Reference
juce_audio_basics » utilities
Performs a simple reverb effect on a stream of audio data.
Classes
struct Parameters
Holds the parameters being used by a Reverb object.
Public Member Functions
Reverb ()
const Parameters & getParameters () const noexcept
Returns the reverb's current parameters.
void setParameters (const Parameters &newParams)
Applies a new set of parameters to the reverb.
void setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
void reset ()
Clears the reverb's buffers.
void processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
void processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
Detailed Description
Performs a simple reverb effect on a stream of audio data.
This is a simple stereo reverb, based on the technique and tunings used in FreeVerb. Use setSampleRate() to prepare it, and then call processStereo() or processMono() to apply the reverb to your audio data.
See also
ReverbAudioSource
Constructor & Destructor Documentation
Reverb()
Reverb::Reverb ()
References setParameters(), and setSampleRate().
Member Function Documentation
getParameters()
const Parameters& Reverb::getParameters () const noexcept
Returns the reverb's current parameters.
setParameters()
void Reverb::setParameters (const Parameters & newParams)
Applies a new set of parameters to the reverb.
Note that this doesn't attempt to lock the reverb, so if you call this in parallel with the process method, you may get artifacts.
References Reverb::Parameters::dryLevel, Reverb::Parameters::freezeMode, Reverb::Parameters::wetLevel, and Reverb::Parameters::width.
Referenced by Reverb().
setSampleRate()
void Reverb::setSampleRate (const double sampleRate)
Sets the sample rate that will be used for the reverb.
You must call this before the process methods, in order to tell it the correct sample rate.
References Reverb::Parameters::damping, int(), and jassert.
Referenced by Reverb().
reset()
void Reverb::reset ()
Clears the reverb's buffers.
processStereo()
void Reverb::processStereo (float *const left, float *const right, const int numSamples) noexcept
Applies the reverb to two stereo channels of audio data.
References Reverb::Parameters::damping, and jassert.
processMono()
void Reverb::processMono (float *const samples, const int numSamples) noexcept
Applies the reverb to a single mono channel of audio data.
References Reverb::Parameters::damping, Reverb::Parameters::freezeMode, jassert, JUCE_DECLARE_NON_COPYABLE, JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, and JUCE_UNDENORMALISE.
The documentation for this class was generated from the following file:
juce_audio_basics/utilities/juce_Reverb.h