JUCE: AudioParameterInt Class Reference
AudioParameterInt Class Reference
juce_audio_processors » utilities
Provides a class of AudioProcessorParameter that can be used as an integer value with a given range.
Public Member Functions
AudioParameterInt (const String &parameterID, const String &name, int minValue, int maxValue, int defaultValue, const String &label=String(), std::function< String(int value, int maximumStringLength)> stringFromInt=nullptr, std::function< int(const String &text)> intFromString=nullptr)
Creates a AudioParameterInt with the specified parameters.
~AudioParameterInt ()
Destructor.
int get () const noexcept
Returns the parameter's current value as an integer.
operator int () const noexcept
Returns the parameter's current value as an integer.
AudioParameterInt & operator= (int newValue)
Changes the parameter's current value to a new integer.
Range< int > getRange () const noexcept
Returns the parameter's range.
const NormalisableRange< float > & getNormalisableRange () const override
Returns the range of values that the parameter can take.
Public Member Functions inherited from RangedAudioParameter
RangedAudioParameter (const String &parameterID, const String &name, const String &label={}, Category category=AudioProcessorParameter::genericParameter)
The creation of this object requires providing a name and ID which will be constant for its lifetime.
int getNumSteps () const override
Returns the number of steps for this parameter based on the normalisable range's interval.
float convertTo0to1 (float v) const noexcept
Normalises and snaps a value based on the normalisable range.
float convertFrom0to1 (float v) const noexcept
Denormalises and snaps a value based on the normalisable range.
Public Member Functions inherited from AudioProcessorParameterWithID
AudioProcessorParameterWithID (const String &parameterID, const String &name, const String &label=String(), Category category=AudioProcessorParameter::genericParameter)
The creation of this object requires providing a name and ID which will be constant for its lifetime.
~AudioProcessorParameterWithID ()
Destructor.
Public Member Functions inherited from AudioProcessorParameter
AudioProcessorParameter () noexcept
virtual ~AudioProcessorParameter ()
Destructor.
void setValueNotifyingHost (float newValue)
A processor should call this when it needs to change one of its parameters.
void beginChangeGesture ()
Sends a signal to the host to tell it that the user is about to start changing this parameter.
void endChangeGesture ()
Tells the host that the user has finished changing this parameter.
virtual bool isDiscrete () const
Returns whether the parameter uses discrete values, based on the result of getNumSteps, or allows the host to select values continuously.
virtual bool isBoolean () const
Returns whether the parameter represents a boolean switch, typically with "On" and "Off" states.
virtual bool isOrientationInverted () const
This can be overridden to tell the host that this parameter operates in the reverse direction.
virtual bool isAutomatable () const
Returns true if the host can automate this parameter.
virtual bool isMetaParameter () const
Should return true if this parameter is a "meta" parameter.
int getParameterIndex () const noexcept
Returns the index of this parameter in its parent processor's parameter list.
virtual String getCurrentValueAsText () const
Returns the current value of the parameter as a String.
virtual StringArray getAllValueStrings () const
Returns the set of strings which represent the possible states a parameter can be in.
void addListener (Listener *newListener)
Registers a listener to receive events when the parameter's state changes.
void removeListener (Listener *listener)
Removes a previously registered parameter listener.
void sendValueChangedMessageToListeners (float newValue)
Protected Member Functions
virtual void valueChanged (int newValue)
Override this method if you are interested in receiving callbacks when the parameter value changes.
Additional Inherited Members
Public Types inherited from AudioProcessorParameter
enum Category {
genericParameter = (0 << 16) | 0, inputGain = (1 << 16) | 0, outputGain = (1 << 16) | 1, inputMeter = (2 << 16) | 0,
outputMeter = (2 << 16) | 1, compressorLimiterGainReductionMeter = (2 << 16) | 2, expanderGateGainReductionMeter = (2 << 16) | 3, analysisMeter = (2 << 16) | 4,
otherMeter = (2 << 16) | 5
}
Public Attributes inherited from AudioProcessorParameterWithID
const String paramID
Provides access to the parameter's ID string.
const String name
Provides access to the parameter's name.
const String label
Provides access to the parameter's label.
const Category category
Provides access to the parameter's category.
Detailed Description
Provides a class of AudioProcessorParameter that can be used as an integer value with a given range.
See also
AudioParameterFloat, AudioParameterBool, AudioParameterChoice
Constructor & Destructor Documentation
AudioParameterInt()
AudioParameterInt::AudioParameterInt (const String & parameterID, const String & name, int minValue, int maxValue, int defaultValue, const String & label = String(), std::function< String(int value, int maximumStringLength)> stringFromInt = nullptr, std::function< int(const String &text)> intFromString = nullptr)
Creates a AudioParameterInt with the specified parameters.
Parameters
parameterID The parameter ID to use
name The parameter name to use
minValue The minimum parameter value
maxValue The maximum parameter value
defaultValue The default value
label An optional label for the parameter's value
stringFromInt An optional lambda function that converts a int value to a string with a maximum length. This may be used by hosts to display the parameter's value.
intFromString An optional lambda function that parses a string and converts it into an int. Some hosts use this to allow users to type in parameter values.
~AudioParameterInt()
AudioParameterInt::~AudioParameterInt ()
Destructor.
Member Function Documentation
get()
int AudioParameterInt::get () const noexcept
Returns the parameter's current value as an integer.
References roundToInt().
operator int()
AudioParameterInt::operator int () const noexcept
Returns the parameter's current value as an integer.
operator=()
AudioParameterInt& AudioParameterInt::operator= (int newValue)
Changes the parameter's current value to a new integer.
The value passed in will be snapped to the permitted range before being used.
getRange()
Range<int> AudioParameterInt::getRange () const noexcept
Returns the parameter's range.
References NormalisableRange< ValueType >::end, RangedAudioParameter::getNormalisableRange(), int(), and NormalisableRange< ValueType >::start.
getNormalisableRange()
const NormalisableRange<float>& AudioParameterInt::getNormalisableRange () const override virtual
Returns the range of values that the parameter can take.
Implements RangedAudioParameter.
References AudioProcessorParameter::getDefaultValue(), RangedAudioParameter::getNumSteps(), AudioProcessorParameter::getText(), AudioProcessorParameter::getValue(), AudioProcessorParameter::getValueForText(), JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR, and AudioProcessorParameter::setValue().
valueChanged()
virtual void AudioParameterInt::valueChanged (int newValue) protected virtual
Override this method if you are interested in receiving callbacks when the parameter value changes.
The documentation for this class was generated from the following file:
juce_AudioParameterInt.h