JUCE: StandaloneFilterWindow Class Reference
StandaloneFilterWindow Class Reference
juce_audio_plugin_client » Standalone
A class that can be used to run a simple standalone application containing your filter.
Public Types
typedef StandalonePluginHolder::PluginInOuts PluginInOuts
Public Types inherited from DocumentWindow
enum TitleBarButtons { minimiseButton = 1, maximiseButton = 2, closeButton = 4, allButtons = 7 }
The set of available button-types that can be put on the title bar.
enum ColourIds { textColourId = 0x1005701 }
A set of colour IDs to use to change the colour of various aspects of the window.
Public Types inherited from ResizableWindow
enum ColourIds { backgroundColourId = 0x1005700 }
A set of colour IDs to use to change the colour of various aspects of the window.
Public Types inherited from Component
enum FocusChangeType { focusChangedByMouseClick, focusChangedByTabKey, focusChangedDirectly }
Enumeration used by the focusGained() and focusLost() methods.
Public Member Functions
StandaloneFilterWindow (const String &title, Colour backgroundColour, PropertySet *settingsToUse, bool takeOwnershipOfSettings, const String &preferredDefaultDeviceName=String(), const AudioDeviceManager::AudioDeviceSetup *preferredSetupOptions=nullptr, const Array< PluginInOuts > &constrainToConfiguration={}, bool autoOpenMidiDevices=true)
Creates a window with a given title and colour.
~StandaloneFilterWindow () override
AudioProcessor * getAudioProcessor () const noexcept
AudioDeviceManager & getDeviceManager () const noexcept
void resetToDefaultState ()
Deletes and re-creates the plugin, resetting it to its default state.
void closeButtonPressed () override
This method is called when the user tries to close the window.
void buttonClicked (Button *) override
Called when the button is clicked.
void handleMenuResult (int result)
void resized () override
Called when this component's size has been changed.
virtual StandalonePluginHolder * getPluginHolder ()
Public Member Functions inherited from DocumentWindow
DocumentWindow (const String &name, Colour backgroundColour, int requiredButtons, bool addToDesktop=true)
Creates a DocumentWindow.
~DocumentWindow () override
Destructor.
void setName (const String &newName) override
Changes the component's name.
void setIcon (const Image &imageToUse)
Sets an icon to show in the title bar, next to the title.
void setTitleBarHeight (int newHeight)
Changes the height of the title-bar.
int getTitleBarHeight () const
Returns the current title bar height.
void setTitleBarButtonsRequired (int requiredButtons, bool positionTitleBarButtonsOnLeft)
Changes the set of title-bar buttons being shown.
void setTitleBarTextCentred (bool textShouldBeCentred)
Sets whether the title should be centred within the window.
void setMenuBar (MenuBarModel *menuBarModel, int menuBarHeight=0)
Creates a menu inside this window.
Component * getMenuBarComponent () const noexcept
Returns the current menu bar component, or null if there isn't one.
void setMenuBarComponent (Component *newMenuBarComponent)
Replaces the current menu bar with a custom component.
virtual void minimiseButtonPressed ()
Callback that is triggered when the minimise button is pressed.
virtual void maximiseButtonPressed ()
Callback that is triggered when the maximise button is pressed, or when the title-bar is double-clicked.
Button * getCloseButton () const noexcept
Returns the close button, (or nullptr if there isn't one).
Button * getMinimiseButton () const noexcept
Returns the minimise button, (or nullptr if there isn't one).
Button * getMaximiseButton () const noexcept
Returns the maximise button, (or nullptr if there isn't one).
Public Member Functions inherited from ResizableWindow
ResizableWindow (const String &name, bool addToDesktop)
Creates a ResizableWindow.
ResizableWindow (const String &name, Colour backgroundColour, bool addToDesktop)
Creates a ResizableWindow.
~ResizableWindow () override
Destructor.
Colour getBackgroundColour () const noexcept
Returns the colour currently being used for the window's background.
void setBackgroundColour (Colour newColour)
Changes the colour currently being used for the window's background.
void setResizable (bool shouldBeResizable, bool useBottomRightCornerResizer)
Make the window resizable or fixed.
bool isResizable () const noexcept
Returns true if resizing is enabled.
void setResizeLimits (int newMinimumWidth, int newMinimumHeight, int newMaximumWidth, int newMaximumHeight) noexcept
This sets the maximum and minimum sizes for the window.
void setDraggable (bool shouldBeDraggable) noexcept
Can be used to enable or disable user-dragging of the window.
bool isDraggable () const noexcept
Returns true if the window can be dragged around by the user.
ComponentBoundsConstrainer * getConstrainer () noexcept
Returns the bounds constrainer object that this window is using.
void setConstrainer (ComponentBoundsConstrainer *newConstrainer)
Sets the bounds-constrainer object to use for resizing and dragging this window.
void setBoundsConstrained (const Rectangle< int > &newBounds)
Calls the window's setBounds method, after first checking these bounds with the current constrainer.
bool isFullScreen () const
Returns true if the window is currently in full-screen mode.
void setFullScreen (bool shouldBeFullScreen)
Puts the window into full-screen mode, or restores it to its normal size.
bool isMinimised () const
Returns true if the window is currently minimised.
void setMinimised (bool shouldMinimise)
Minimises the window, or restores it to its previous position and size.
bool isKioskMode () const
Returns true if the window has been placed in kiosk-mode.
String getWindowStateAsString ()
Returns a string which encodes the window's current size and position.
bool restoreWindowStateFromString (const String &previousState)
Restores the window to a previously-saved size and position.
Component * getContentComponent () const noexcept
Returns the current content component.
void setContentOwned (Component *newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
void setContentNonOwned (Component *newContentComponent, bool resizeToFitWhenContentChangesSize)
Changes the current content component.
void clearContentComponent ()
Removes the current content component.
void setContentComponentSize (int width, int height)
Changes the window so that the content component ends up with the specified size.
virtual BorderSize< int > getBorderThickness ()
Returns the width of the frame to use around the window.
virtual BorderSize< int > getContentComponentBorder ()
Returns the insets to use when positioning the content component.
JUCE_DEPRECATED (void setContentComponent(Component *newContentComponent, bool deleteOldOne=true, bool resizeToFit=false))
Public Member Functions inherited from TopLevelWindow
TopLevelWindow (const String &name, bool addToDesktop)
Creates a TopLevelWindow.
~TopLevelWindow () override
Destructor.
bool isActiveWindow () const noexcept
True if this is currently the TopLevelWindow that is actively being used.
void centreAroundComponent (Component *componentToCentreAround, int width, int height)
This will set the bounds of the window so that it's centred in front of another window.
void setDropShadowEnabled (bool useShadow)
Turns the drop-shadow on and off.
bool isDropShadowEnabled () const noexcept
True if drop-shadowing is enabled.
void setUsingNativeTitleBar (bool useNativeTitleBar)
Sets whether an OS-native title bar will be used, or a JUCE one.
bool isUsingNativeTitleBar () const noexcept
Returns true if the window is currently using an OS-native title bar.
void addToDesktop ()
Adds the window to the desktop using the default flags.
void addToDesktop (int windowStyleFlags, void *nativeWindowToAttachTo=nullptr) override
Public Member Functions inherited from Component
Component () noexcept
Creates a component.
~Component () override
Destructor.
Component (const String &componentName) noexcept
Creates a component, setting its name at the same time.
const String & getName () const noexcept
Returns the name of this component.
const String & getComponentID () const noexcept
Returns the ID string that was set by setComponentID().
void setComponentID (const String &newID)
Sets the component's ID string.
virtual void setVisible (bool shouldBeVisible)
Makes the component visible or invisible.
bool isVisible () const noexcept
Tests whether the component is visible or not.
bool isShowing () const
Tests whether this component and all its parents are visible.
void removeFromDesktop ()
If the component is currently showing on the desktop, this will hide it.
bool isOnDesktop () const noexcept
Returns true if this component is currently showing on the desktop.
ComponentPeer * getPeer () const
Returns the heavyweight window that contains this component.
virtual void userTriedToCloseWindow ()
For components on the desktop, this is called if the system wants to close the window.
virtual void minimisationStateChanged (bool isNowMinimised)
Called for a desktop component which has just been minimised or un-minimised.
virtual float getDesktopScaleFactor () const
Returns the default scale factor to use for this component when it is placed on the desktop.
void toFront (bool shouldAlsoGainFocus)
Brings the component to the front of its siblings.
void toBack ()
Changes this component's z-order to be at the back of all its siblings.
void toBehind (Component *other)
Changes this component's z-order so that it's just behind another component.
void setAlwaysOnTop (bool shouldStayOnTop)
Sets whether the component should always be kept at the front of its siblings.
bool isAlwaysOnTop () const noexcept
Returns true if this component is set to always stay in front of its siblings.
int getX () const noexcept
Returns the x coordinate of the component's left edge.
int getY () const noexcept
Returns the y coordinate of the top of this component.
int getWidth () const noexcept
Returns the component's width in pixels.
int getHeight () const noexcept
Returns the component's height in pixels.
int getRight () const noexcept
Returns the x coordinate of the component's right-hand edge.
Point< int > getPosition () const noexcept
Returns the component's top-left position as a Point.
int getBottom () const noexcept
Returns the y coordinate of the bottom edge of this component.
Rectangle< int > getBounds () const noexcept
Returns this component's bounding box.
Rectangle< int > getLocalBounds () const noexcept
Returns the component's bounds, relative to its own origin.
Rectangle< int > getBoundsInParent () const noexcept
Returns the area of this component's parent which this component covers.
int getScreenX () const
Returns this component's x coordinate relative the screen's top-left origin.
int getScreenY () const
Returns this component's y coordinate relative the screen's top-left origin.
Point< int > getScreenPosition () const
Returns the position of this component's top-left corner relative to the screen's top-left.
Rectangle< int > getScreenBounds () const
Returns the bounds of this component, relative to the screen's top-left.
Point< int > getLocalPoint (const Component *sourceComponent, Point< int > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Point< float > getLocalPoint (const Component *sourceComponent, Point< float > pointRelativeToSourceComponent) const
Converts a point to be relative to this component's coordinate space.
Rectangle< int > getLocalArea (const Component *sourceComponent, Rectangle< int > areaRelativeToSourceComponent) const
Converts a rectangle to be relative to this component's coordinate space.
Point< int > localPointToGlobal (Point< int > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Point< float > localPointToGlobal (Point< float > localPoint) const
Converts a point relative to this component's top-left into a screen coordinate.
Rectangle< int > localAreaToGlobal (Rectangle< int > localArea) const
Converts a rectangle from this component's coordinate space to a screen coordinate.
void setTopLeftPosition (int x, int y)
Moves the component to a new position.
void setTopLeftPosition (Point< int > newTopLeftPosition)
Moves the component to a new position.
void setTopRightPosition (int x, int y)
Moves the component to a new position.
void setSize (int newWidth, int newHeight)
Changes the size of the component.
void setBounds (int x, int y, int width, int height)
Changes the component's position and size.
void setBounds (Rectangle< int > newBounds)
Changes the component's position and size.
void setBoundsRelative (float proportionalX, float proportionalY, float proportionalWidth, float proportionalHeight)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsRelative (Rectangle< float > proportionalArea)
Changes the component's position and size in terms of fractions of its parent's size.
void setBoundsInset (BorderSize< int > borders)
Changes the component's position and size based on the amount of space to leave around it.
void setBoundsToFit (Rectangle< int > targetArea, Justification justification, bool onlyReduceInSize)
Positions the component within a given rectangle, keeping its proportions unchanged.
void setCentrePosition (int x, int y)
Changes the position of the component's centre.
void setCentrePosition (Point< int > newCentrePosition)
Changes the position of the component's centre.
void setCentreRelative (float x, float y)
Changes the position of the component's centre.
void centreWithSize (int width, int height)
Changes the component's size and centres it within its parent.
void setTransform (const AffineTransform &transform)
Sets a transform matrix to be applied to this component.
AffineTransform getTransform () const
Returns the transform that is currently being applied to this component.
bool isTransformed () const noexcept
Returns true if a non-identity transform is being applied to this component.
int proportionOfWidth (float proportion) const noexcept
Returns a proportion of the component's width.
int proportionOfHeight (float proportion) const noexcept
Returns a proportion of the component's height.
int getParentWidth () const noexcept
Returns the width of the component's parent.
int getParentHeight () const noexcept
Returns the height of the component's parent.
Rectangle< int > getParentMonitorArea () const
Returns the screen coordinates of the monitor that contains this component.
int getNumChildComponents () const noexcept
Returns the number of child components that this component contains.
Component * getChildComponent (int index) const noexcept
Returns one of this component's child components, by it index.
int getIndexOfChildComponent (const Component *child) const noexcept
Returns the index of this component in the list of child components.
const Array< Component * > & getChildren () const noexcept
Provides access to the underlying array of child components.
Component * findChildWithID (StringRef componentID) const noexcept
Looks for a child component with the specified ID.
void addChildComponent (Component *child, int zOrder=-1)
Adds a child component to this one.
void addChildComponent (Component &child, int zOrder=-1)
Adds a child component to this one.
void addAndMakeVisible (Component *child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addAndMakeVisible (Component &child, int zOrder=-1)
Adds a child component to this one, and also makes the child visible if it isn't already.
void addChildAndSetID (Component *child, const String &componentID)
Adds a child component to this one, makes it visible, and sets its component ID.
void removeChildComponent (Component *childToRemove)
Removes one of this component's child-components.
Component * removeChildComponent (int childIndexToRemove)
Removes one of this component's child-components by index.
void removeAllChildren ()
Removes all this component's children.
void deleteAllChildren ()
Removes and deletes all of this component's children.
Component * getParentComponent () const noexcept
Returns the component which this component is inside.
template<class TargetClass >
TargetClass * findParentComponentOfClass () const
Searches the parent components for a component of a specified class.
Component * getTopLevelComponent () const noexcept
Returns the highest-level component which contains this one or its parents.
bool isParentOf (const Component *possibleChild) const noexcept
Checks whether a component is anywhere inside this component or its children.
virtual void childrenChanged ()
Subclasses can use this callback to be told when children are added or removed, or when their z-order changes.
virtual bool hitTest (int x, int y)
Tests whether a given point is inside the component.
void setInterceptsMouseClicks (bool allowClicksOnThisComponent, bool allowClicksOnChildComponents) noexcept
Changes the default return value for the hitTest() method.
void getInterceptsMouseClicks (bool &allowsClicksOnThisComponent, bool &allowsClicksOnChildComponents) const noexcept
Retrieves the current state of the mouse-click interception flags.
bool contains (Point< int > localPoint)
Returns true if a given point lies within this component or one of its children.
bool reallyContains (Point< int > localPoint, bool returnTrueIfWithinAChild)
Returns true if a given point lies in this component, taking any overlapping siblings into account.
Component * getComponentAt (int x, int y)
Returns the component at a certain point within this one.
Component * getComponentAt (Point< int > position)
Returns the component at a certain point within this one.
void repaint ()
Marks the whole component as needing to be redrawn.
void repaint (int x, int y, int width, int height)
Marks a subsection of this component as needing to be redrawn.
void repaint (Rectangle< int > area)
Marks a subsection of this component as needing to be redrawn.
void setBufferedToImage (bool shouldBeBuffered)
Makes the component use an internal buffer to optimise its redrawing.
Image createComponentSnapshot (Rectangle< int > areaToGrab, bool clipImageToComponentBounds=true, float scaleFactor=1.0f)
Generates a snapshot of part of this component.
void paintEntireComponent (Graphics &context, bool ignoreAlphaLevel)
Draws this component and all its subcomponents onto the specified graphics context.
void setPaintingIsUnclipped (bool shouldPaintWithoutClipping) noexcept
This allows you to indicate that this component doesn't require its graphics context to be clipped when it is being painted.
bool isPaintingUnclipped () const noexcept
Returns true if this component doesn't require its graphics context to be clipped when it is being painted.
void setComponentEffect (ImageEffectFilter *newEffect)
Adds an effect filter to alter the component's appearance.
ImageEffectFilter * getComponentEffect () const noexcept
Returns the current component effect.
LookAndFeel & getLookAndFeel () const noexcept
Finds the appropriate look-and-feel to use for this component.
void setLookAndFeel (LookAndFeel *newLookAndFeel)
Sets the look and feel to use for this component.
void sendLookAndFeelChange ()
Calls the lookAndFeelChanged() method in this component and all its children.
void setOpaque (bool shouldBeOpaque)
Indicates whether any parts of the component might be transparent.
bool isOpaque () const noexcept
Returns true if no parts of this component are transparent.
void setBroughtToFrontOnMouseClick (bool shouldBeBroughtToFront) noexcept
Indicates whether the component should be brought to the front when clicked.
bool isBroughtToFrontOnMouseClick () const noexcept
Indicates whether the component should be brought to the front when clicked-on.
void setWantsKeyboardFocus (bool wantsFocus) noexcept
Sets a flag to indicate whether this component needs keyboard focus or not.
bool getWantsKeyboardFocus () const noexcept
Returns true if the component is interested in getting keyboard focus.
void setMouseClickGrabsKeyboardFocus (bool shouldGrabFocus)
Chooses whether a click on this component automatically grabs the focus.
bool getMouseClickGrabsKeyboardFocus () const noexcept
Returns the last value set with setMouseClickGrabsKeyboardFocus().
void grabKeyboardFocus ()
Tries to give keyboard focus to this component.
bool hasKeyboardFocus (bool trueIfChildIsFocused) const
Returns true if this component currently has the keyboard focus.
void moveKeyboardFocusToSibling (bool moveToNext)
Tries to move the keyboard focus to one of this component's siblings.
virtual KeyboardFocusTraverser * createFocusTraverser ()
Creates a KeyboardFocusTraverser object to use to determine the logic by which focus should be passed from this component.
int getExplicitFocusOrder () const
Returns the focus order of this component, if one has been specified.
void setExplicitFocusOrder (int newFocusOrderIndex)
Sets the index used in determining the order in which focusable components should be traversed.
void setFocusContainer (bool shouldBeFocusContainer) noexcept
Indicates whether this component is a parent for components that can have their focus traversed.
bool isFocusContainer () const noexcept
Returns true if this component has been marked as a focus container.
bool isEnabled () const noexcept
Returns true if the component (and all its parents) are enabled.
void setEnabled (bool shouldBeEnabled)
Enables or disables this component.
virtual void enablementChanged ()
Callback to indicate that this component has been enabled or disabled.
float getAlpha () const noexcept
Returns the component's current transparency level.
void setAlpha (float newAlpha)
Changes the transparency of this component.
virtual void alphaChanged ()
Called when setAlpha() is used to change the alpha value of this component.
void setMouseCursor (const MouseCursor &cursorType)
Changes the mouse cursor shape to use when the mouse is over this component.
virtual MouseCursor getMouseCursor ()
Returns the mouse cursor shape to use when the mouse is over this component.
void updateMouseCursor () const
Forces the current mouse cursor to be updated.
virtual void paintOverChildren (Graphics &g)
Components can override this method to draw over the top of their children.
void mouseMove (const MouseEvent &event) override
Called when the mouse moves inside a component.
void mouseEnter (const MouseEvent &event) override
Called when the mouse first enters a component.
void mouseExit (const MouseEvent &event) override
Called when the mouse moves out of a component.
void mouseDoubleClick (const MouseEvent &event) override
Called when a mouse button has been double-clicked on a component.
void mouseWheelMove (const MouseEvent &event, const MouseWheelDetails &wheel) override
Called when the mouse-wheel is moved.
void mouseMagnify (const MouseEvent &event, float scaleFactor) override
Called when a pinch-to-zoom mouse-gesture is used.
void setRepaintsOnMouseActivity (bool shouldRepaint) noexcept
Causes automatic repaints when the mouse enters or exits this component.
void addMouseListener (MouseListener *newListener, bool wantsEventsForAllNestedChildComponents)
Registers a listener to be told when mouse events occur in this component.
void removeMouseListener (MouseListener *listenerToRemove)
Deregisters a mouse listener.
void addKeyListener (KeyListener *newListener)
Adds a listener that wants to hear about keypresses that this component receives.
void removeKeyListener (KeyListener *listenerToRemove)
Removes a previously-registered key listener.
virtual bool keyPressed (const KeyPress &key)
Called when a key is pressed.
virtual bool keyStateChanged (bool isKeyDown)
Called when a key is pressed or released.
virtual void modifierKeysChanged (const ModifierKeys &modifiers)
Called when a modifier key is pressed or released.
virtual void focusGained (FocusChangeType cause)
Called to indicate that this component has just acquired the keyboard focus.
virtual void focusLost (FocusChangeType cause)
Called to indicate that this component has just lost the keyboard focus.
bool isMouseOver (bool includeChildren=false) const
Returns true if the mouse is currently over this component.
bool isMouseButtonDown (bool includeChildren=false) const
Returns true if the mouse button is currently held down in this component.
bool isMouseOverOrDragging (bool includeChildren=false) const
True if the mouse is over this component, or if it's being dragged in this component.
Point< int > getMouseXYRelative () const
Returns the mouse's current position, relative to this component.
virtual void broughtToFront ()
Called when this component has been moved to the front of its siblings.
void addComponentListener (ComponentListener *newListener)
Adds a listener to be told about changes to the component hierarchy or position.
void removeComponentListener (ComponentListener *listenerToRemove)
Removes a component listener.
void postCommandMessage (int commandId)
Dispatches a numbered message to this component.
virtual void handleCommandMessage (int commandId)
Called to handle a command that was sent by postCommandMessage().
int runModalLoop ()
Runs a component modally, waiting until the loop terminates.
void enterModalState (bool takeKeyboardFocus=true, ModalComponentManager::Callback *callback=nullptr, bool deleteWhenDismissed=false)
Puts the component into a modal state.
void exitModalState (int returnValue)
Ends a component's modal state.
bool isCurrentlyModal (bool onlyConsiderForemostModalComponent=true) const noexcept
Returns true if this component is the modal one.
bool isCurrentlyBlockedByAnotherModalComponent () const
Checks whether there's a modal component somewhere that's stopping this one from receiving messages.
virtual bool canModalEventBeSentToComponent (const Component *targetComponent)
When a component is modal, this callback allows it to choose which other components can still receive events.
virtual void inputAttemptWhenModal ()
Called when the user tries to click on a component that is blocked by another modal component.
NamedValueSet & getProperties () noexcept
Returns the set of properties that belong to this component.
const NamedValueSet & getProperties () const noexcept
Returns the set of properties that belong to this component.
Colour findColour (int colourID, bool inheritFromParent=false) const
Looks for a colour that has been registered with the given colour ID number.
void setColour (int colourID, Colour newColour)
Registers a colour to be used for a particular purpose.
void removeColour (int colourID)
If a colour has been set with setColour(), this will remove it.
bool isColourSpecified (int colourID) const
Returns true if the specified colour ID has been explicitly set for this component using the setColour() method.
void copyAllExplicitColoursTo (Component &target) const
This looks for any colours that have been specified for this component, and copies them to the specified target component.
virtual void colourChanged ()
This method is called when a colour is changed by the setColour() method.
void * getWindowHandle () const
Returns the underlying native window handle for this component.
Positioner * getPositioner () const noexcept
Returns the Positioner object that has been set for this component.
void setPositioner (Positioner *newPositioner)
Sets a new Positioner object for this component.
void setCachedComponentImage (CachedComponentImage *newCachedImage)
Gives the component a CachedComponentImage that should be used to buffer its painting.
CachedComponentImage * getCachedComponentImage () const noexcept
Returns the object that was set by setCachedComponentImage().
void setViewportIgnoreDragFlag (bool ignoreDrag) noexcept
Sets a flag to indicate whether mouse drag events on this Component should be ignored when it is inside a Viewport with drag-to-scroll functionality enabled.
bool getViewportIgnoreDragFlag () const noexcept
Retrieves the current state of the Viewport drag-to-scroll functionality flag.
Public Member Functions inherited from MouseListener
virtual ~MouseListener ()=default
Destructor.
Public Member Functions inherited from Button::Listener
virtual ~Listener ()=default
Destructor.
virtual void buttonStateChanged (Button *)
Called when the button's state changes.
Static Public Member Functions
static void menuCallback (int result, StandaloneFilterWindow *button)
Static Public Member Functions inherited from TopLevelWindow
static int getNumTopLevelWindows () noexcept
Returns the number of TopLevelWindow objects currently in use.
static TopLevelWindow * getTopLevelWindow (int index) noexcept
Returns one of the TopLevelWindow objects currently in use.
static TopLevelWindow * getActiveTopLevelWindow () noexcept
Returns the currently-active top level window.
Static Public Member Functions inherited from Component
static float JUCE_CALLTYPE getApproximateScaleFactorForComponent (Component *targetComponent)
Returns the approximate scale factor for a given component by traversing its parent hierarchy and applying each transform and finally scaling this by the global scale factor.
static Component *JUCE_CALLTYPE getCurrentlyFocusedComponent () noexcept
Returns the component that currently has the keyboard focus.
static void JUCE_CALLTYPE unfocusAllComponents ()
If any component has keyboard focus, this will defocus it.
static void JUCE_CALLTYPE beginDragAutoRepeat (int millisecondsBetweenCallbacks)
Ensures that a non-stop stream of mouse-drag events will be sent during the current mouse-drag operation.
static bool JUCE_CALLTYPE isMouseButtonDownAnywhere () noexcept
Returns true if a mouse button is currently down.
static int JUCE_CALLTYPE getNumCurrentlyModalComponents () noexcept
Returns the number of components that are currently in a modal state.
static Component *JUCE_CALLTYPE getCurrentlyModalComponent (int index=0) noexcept
Returns one of the components that are currently modal.
Public Attributes
std::unique_ptr< StandalonePluginHolder > pluginHolder
Additional Inherited Members
Protected Member Functions inherited from ResizableWindow
void paint (Graphics &) override
void moved () override
(if overriding this, make sure you call ResizableWindow::moved() in your subclass)
void resized () override
(if overriding this, make sure you call ResizableWindow::resized() in your subclass)
void mouseDown (const MouseEvent &) override
void mouseDrag (const MouseEvent &) override
void mouseUp (const MouseEvent &) override
void lookAndFeelChanged () override
void childBoundsChanged (Component *) override
void parentSizeChanged () override
void visibilityChanged () override
void activeWindowStatusChanged () override
int getDesktopWindowStyleFlags () const override
Protected Member Functions inherited from TopLevelWindow
void focusOfChildComponentChanged (FocusChangeType) override
void parentHierarchyChanged () override
void recreateDesktopWindow ()
void visibilityChanged () override
Protected Attributes inherited from ResizableWindow
std::unique_ptr< ResizableCornerComponent > resizableCorner
std::unique_ptr< ResizableBorderComponent > resizableBorder
Detailed Description
A class that can be used to run a simple standalone application containing your filter.
Just create one of these objects in your JUCEApplicationBase::initialise() method, and let it do its work. It will create your filter object using the same createPluginFilter() function that the other plugin wrappers use.
Member Typedef Documentation
PluginInOuts
typedef StandalonePluginHolder::PluginInOuts StandaloneFilterWindow::PluginInOuts
Constructor & Destructor Documentation
StandaloneFilterWindow()
StandaloneFilterWindow::StandaloneFilterWindow (const String & title, Colour backgroundColour, PropertySet * settingsToUse, bool takeOwnershipOfSettings, const String & preferredDefaultDeviceName = String(), const AudioDeviceManager::AudioDeviceSetup * preferredSetupOptions = nullptr, const Array< PluginInOuts > & constrainToConfiguration = {}, bool autoOpenMidiDevices = true)
Creates a window with a given title and colour.
The settings object can be a PropertySet that the class should use to store its settings (it can also be null). If takeOwnershipOfSettings is true, then the settings object will be owned and deleted by this object.
References Component::addAndMakeVisible(), StandalonePluginHolder::autoOpenMidiDevices, DocumentWindow::closeButton, and DocumentWindow::minimiseButton.
~StandaloneFilterWindow()
StandaloneFilterWindow::~StandaloneFilterWindow () override
Member Function Documentation
getAudioProcessor()
AudioProcessor* StandaloneFilterWindow::getAudioProcessor () const noexcept
getDeviceManager()
AudioDeviceManager& StandaloneFilterWindow::getDeviceManager () const noexcept
resetToDefaultState()
void StandaloneFilterWindow::resetToDefaultState ()
Deletes and re-creates the plugin, resetting it to its default state.
closeButtonPressed()
void StandaloneFilterWindow::closeButtonPressed () override virtual
This method is called when the user tries to close the window.
This is triggered by the user clicking the close button, or using some other OS-specific key shortcut or OS menu for getting rid of a window.
If the window is just a pop-up, you should override this closeButtonPressed() method and make it delete the window in whatever way is appropriate for your app. E.g. you might just want to call "delete this".
If your app is centred around this window such that the whole app should quit when the window is closed, then you will probably want to use this method as an opportunity to call JUCEApplicationBase::quit(), and leave the window to be deleted later by your JUCEApplicationBase::shutdown() method. (Doing it this way means that your window will still get cleaned-up if the app is quit by some other means (e.g. a cmd-Q on the mac or closing it via the taskbar icon on Windows).
(Note that the DocumentWindow class overrides Component::userTriedToCloseWindow() and redirects it to call this method, so any methods of closing the window that are caught by userTriedToCloseWindow() will also end up here).
Reimplemented from DocumentWindow.
References JUCEApplicationBase::quit().
buttonClicked()
void StandaloneFilterWindow::buttonClicked (Button *) override virtual
Called when the button is clicked.
Implements Button::Listener.
References PopupMenu::addItem(), PopupMenu::addSeparator(), ModalCallbackFunction::forComponent(), PopupMenu::showMenuAsync(), and TRANS.
handleMenuResult()
void StandaloneFilterWindow::handleMenuResult (int result)
Referenced by menuCallback().
menuCallback()
static void StandaloneFilterWindow::menuCallback (int result, StandaloneFilterWindow * button) static
References handleMenuResult().
resized()
void StandaloneFilterWindow::resized () override virtual
Called when this component's size has been changed.
A component can implement this method to do things such as laying out its child components when its width or height changes.
The method is called synchronously as a result of the setBounds or setSize methods, so repeatedly changing a components size will repeatedly call its resized method (unlike things like repainting, where multiple calls to repaint are coalesced together).
If the component is a top-level window on the desktop, its size could also be changed by operating-system factors beyond the application's control.
See also
moved, setSize
Reimplemented from Component.
References ResizableWindow::resized().
getPluginHolder()
virtual StandalonePluginHolder* StandaloneFilterWindow::getPluginHolder () virtual
Member Data Documentation
pluginHolder
std::unique_ptr<StandalonePluginHolder> StandaloneFilterWindow::pluginHolder
The documentation for this class was generated from the following file:
juce_StandaloneFilterWindow.h