JUCE: MidiEventList Class Reference
MidiEventList Class Reference
Public Member Functions
MidiEventList ()
virtual ~MidiEventList ()
JUCE_DECLARE_VST3_COM_REF_METHODS
JUCE_DECLARE_VST3_COM_QUERY_METHODS
void clear ()
Steinberg::int32 PLUGIN_API getEventCount () override
Steinberg::tresult PLUGIN_API getEvent (Steinberg::int32 index, Steinberg::Vst::Event &e) override
Steinberg::tresult PLUGIN_API addEvent (Steinberg::Vst::Event &e) override
Static Public Member Functions
static void toMidiBuffer (MidiBuffer &result, Steinberg::Vst::IEventList &eventList)
static void toEventList (Steinberg::Vst::IEventList &result, MidiBuffer &midiBuffer)
Constructor & Destructor Documentation
MidiEventList::MidiEventList ()
virtual MidiEventList::~MidiEventList () virtual
Member Function Documentation
JUCE_DECLARE_VST3_COM_REF_METHODS JUCE_DECLARE_VST3_COM_QUERY_METHODS void MidiEventList::clear ()
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick().
Steinberg::int32 PLUGIN_API MidiEventList::getEventCount () override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Steinberg::tresult PLUGIN_API MidiEventList::getEvent (Steinberg::int32 index, Steinberg::Vst::Event & e) override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), isPositiveAndBelow(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Steinberg::tresult PLUGIN_API MidiEventList::addEvent (Steinberg::Vst::Event & e) override
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add().
static void MidiEventList::toMidiBuffer (MidiBuffer & result, Steinberg::Vst::IEventList & eventList) static
References MidiBuffer::addEvent(), MidiMessage::aftertouchChange(), MidiMessage::createSysExMessage(), MidiMessage::noteOff(), and MidiMessage::noteOn().
static void MidiEventList::toEventList (Steinberg::Vst::IEventList & result, MidiBuffer & midiBuffer) static
References MidiMessage::getAfterTouchValue(), MidiMessage::getChannel(), MidiBuffer::Iterator::getNextEvent(), MidiMessage::getNoteNumber(), MidiMessage::getSysExData(), MidiMessage::getSysExDataSize(), MidiMessage::getVelocity(), MidiMessage::isAftertouch(), MidiMessage::isNoteOff(), MidiMessage::isNoteOn(), MidiMessage::isSysEx(), and MidiMessage::noteOn().
The documentation for this class was generated from the following file:
juce_VST3Common.h