JUCE: time
time
juce_core
Classes
class PerformanceCounter
A timer for measuring performance of code and dumping the results to a file.
struct PerformanceCounter::Statistics
Holds the current statistics.
class ScopedTimeMeasurement
Simple RAII class for measuring the time spent in a scope.
class RelativeTime
A relative measure of time.
class Time
Holds an absolute date and time.
Functions
JUCE_API bool JUCE_CALLTYPE operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API bool JUCE_CALLTYPE operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
JUCE_API RelativeTime JUCE_CALLTYPE operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
JUCE_API RelativeTime JUCE_CALLTYPE operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
JUCE_API Time operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
JUCE_API Time operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
JUCE_API const RelativeTime operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
JUCE_API bool operator== (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator< (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator> (Time time1, Time time2) noexcept
Compares two Time objects.
JUCE_API bool operator>= (Time time1, Time time2) noexcept
Compares two Time objects.
Detailed Description
Function Documentation
operator==() [1/2]
JUCE_API bool JUCE_CALLTYPE operator== (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator!=() [1/2]
JUCE_API bool JUCE_CALLTYPE operator!= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator>() [1/2]
JUCE_API bool JUCE_CALLTYPE operator> (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator<() [1/2]
JUCE_API bool JUCE_CALLTYPE operator< (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator>=() [1/2]
JUCE_API bool JUCE_CALLTYPE operator>= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator<=() [1/2]
JUCE_API bool JUCE_CALLTYPE operator<= (RelativeTime t1, RelativeTime t2) noexcept
Compares two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator+() [1/3]
JUCE_API RelativeTime JUCE_CALLTYPE operator+ (RelativeTime t1, RelativeTime t2) noexcept
Adds two RelativeTimes together.
Referenced by RelativeTime::inSeconds().
operator-() [1/3]
JUCE_API RelativeTime JUCE_CALLTYPE operator- (RelativeTime t1, RelativeTime t2) noexcept
Subtracts two RelativeTimes.
Referenced by RelativeTime::inSeconds().
operator+() [2/3]
JUCE_API Time operator+ (Time time, RelativeTime delta) noexcept
Adds a RelativeTime to a Time.
Referenced by Time::toMilliseconds().
operator+() [3/3]
JUCE_API Time operator+ (RelativeTime delta, Time time) noexcept
Adds a RelativeTime to a Time.
operator-() [2/3]
JUCE_API Time operator- (Time time, RelativeTime delta) noexcept
Subtracts a RelativeTime from a Time.
Referenced by Time::toMilliseconds().
operator-() [3/3]
JUCE_API const RelativeTime operator- (Time time1, Time time2) noexcept
Returns the relative time difference between two times.
operator==() [2/2]
JUCE_API bool operator== (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().
operator!=() [2/2]
JUCE_API bool operator!= (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().
operator<() [2/2]
JUCE_API bool operator< (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().
operator<=() [2/2]
JUCE_API bool operator<= (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().
operator>() [2/2]
JUCE_API bool operator> (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().
operator>=() [2/2]
JUCE_API bool operator>= (Time time1, Time time2) noexcept
Compares two Time objects.
Referenced by Time::toMilliseconds().