JUCE: utility
utility
juce_audio_plugin_client
Classes
class PluginHostType
A useful utility class to determine the host or DAW in which your plugin is loaded.
Macros
#define JUCE_CHECKSETTINGMACROS_H
#define JucePlugin_Build_VST3 0
#define Component juce::Component
#define Point juce::Point
Functions
void attachWindowHidingHooks (void *, void *, void *)
void removeWindowHidingHooks (void *)
juce::AudioProcessor *JUCE_CALLTYPE createPluginFilter ()
Somewhere in the codebase of your plugin, you need to implement this function and make it return a new instance of the filter subclass that you're building.
AudioProcessor *JUCE_API JUCE_CALLTYPE createPluginFilterOfType (AudioProcessor::WrapperType type)
void repostCurrentNSEvent ()
const PluginHostType & getHostType ()
Detailed Description
Macro Definition Documentation
JUCE_CHECKSETTINGMACROS_H
#define JUCE_CHECKSETTINGMACROS_H
JucePlugin_Build_VST3
#define JucePlugin_Build_VST3 0
Component
#define Component juce::Component
Point
#define Point juce::Point
Function Documentation
attachWindowHidingHooks()
void attachWindowHidingHooks (void * , void * , void *)
removeWindowHidingHooks()
void removeWindowHidingHooks (void *)
createPluginFilter()
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter ()
Somewhere in the codebase of your plugin, you need to implement this function and make it return a new instance of the filter subclass that you're building.
Referenced by createPluginFilterOfType().
createPluginFilterOfType()
AudioProcessor* JUCE_API JUCE_CALLTYPE createPluginFilterOfType (AudioProcessor::WrapperType type)
References createPluginFilter(), jassert, AudioProcessor::setTypeOfNextNewPlugin(), AudioProcessor::wrapperType, and AudioProcessor::wrapperType_Undefined.
Referenced by StandalonePluginHolder::createPlugin().
repostCurrentNSEvent()
void repostCurrentNSEvent ()
getHostType()
const PluginHostType& getHostType ()