JUCE: Standalone
Standalone
juce_audio_plugin_client
Classes
class StandalonePluginHolder
An object that creates and plays a standalone instance of an AudioProcessor.
struct StandalonePluginHolder::PluginInOuts
Structure used for the number of inputs and outputs.
class StandaloneFilterWindow
A class that can be used to run a simple standalone application containing your filter.
Functions
static StandalonePluginHolder * StandalonePluginHolder::getInstance ()
Detailed Description
Function Documentation
getInstance()
StandalonePluginHolder * StandalonePluginHolder::getInstance () static
References Desktop::getInstance(), PluginHostType::getPluginLoadedAs(), and AudioProcessor::wrapperType_Standalone.
Referenced by StandalonePluginHolder::isInterAppAudioConnected().