JUCE: juce_PixelFormats.h File Reference
juce_PixelFormats.h File Reference
Classes
class PixelARGB
Represents a 32-bit INTERNAL pixel with premultiplied alpha, and can perform compositing operations with it.
class PixelRGB
Represents a 24-bit RGB pixel, and can perform compositing operations on it.
class PixelAlpha
Represents an 8-bit single-channel pixel, and can perform compositing operations on it.
Functions
uint32 maskPixelComponents (uint32 x) noexcept
uint32 clampPixelComponents (uint32 x) noexcept
Function Documentation
uint32 maskPixelComponents (uint32 x) noexcept
Referenced by PixelARGB::blend(), PixelRGB::blend(), and clampPixelComponents().
uint32 clampPixelComponents (uint32 x) noexcept
References maskPixelComponents().
Referenced by PixelARGB::blend(), and PixelRGB::blend().