JUCE: juce_MathsFunctions.h File Reference
juce_MathsFunctions.h File Reference
Classes
struct TypeHelpers::ParameterType< Type >
The ParameterType struct is used to find the best type to use when passing some kind of object as a parameter.
struct TypeHelpers::SmallestFloatType< Type >
These templates are designed to take a type, and if it's a double, they return a double type; for anything else, they return a float type.
struct TypeHelpers::SmallestFloatType< double >
struct TypeHelpers::UnsignedTypeWithSize< bytes >
These templates are designed to take an integer type, and return an unsigned int version with the same size.
struct TypeHelpers::UnsignedTypeWithSize< 1 >
struct TypeHelpers::UnsignedTypeWithSize< 2 >
struct TypeHelpers::UnsignedTypeWithSize< 4 >
struct TypeHelpers::UnsignedTypeWithSize< 8 >
Namespaces
TypeHelpers
This namespace contains a few template classes for helping work out class type variations.
Macros
#define JUCE_UNDENORMALISE(x) { (x) += 0.1f; (x) -= 0.1f; }
This macro can be applied to a float variable to check whether it contains a denormalised value, and to normalise it if necessary.
Typedefs
typedef signed char int8
A platform-independent 8-bit signed integer type.
typedef unsigned char uint8
A platform-independent 8-bit unsigned integer type.
typedef signed short int16
A platform-independent 16-bit signed integer type.
typedef unsigned short uint16
A platform-independent 16-bit unsigned integer type.
typedef signed int int32
A platform-independent 32-bit signed integer type.
typedef unsigned int uint32
A platform-independent 32-bit unsigned integer type.
typedef long long int64
A platform-independent 64-bit integer type.
typedef unsigned long long uint64
A platform-independent 64-bit unsigned integer type.
typedef int pointer_sized_int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
typedef unsigned int pointer_sized_uint
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
Functions
template<typename Type >
Type jmax (const Type a, const Type b)
Returns the larger of two values.
template<typename Type >
Type jmax (const Type a, const Type b, const Type c)
Returns the larger of three values.
template<typename Type >
Type jmax (const Type a, const Type b, const Type c, const Type d)
Returns the larger of four values.
template<typename Type >
Type jmin (const Type a, const Type b)
Returns the smaller of two values.
template<typename Type >
Type jmin (const Type a, const Type b, const Type c)
Returns the smaller of three values.
template<typename Type >
Type jmin (const Type a, const Type b, const Type c, const Type d)
Returns the smaller of four values.
template<typename Type >
Type jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax)
Remaps a normalised value (between 0 and 1) to a target range.
template<typename Type >
Type jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax)
Remaps a value from a source range to a target range.
template<typename Type >
Type findMinimum (const Type *data, int numValues)
Scans an array of values, returning the minimum value that it contains.
template<typename Type >
Type findMaximum (const Type *values, int numValues)
Scans an array of values, returning the maximum value that it contains.
template<typename Type >
void findMinAndMax (const Type *values, int numValues, Type &lowest, Type &highest)
Scans an array of values, returning the minimum and maximum values that it contains.
template<typename Type >
Type jlimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) noexcept
Constrains a value to keep it within a given range.
template<typename Type >
bool isPositiveAndBelow (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
template<>
bool isPositiveAndBelow (const int valueToTest, const int upperLimit) noexcept
template<typename Type >
bool isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
template<>
bool isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) noexcept
template<typename Type >
void swapVariables (Type &variable1, Type &variable2)
Handy function to swap two values.
template<typename Type1 >
void ignoreUnused (const Type1 &) noexcept
Handy function for avoiding unused variables warning.
template<typename Type1 , typename Type2 >
void ignoreUnused (const Type1 &, const Type2 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 >
void ignoreUnused (const Type1 &, const Type2 &, const Type3 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 , typename Type4 >
void ignoreUnused (const Type1 &, const Type2 &, const Type3 &, const Type4 &) noexcept
template<typename Type , int N>
int numElementsInArray (Type(&array)[N])
Handy function for getting the number of elements in a simple const C array.
template<typename Type >
Type juce_hypot (Type a, Type b) noexcept
Using juce_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
int64 abs64 (const int64 n) noexcept
64-bit abs function.
float degreesToRadians (float degrees) noexcept
Converts an angle in degrees to radians.
double degreesToRadians (double degrees) noexcept
Converts an angle in degrees to radians.
float radiansToDegrees (float radians) noexcept
Converts an angle in radians to degrees.
double radiansToDegrees (double radians) noexcept
Converts an angle in radians to degrees.
template<typename NumericType >
bool juce_isfinite (NumericType) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
template<>
bool juce_isfinite (float value) noexcept
template<>
bool juce_isfinite (double value) noexcept
template<typename FloatType >
int roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
int roundToInt (int value) noexcept
int roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
int roundDoubleToInt (double value) noexcept
Fast floating-point-to-integer conversion.
int roundFloatToInt (float value) noexcept
Fast floating-point-to-integer conversion.
template<typename IntegerType >
bool isPowerOfTwo (IntegerType value)
Returns true if the specified integer is a power-of-two.
int nextPowerOfTwo (int n) noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
int findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
int countNumberOfBits (uint32 n) noexcept
Returns the number of bits in a 32-bit integer.
int countNumberOfBits (uint64 n) noexcept
Returns the number of bits in a 64-bit integer.
template<typename IntegerType >
IntegerType negativeAwareModulo (IntegerType dividend, const IntegerType divisor) noexcept
Performs a modulo operation, but can cope with the dividend being negative.
template<typename NumericType >
NumericType square (NumericType n) noexcept
Returns the square of its argument.
void writeLittleEndianBitsInBuffer (void *targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
uint32 readLittleEndianBitsInBuffer (const void *sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
Variables
const double double_Pi = 3.1415926535897932384626433832795
A predefined value for Pi, at double-precision.
const float float_Pi = 3.14159265358979323846f
A predefined value for Pi, at single-precision.
Macro Definition Documentation
#define JUCE_UNDENORMALISE (x) { (x) += 0.1f; (x) -= 0.1f; }
This macro can be applied to a float variable to check whether it contains a denormalised value, and to normalise it if necessary.
On CPUs that aren't vulnerable to denormalisation problems, this will have no effect.
Typedef Documentation
typedef signed char int8
A platform-independent 8-bit signed integer type.
typedef unsigned char uint8
A platform-independent 8-bit unsigned integer type.
typedef signed short int16
A platform-independent 16-bit signed integer type.
typedef unsigned short uint16
A platform-independent 16-bit unsigned integer type.
typedef signed int int32
A platform-independent 32-bit signed integer type.
typedef unsigned int uint32
A platform-independent 32-bit unsigned integer type.
typedef long long int64
A platform-independent 64-bit integer type.
typedef unsigned long long uint64
A platform-independent 64-bit unsigned integer type.
typedef int pointer_sized_int
A signed integer type that's guaranteed to be large enough to hold a pointer without truncating it.
typedef unsigned int pointer_sized_uint
An unsigned integer type that's guaranteed to be large enough to hold a pointer without truncating it.
Function Documentation
template<typename Type > Type jmax (const Type a, const Type b)
Returns the larger of two values.
Referenced by Rectangle< int >::enlargeIfAdjacent(), Rectangle< int >::expand(), Rectangle< int >::expanded(), Rectangle< int >::findAreaContainingPoints(), Decibels::gainToDecibels(), RectangleList< int >::getBounds(), Rectangle< int >::getIntersection(), Range< int64 >::getIntersectionWith(), AudioBuffer< float >::getMagnitude(), Rectangle< int >::getUnion(), Range< int64 >::getUnionWith(), Rectangle< int >::intersectRectangle(), Rectangle< int >::intersectRectangles(), jmax(), AudioUnitHelpers::CoreAudioBufferList::prepare(), ResizableBorderComponent::Zone::resizeRectangleBy(), Rectangle< int >::setLeft(), Range< int64 >::setLength(), TextEditor::setLineSpacing(), Draggable3DOrientation::setRadius(), Rectangle< int >::setTop(), Rectangle< int >::transformedBy(), Rectangle< int >::withBottom(), Rectangle< int >::withLeft(), Rectangle< int >::withRight(), Range< int64 >::withStart(), and Rectangle< int >::withTop().
template<typename Type > Type jmax (const Type a, const Type b, const Type c)
Returns the larger of three values.
template<typename Type > Type jmax (const Type a, const Type b, const Type c, const Type d)
Returns the larger of four values.
References jmax().
template<typename Type > Type jmin (const Type a, const Type b)
Returns the smaller of two values.
Referenced by Rectangle< int >::constrainedWithin(), SelectedItemSet< SelectableItemType >::deselectAll(), Rectangle< int >::enlargeIfAdjacent(), Rectangle< int >::findAreaContainingPoints(), RectangleList< int >::getBounds(), AudioUnitHelpers::getBusCount(), Rectangle< int >::getIntersection(), Range< int64 >::getIntersectionWith(), Rectangle< int >::getUnion(), Range< int64 >::getUnionWith(), Rectangle< int >::intersectRectangle(), Rectangle< int >::intersectRectangles(), jmin(), Rectangle< int >::removeFromBottom(), Rectangle< int >::removeFromLeft(), Rectangle< int >::removeFromRight(), Rectangle< int >::removeFromTop(), SparseSet< int >::removeRange(), ResizableBorderComponent::Zone::resizeRectangleBy(), SelectedItemSet< SelectableItemType >::selectOnly(), Rectangle< int >::setBottom(), Rectangle< int >::setRight(), AudioBuffer< float >::setSize(), Rectangle< int >::transformedBy(), PixelARGB::unpremultiply(), Rectangle< int >::withBottom(), Range< int64 >::withEnd(), Rectangle< int >::withRight(), Line< ValueType >::withShortenedEnd(), Line< ValueType >::withShortenedStart(), and Packed7BitArrayBuilder< maxPacketBytes >::writeBits().
template<typename Type > Type jmin (const Type a, const Type b, const Type c)
Returns the smaller of three values.
template<typename Type > Type jmin (const Type a, const Type b, const Type c, const Type d)
Returns the smaller of four values.
References jmin().
template<typename Type > Type jmap (Type value0To1, Type targetRangeMin, Type targetRangeMax)
Remaps a normalised value (between 0 and 1) to a target range.
This effectively returns (targetRangeMin + value0To1 * (targetRangeMax - targetRangeMin)).
template<typename Type > Type jmap (Type sourceValue, Type sourceRangeMin, Type sourceRangeMax, Type targetRangeMin, Type targetRangeMax)
Remaps a value from a source range to a target range.
References jassert.
template<typename Type > Type findMinimum (const Type * data, int numValues)
Scans an array of values, returning the minimum value that it contains.
template<typename Type > Type findMaximum (const Type * values, int numValues)
Scans an array of values, returning the maximum value that it contains.
template<typename Type > void findMinAndMax (const Type * values, int numValues, Type & lowest, Type & highest)
Scans an array of values, returning the minimum and maximum values that it contains.
Referenced by AudioData::Pointer< SampleFormat, Endianness, InterleavingType, Constness >::findMinAndMax().
template<typename Type > Type jlimit (const Type lowerLimit, const Type upperLimit, const Type valueToConstrain) noexcept
Constrains a value to keep it within a given range.
This will check that the specified value lies between the lower and upper bounds specified, and if not, will return the nearest value that would be in-range. Effectively, it's like calling jmax (lowerLimit, jmin (upperLimit, value)).
Note that it expects that lowerLimit <= upperLimit. If this isn't true, the results will be unpredictable.
Parameters
lowerLimit the minimum value to return
upperLimit the maximum value to return
valueToConstrain the value to try to return
Returns
the closest value to valueToConstrain which lies between lowerLimit and upperLimit (inclusive)
See Also
jmin, jmax, jmap
References jassert.
Referenced by Range< int64 >::clipValue(), Rectangle< int >::constrainedWithin(), Range< int64 >::constrainRange(), Line< ValueType >::findNearestProportionalPositionTo(), IntegerWithBitSize< 8 >::fromBipolarFloat(), IntegerWithBitSize< 8 >::fromUnipolarFloat(), Rectangle< int >::getConstrainedPoint(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeRange(), OwnedArray< MidiBuffer >::removeRange(), and Array< Button::Listener * >::removeRange().
template<typename Type > bool isPositiveAndBelow (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also below a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest < upperLimit
References jassert.
Referenced by AudioBuffer< float >::addFrom(), AudioBuffer< float >::addFromWithRamp(), AudioBuffer< float >::addSample(), AudioBuffer< float >::applyGain(), AudioBuffer< float >::applyGainRamp(), AudioBuffer< float >::clear(), AudioBuffer< float >::copyFrom(), AudioBuffer< float >::copyFromWithRamp(), AudioBuffer< float >::findMinMax(), MidiEventList::getEvent(), AudioBuffer< float >::getMagnitude(), AudioProcessor::BusesLayout::getNumChannels(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointer(), ReferenceCountedArray< AudioProcessorGraph::Node >::getObjectPointerUnchecked(), SparseSet< int >::getRange(), AudioBuffer< float >::getReadPointer(), Array< Button::Listener * >::getReference(), AudioBuffer< float >::getRMSLevel(), AudioBuffer< float >::getSample(), OwnedArray< MidiBuffer >::getUnchecked(), Array< Button::Listener * >::getUnchecked(), AudioBuffer< float >::getWritePointer(), Array< Button::Listener * >::insert(), OwnedArray< MidiBuffer >::insertArray(), Array< Button::Listener * >::insertArray(), Array< Button::Listener * >::insertMultiple(), EdgeTable::iterate(), ReferenceCountedArray< AudioProcessorGraph::Node >::move(), OwnedArray< MidiBuffer >::move(), Array< Button::Listener * >::move(), OwnedArray< MidiBuffer >::operator[](), Array< Button::Listener * >::operator[](), ReferenceCountedArray< AudioProcessorGraph::Node >::remove(), OwnedArray< MidiBuffer >::remove(), Array< Button::Listener * >::remove(), ReferenceCountedArray< AudioProcessorGraph::Node >::removeAndReturn(), OwnedArray< MidiBuffer >::removeAndReturn(), Array< Button::Listener * >::removeAndReturn(), AudioBuffer< float >::reverse(), Array< Button::Listener * >::set(), AudioBuffer< float >::setSample(), Array< Button::Listener * >::setUnchecked(), ReferenceCountedArray< AudioProcessorGraph::Node >::swap(), OwnedArray< MidiBuffer >::swap(), and Array< Button::Listener * >::swap().
template<> bool isPositiveAndBelow (const int valueToTest, const int upperLimit) noexcept
References jassert.
template<typename Type > bool isPositiveAndNotGreaterThan (Type valueToTest, Type upperLimit) noexcept
Returns true if a value is at least zero, and also less than or equal to a specified upper limit.
This is basically a quicker way to write:
valueToTest >= 0 && valueToTest <= upperLimit
References jassert.
template<> bool isPositiveAndNotGreaterThan (const int valueToTest, const int upperLimit) noexcept
References jassert.
template<typename Type > void swapVariables (Type & variable1, Type & variable2)
Handy function to swap two values.
template<typename Type1 > void ignoreUnused (const Type1 &) noexcept
Handy function for avoiding unused variables warning.
Referenced by OwnedArray< MidiBuffer >::addSorted(), StandalonePluginHolder::askUserToLoadState(), StandalonePluginHolder::askUserToSaveState(), AudioProcessor::canAddBus(), AudioProcessor::canRemoveBus(), UndoableAction::createCoalescedAction(), ContainerDeletePolicy< ObjectType >::destroy(), MidiInputCallback::handlePartialSysexMessage(), ReferenceCountedArray< AudioProcessorGraph::Node >::indexOfSorted(), OwnedArray< MidiBuffer >::indexOfSorted(), Array< Button::Listener * >::indexOfSorted(), numElementsInArray(), PositionableAudioSource::setLooping(), ReferenceCountedArray< AudioProcessorGraph::Node >::sort(), OwnedArray< MidiBuffer >::sort(), Array< Button::Listener * >::sort(), AudioPlayHead::transportPlay(), and AudioPlayHead::transportRecord().
template<typename Type1 , typename Type2 > void ignoreUnused (const Type1 & , const Type2 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 > void ignoreUnused (const Type1 & , const Type2 & , const Type3 &) noexcept
template<typename Type1 , typename Type2 , typename Type3 , typename Type4 > void ignoreUnused (const Type1 & , const Type2 & , const Type3 & , const Type4 &) noexcept
template<typename Type , int N> int numElementsInArray (Type(&) array[N])
Handy function for getting the number of elements in a simple const C array.
E.g.
static int myArray[] = { 1, 2, 3 };
int numElements = numElementsInArray (myArray) // returns 3
References ignoreUnused().
template<typename Type > Type juce_hypot (Type a, Type b) noexcept
Using juce_hypot is easier than dealing with the different types of hypot function that are provided by the various platforms and compilers.
Referenced by Point< int >::getDistanceFrom(), Point< int >::getDistanceFromOrigin(), and Line< ValueType >::getPointAlongLine().
int64 abs64 (const int64 n) noexcept
64-bit abs function.
float degreesToRadians (float degrees) noexcept
Converts an angle in degrees to radians.
double degreesToRadians (double degrees) noexcept
Converts an angle in degrees to radians.
float radiansToDegrees (float radians) noexcept
Converts an angle in radians to degrees.
References float_Pi.
double radiansToDegrees (double radians) noexcept
Converts an angle in radians to degrees.
References double_Pi.
template<typename NumericType > bool juce_isfinite (NumericType) noexcept
The isfinite() method seems to vary between platforms, so this is a platform-independent function for it.
Referenced by StatisticsAccumulator< FloatType >::addValue(), Point< int >::isFinite(), and Rectangle< int >::isFinite().
template<> bool juce_isfinite (float value) noexcept
template<> bool juce_isfinite (double value) noexcept
template<typename FloatType > int roundToInt (const FloatType value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
Referenced by AudioParameterInt::get(), AudioParameterChoice::getIndex(), roundDoubleToInt(), roundFloatToInt(), Point< int >::roundToInt(), roundToIntAccurate(), and Rectangle< int >::toNearestInt().
int roundToInt (int value) noexcept
int roundToIntAccurate (double value) noexcept
Fast floating-point-to-integer conversion.
This is a slightly slower and slightly more accurate version of roundDoubleToInt(). It works fine for values above zero, but negative numbers are rounded the wrong way.
References roundToInt().
int roundDoubleToInt (double value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a double to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently. For a more accurate conversion, see roundDoubleToIntAccurate().
References roundToInt().
int roundFloatToInt (float value) noexcept
Fast floating-point-to-integer conversion.
This is faster than using the normal c++ cast to convert a float to an int, and it will round the value to the nearest integer, rather than rounding it down like the normal cast does.
Note that this routine gets its speed at the expense of some accuracy, and when rounding values whose floating point component is exactly 0.5, odd numbers and even numbers will be rounded up or down differently.
References roundToInt().
template<typename IntegerType > bool isPowerOfTwo (IntegerType value)
Returns true if the specified integer is a power-of-two.
int nextPowerOfTwo (int n) noexcept
Returns the smallest power-of-two which is equal to or greater than the given integer.
int findHighestSetBit (uint32 n) noexcept
Returns the index of the highest set bit in a (non-zero) number.
So for n=3 this would return 1, for n=7 it returns 2, etc. An input value of 0 is illegal!
int countNumberOfBits (uint32 n) noexcept
Returns the number of bits in a 32-bit integer.
Referenced by countNumberOfBits().
int countNumberOfBits (uint64 n) noexcept
Returns the number of bits in a 64-bit integer.
References countNumberOfBits().
template<typename IntegerType > IntegerType negativeAwareModulo (IntegerType dividend, const IntegerType divisor) noexcept
Performs a modulo operation, but can cope with the dividend being negative.
The divisor must be greater than zero.
References jassert.
template<typename NumericType > NumericType square (NumericType n) noexcept
Returns the square of its argument.
void writeLittleEndianBitsInBuffer (void * targetBuffer, uint32 startBit, uint32 numBits, uint32 value) noexcept
Writes a number of bits into a memory buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the value would be written into bits 2-8 of targetBuffer[1], and the upper 5 bits of value into bits 0-5 of targetBuffer[2].
See Also
readLittleEndianBitsInBuffer
Referenced by littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBits().
uint32 readLittleEndianBitsInBuffer (const void * sourceBuffer, uint32 startBit, uint32 numBits) noexcept
Reads a number of bits from a buffer at a given bit index.
The buffer is treated as a sequence of 8-bit bytes, and the value is encoded in little-endian order, so for example if startBit = 10, and numBits = 11 then the lower 6 bits of the result would be read from bits 2-8 of sourceBuffer[1], and the upper 5 bits of the result from bits 0-5 of sourceBuffer[2].
See Also
writeLittleEndianBitsInBuffer
Referenced by littlefoot::Runner< programAndHeapSpace, stackAndGlobalsSpace >::getHeapBits(), and littlefoot::LittleFootRemoteHeap< ImplementationClass >::setBits().
Variable Documentation
const double double_Pi = 3.1415926535897932384626433832795
A predefined value for Pi, at double-precision.
See Also
float_Pi
Referenced by radiansToDegrees().
const float float_Pi = 3.14159265358979323846f
A predefined value for Pi, at single-precision.
See Also
double_Pi
Referenced by radiansToDegrees().