JUCE: VST3BufferExchange Namespace Reference
VST3BufferExchange Namespace Reference
Typedefs
typedef Array< float * > Bus
typedef Array< Bus > BusMap
Functions
void associateBufferTo (Steinberg::Vst::AudioBusBuffers &vstBuffers, Bus &bus, AudioSampleBuffer &buffer, int numChannels, int channelStartOffset, int sampleOffset=0)
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
void mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const Array< Steinberg::Vst::SpeakerArrangement > &arrangements, AudioSampleBuffer &source)
void mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > &result, Steinberg::Vst::IAudioProcessor &processor, BusMap &busMapToUse, bool isInput, int numBusses, AudioSampleBuffer &source)
Typedef Documentation
typedef Array<float*> VST3BufferExchange::Bus
typedef Array<Bus> VST3BufferExchange::BusMap
Function Documentation
void VST3BufferExchange::associateBufferTo (Steinberg::Vst::AudioBusBuffers & vstBuffers, Bus & bus, AudioSampleBuffer & buffer, int numChannels, int channelStartOffset, int sampleOffset = 0)
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
Warning
For speed, does not check the channel count and offsets according to the AudioSampleBuffer
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::clearQuick(), AudioSampleBuffer::getNumChannels(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getRawDataPointer(), AudioSampleBuffer::getWritePointer(), and jassert.
void VST3BufferExchange::mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const Array< Steinberg::Vst::SpeakerArrangement > & arrangements, AudioSampleBuffer & source)
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getUnchecked(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
void VST3BufferExchange::mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > & result, Steinberg::Vst::IAudioProcessor & processor, BusMap & busMapToUse, bool isInput, int numBusses, AudioSampleBuffer & source)