JUCE: HostPacketDecoder< Handler > Struct Template Reference
HostPacketDecoder< Handler > Struct Template Reference
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Static Public Member Functions
static void processNextPacket (Handler &handler, TopologyIndex deviceIndex, const void *data, int size)
static bool processNextMessage (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp)
static bool handleTopology (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyDevice (Handler &handler, Packed7BitArrayReader &reader)
static void handleTopologyConnection (Handler &handler, Packed7BitArrayReader &reader)
static bool handleTouch (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static bool handleTouchWithVelocity (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd)
static void handleTouch (Handler &handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd)
static bool handleButtonDownOrUp (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown)
static bool handlePacketACK (Handler &handler, Packed7BitArrayReader &reader, TopologyIndex deviceIndex)
Detailed Description
template<typename Handler>
struct HostPacketDecoder< Handler >
Parses data packets from a BLOCKS device, and translates them into callbacks on a handler object.
Member Function Documentation
template<typename Handler > static void HostPacketDecoder< Handler >::processNextPacket (Handler & handler, TopologyIndex deviceIndex, const void * data, int size) static
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayReader::checksumIsOK(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, HostPacketDecoder< Handler >::processNextMessage(), and Packed7BitArrayReader::read().
template<typename Handler > static bool HostPacketDecoder< Handler >::processNextMessage (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp) static
References IntegerWithBitSize< numBits >::bits, controlButtonDown, controlButtonUp, deviceTopology, Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), jassertfalse, packetACK, Packed7BitArrayReader::read(), touchEnd, touchEndWithVelocity, touchMove, touchMoveWithVelocity, touchStart, and touchStartWithVelocity.
Referenced by HostPacketDecoder< Handler >::processNextPacket().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTopology (Handler & handler, Packed7BitArrayReader & reader) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), jassertfalse, Packed7BitArrayReader::read(), topologyConnectionInfo, and topologyDeviceInfo.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTopologyDevice (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceStatus::batteryCharging, DeviceStatus::batteryLevel, DeviceStatus::index, Packed7BitArrayReader::read(), Packed7BitArrayReader::readBits(), BlockSerialNumber::serial, and DeviceStatus::serialNumber.
Referenced by HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTopologyConnection (Handler & handler, Packed7BitArrayReader & reader) static
References DeviceConnection::device1, DeviceConnection::device2, DeviceConnection::port1, DeviceConnection::port2, Packed7BitArrayReader::read(), and Packed7BitArrayReader::readBits().
Referenced by HostPacketDecoder< Handler >::handleTopology().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTouch (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, Packed7BitArrayReader::read(), and touchMessage.
Referenced by HostPacketDecoder< Handler >::handleTouchWithVelocity(), and HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handleTouchWithVelocity (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isStart, bool isEnd) static
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), HostPacketDecoder< Handler >::handleTouch(), jassertfalse, Packed7BitArrayReader::read(), and touchMessageWithVelocity.
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static void HostPacketDecoder< Handler >::handleTouch (Handler & handler, TopologyIndex deviceIndex, uint32 timestamp, TouchIndex touchIndex, TouchPosition position, TouchVelocity velocity, bool isStart, bool isEnd) static
template<typename Handler > static bool HostPacketDecoder< Handler >::handleButtonDownOrUp (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex, PacketTimestamp packetTimestamp, bool isDown) static
References IntegerWithBitSize< numBits >::bits, controlButtonMessage, IntegerWithBitSize< numBits >::get(), Packed7BitArrayReader::getRemainingBits(), jassertfalse, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
template<typename Handler > static bool HostPacketDecoder< Handler >::handlePacketACK (Handler & handler, Packed7BitArrayReader & reader, TopologyIndex deviceIndex) static
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayReader::getRemainingBits(), jassertfalse, packetACK, and Packed7BitArrayReader::read().
Referenced by HostPacketDecoder< Handler >::processNextMessage().
The documentation for this struct was generated from the following file:
juce_HostPacketDecoder.h