JUCE: VSTCallbackHandler Struct Reference
VSTCallbackHandler Struct Reference abstract
juce_audio_plugin_client » VST
An interface to allow an AudioProcessor to send and receive VST specific calls from the host.
Public Types
typedef pointer_sized_int() VstHostCallbackType(int32 opcode, int32 index, pointer_sized_int value, void *ptr, float opt)
The host callback function type.
Public Member Functions
virtual ~VSTCallbackHandler ()=default
virtual pointer_sized_int handleVstPluginCanDo (int32 index, pointer_sized_int value, void *ptr, float opt)
This is called by the VST plug-in wrapper when it receives unhandled plug-in "can do" calls from the host.
virtual pointer_sized_int handleVstManufacturerSpecific (int32 index, pointer_sized_int value, void *ptr, float opt)=0
This is called by the VST plug-in wrapper when it receives unhandled vendor specific calls from the host.
virtual void handleVstHostCallbackAvailable (std::function< VstHostCallbackType > &&callback)
This is called once by the VST plug-in wrapper after its constructor.
Detailed Description
An interface to allow an AudioProcessor to send and receive VST specific calls from the host.
Member Typedef Documentation
VstHostCallbackType
typedef pointer_sized_int() VSTCallbackHandler::VstHostCallbackType(int32 opcode, int32 index, pointer_sized_int value, void *ptr, float opt)
The host callback function type.
Constructor & Destructor Documentation
~VSTCallbackHandler()
virtual VSTCallbackHandler::~VSTCallbackHandler () virtual default
Member Function Documentation
handleVstPluginCanDo()
virtual pointer_sized_int VSTCallbackHandler::handleVstPluginCanDo (int32 index, pointer_sized_int value, void * ptr, float opt) virtual
This is called by the VST plug-in wrapper when it receives unhandled plug-in "can do" calls from the host.
References handleVstManufacturerSpecific(), and ignoreUnused().
handleVstManufacturerSpecific()
virtual pointer_sized_int VSTCallbackHandler::handleVstManufacturerSpecific (int32 index, pointer_sized_int value, void * ptr, float opt) pure virtual
This is called by the VST plug-in wrapper when it receives unhandled vendor specific calls from the host.
Referenced by handleVstPluginCanDo().
handleVstHostCallbackAvailable()
virtual void VSTCallbackHandler::handleVstHostCallbackAvailable (std::function< VstHostCallbackType > && callback) virtual
This is called once by the VST plug-in wrapper after its constructor.
You can use the supplied function to query the VST host.
References ignoreUnused().
The documentation for this struct was generated from the following file:
juce_VSTCallbackHandler.h