JUCE: AudioUnitHelpers Struct Reference
AudioUnitHelpers Struct Reference
Classes
struct AUChannelStreamOrder
class ChannelRemapper
class CoreAudioBufferList
struct StreamOrder
Static Public Member Functions
static AudioChannelSet::ChannelType CoreAudioChannelLabelToJuceType (AudioChannelLabel label) noexcept
static AudioChannelLabel JuceChannelTypeToCoreAudioLabel (const AudioChannelSet::ChannelType &label) noexcept
static AudioChannelSet CoreAudioChannelBitmapToJuceType (UInt32 bitmap) noexcept
static AudioChannelSet CoreAudioChannelLayoutToJuceType (const AudioChannelLayout &layout) noexcept
static AudioChannelSet CALayoutTagToChannelSet (AudioChannelLayoutTag tag) noexcept
static AudioChannelLayoutTag ChannelSetToCALayoutTag (const AudioChannelSet &set) noexcept
static int auChannelIndexToJuce (int auIndex, const AudioChannelSet &channelSet)
static int juceChannelIndexToAu (int juceIndex, const AudioChannelSet &channelSet)
static bool isAudioBufferInterleaved (const AudioBufferList &audioBuffer) noexcept
static void clearAudioBuffer (const AudioBufferList &audioBuffer) noexcept
static void copyAudioBuffer (const AudioBufferList &audioBuffer, const int channel, const UInt32 size, float *dst) noexcept
static void copyAudioBuffer (const float *src, const int channel, const UInt32 size, AudioBufferList &audioBuffer) noexcept
template<int numLayouts>
static bool isLayoutSupported (const AudioProcessor &processor, bool isInput, int busIdx, int numChannels, const short(&channelLayoutList)[numLayouts][2], bool hasLayoutMap=true)
static Array< AUChannelInfo > getAUChannelInfo (const AudioProcessor &processor)
static int getBusCount (const AudioProcessor *juceFilter, bool isInput)
static bool setBusesLayout (AudioProcessor *juceFilter, const AudioProcessor::BusesLayout &requestedLayouts)
static AudioProcessor::BusesLayout getBusesLayout (const AudioProcessor *juceFilter)
Member Function Documentation
static AudioChannelSet::ChannelType AudioUnitHelpers::CoreAudioChannelLabelToJuceType (AudioChannelLabel label) static noexcept
References AudioChannelSet::ambisonicW, AudioChannelSet::ambisonicX, AudioChannelSet::ambisonicY, AudioChannelSet::ambisonicZ, AudioChannelSet::centre, AudioChannelSet::discreteChannel0, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::leftSurroundSide, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::rightSurroundSide, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, AudioChannelSet::wideLeft, and AudioChannelSet::wideRight.
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelLabel AudioUnitHelpers::JuceChannelTypeToCoreAudioLabel (const AudioChannelSet::ChannelType & label) static noexcept
References AudioChannelSet::ambisonicW, AudioChannelSet::ambisonicX, AudioChannelSet::ambisonicY, AudioChannelSet::ambisonicZ, AudioChannelSet::centre, AudioChannelSet::discreteChannel0, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::leftSurroundSide, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::rightSurroundSide, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, AudioChannelSet::wideLeft, and AudioChannelSet::wideRight.
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelSet AudioUnitHelpers::CoreAudioChannelBitmapToJuceType (UInt32 bitmap) static noexcept
References AudioChannelSet::addChannel(), AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundSide, AudioChannelSet::LFE, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundSide, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, and AudioChannelSet::topRearRight.
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelSet AudioUnitHelpers::CoreAudioChannelLayoutToJuceType (const AudioChannelLayout & layout) static noexcept
References AudioChannelSet::addChannel(), AudioUnitHelpers::StreamOrder::auChannelStreamOrder, AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, CALayoutTagToChannelSet(), CoreAudioChannelBitmapToJuceType(), CoreAudioChannelLabelToJuceType(), JuceChannelTypeToCoreAudioLabel(), and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
static AudioChannelSet AudioUnitHelpers::CALayoutTagToChannelSet (AudioChannelLayoutTag tag) static noexcept
References AudioChannelSet::ambisonic(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::discreteChannels(), AudioChannelSet::hexagonal(), jassertfalse, AudioChannelSet::mono(), AudioChannelSet::octagonal(), AudioChannelSet::pentagonal(), AudioChannelSet::quadraphonic(), and AudioChannelSet::stereo().
Referenced by CoreAudioChannelLayoutToJuceType().
static AudioChannelLayoutTag AudioUnitHelpers::ChannelSetToCALayoutTag (const AudioChannelSet & set) static noexcept
References AudioChannelSet::ambisonic(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::hexagonal(), AudioChannelSet::mono(), AudioChannelSet::octagonal(), AudioChannelSet::pentagonal(), AudioChannelSet::quadraphonic(), and AudioChannelSet::stereo().
Referenced by auChannelIndexToJuce(), and juceChannelIndexToAu().
static int AudioUnitHelpers::auChannelIndexToJuce (int auIndex, const AudioChannelSet & channelSet) static
References AudioUnitHelpers::StreamOrder::auChannelStreamOrder, AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, ChannelSetToCALayoutTag(), AudioChannelSet::getChannelTypes(), jassert, and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
static int AudioUnitHelpers::juceChannelIndexToAu (int juceIndex, const AudioChannelSet & channelSet) static
References AudioUnitHelpers::StreamOrder::auChannelStreamOrder, AudioUnitHelpers::AUChannelStreamOrder::auLayoutTag, ChannelSetToCALayoutTag(), AudioChannelSet::getTypeOfChannel(), AudioChannelSet::isDiscreteLayout(), jassertfalse, and AudioUnitHelpers::AUChannelStreamOrder::speakerOrder.
static bool AudioUnitHelpers::isAudioBufferInterleaved (const AudioBufferList & audioBuffer) static noexcept
Referenced by copyAudioBuffer(), AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::clearAudioBuffer (const AudioBufferList & audioBuffer) static noexcept
References zeromem().
static void AudioUnitHelpers::copyAudioBuffer (const AudioBufferList & audioBuffer, const int channel, const UInt32 size, float * dst) static noexcept
References isAudioBufferInterleaved(), and jassert.
Referenced by AudioUnitHelpers::CoreAudioBufferList::pop(), and AudioUnitHelpers::CoreAudioBufferList::push().
static void AudioUnitHelpers::copyAudioBuffer (const float * src, const int channel, const UInt32 size, AudioBufferList & audioBuffer) static noexcept
References isAudioBufferInterleaved(), and jassert.
template<int numLayouts> static bool AudioUnitHelpers::isLayoutSupported (const AudioProcessor & processor, bool isInput, int busIdx, int numChannels, const short(&) channelLayoutList[numLayouts][2], bool hasLayoutMap = true) static
References AudioProcessor::getBus().
static Array<AUChannelInfo> AudioUnitHelpers::getAUChannelInfo (const AudioProcessor & processor) static
References SortedSet< ElementType, TypeOfCriticalSectionToUse >::add(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), SortedSet< ElementType, TypeOfCriticalSectionToUse >::contains(), AudioProcessor::getBus(), getBusCount(), AudioProcessor::Bus::getBusesLayoutForLayoutChangeOfBus(), AudioProcessor::getChannelCountOfBus(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::getReference(), AudioProcessor::BusesLayout::inputBuses, AudioProcessor::Bus::isNumberOfChannelsSupported(), AudioProcessor::BusesLayout::outputBuses, SortedSet< ElementType, TypeOfCriticalSectionToUse >::size(), Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size(), AudioChannelSet::size(), and AudioProcessor::Bus::supportedLayoutWithChannels().
static int AudioUnitHelpers::getBusCount (const AudioProcessor * juceFilter, bool isInput) static
References AudioProcessor::getBusCount(), and jmin().
Referenced by AudioUnitHelpers::ChannelRemapper::alloc(), getAUChannelInfo(), getBusesLayout(), and setBusesLayout().
static bool AudioUnitHelpers::setBusesLayout (AudioProcessor * juceFilter, const AudioProcessor::BusesLayout & requestedLayouts) static
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::add(), StandardApplicationCommandIDs::copy, AudioChannelSet::disabled(), AudioProcessor::getBusCount(), getBusCount(), AudioProcessor::BusesLayout::inputBuses, AudioProcessor::BusesLayout::outputBuses, and AudioProcessor::setBusesLayout().
static AudioProcessor::BusesLayout AudioUnitHelpers::getBusesLayout (const AudioProcessor * juceFilter) static
References AudioProcessor::getBusCount(), getBusCount(), AudioProcessor::getBusesLayout(), AudioProcessor::BusesLayout::inputBuses, AudioProcessor::BusesLayout::outputBuses, and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::removeLast().
The documentation for this struct was generated from the following file:
juce_AU_Shared.h