JUCE: dsp::WaveShaper< FloatType, Function > Struct Template Reference
dsp::WaveShaper< FloatType, Function > Struct Template Reference
juce_dsp » processors
Applies waveshaping to audio samples as single samples or AudioBlocks.
Public Member Functions
void prepare (const ProcessSpec &) noexcept
Called before processing starts.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) const noexcept
Processes the input and output buffers supplied in the processing context.
void reset () noexcept
Public Attributes
Function functionToUse
Detailed Description
template<typename FloatType, typename Function = FloatType (*) (FloatType)>
struct dsp::WaveShaper< FloatType, Function >
Applies waveshaping to audio samples as single samples or AudioBlocks.
Member Function Documentation
prepare()
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void dsp::WaveShaper< FloatType, Function >::prepare (const ProcessSpec &) noexcept
Called before processing starts.
processSample()
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE dsp::WaveShaper< FloatType, Function >::processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
References dsp::WaveShaper< FloatType, Function >::functionToUse.
process()
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename ProcessContext > void dsp::WaveShaper< FloatType, Function >::process (const ProcessContext & context) const noexcept
Processes the input and output buffers supplied in the processing context.
References dsp::WaveShaper< FloatType, Function >::functionToUse, and dsp::AudioBlock< SampleType >::process().
reset()
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void dsp::WaveShaper< FloatType, Function >::reset () noexcept
References dsp::WaveShaper< FloatType, Function >::functionToUse.
Member Data Documentation
functionToUse
template<typename FloatType , typename Function = FloatType (*) (FloatType)> Function dsp::WaveShaper< FloatType, Function >::functionToUse
Referenced by dsp::WaveShaper< FloatType, Function >::process(), dsp::WaveShaper< FloatType, Function >::processSample(), and dsp::WaveShaper< FloatType, Function >::reset().
The documentation for this struct was generated from the following file:
juce_WaveShaper.h