JUCE: WaveShaper< FloatType, Function > Struct Template Reference
WaveShaper< FloatType, Function > Struct Template Reference
Applies waveshaping to audio samples as single samples or AudioBlocks.
Public Member Functions
void prepare (const ProcessSpec &) noexcept
Called before processing starts.
template<typename SampleType >
SampleType JUCE_VECTOR_CALLTYPE processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
template<typename ProcessContext >
void process (const ProcessContext &context) const noexcept
Processes the input and output buffers supplied in the processing context.
void reset () noexcept
Public Attributes
Function functionToUse
Detailed Description
template<typename FloatType, typename Function = FloatType (*) (FloatType)>
struct WaveShaper< FloatType, Function >
Applies waveshaping to audio samples as single samples or AudioBlocks.
Member Function Documentation
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void WaveShaper< FloatType, Function >::prepare (const ProcessSpec &) noexcept
Called before processing starts.
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename SampleType > SampleType JUCE_VECTOR_CALLTYPE WaveShaper< FloatType, Function >::processSample (SampleType inputSample) const noexcept
Returns the result of processing a single sample.
References WaveShaper< FloatType, Function >::functionToUse.
template<typename FloatType , typename Function = FloatType (*) (FloatType)> template<typename ProcessContext > void WaveShaper< FloatType, Function >::process (const ProcessContext & context) const noexcept
Processes the input and output buffers supplied in the processing context.
References WaveShaper< FloatType, Function >::functionToUse, jassert, and AudioBlock< SampleType >::process().
template<typename FloatType , typename Function = FloatType (*) (FloatType)> void WaveShaper< FloatType, Function >::reset () noexcept
Member Data Documentation
template<typename FloatType , typename Function = FloatType (*) (FloatType)> Function WaveShaper< FloatType, Function >::functionToUse
Referenced by WaveShaper< FloatType, Function >::process(), and WaveShaper< FloatType, Function >::processSample().
The documentation for this struct was generated from the following file:
juce_WaveShaper.h