JUCE: Packed7BitArrayReader Struct Reference
Packed7BitArrayReader Struct Reference
This helper class reads from a block of 7-bit bytes as sequences of bits.
Public Member Functions
Packed7BitArrayReader (const void *sourceData, int numBytes) noexcept
int getRemainingBits () const noexcept
template<typename Target >
Target read () noexcept
uint32 readBits (int numBits) noexcept
Static Public Member Functions
static bool checksumIsOK (const uint8 *data, uint32 size) noexcept
Detailed Description
This helper class reads from a block of 7-bit bytes as sequences of bits.
See Also
Packed7BitArrayBuilder
Constructor & Destructor Documentation
Packed7BitArrayReader::Packed7BitArrayReader (const void * sourceData, int numBytes) noexcept
Member Function Documentation
int Packed7BitArrayReader::getRemainingBits () const noexcept
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), HostPacketDecoder< Handler >::handleLogMessage(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), HostPacketDecoder< Handler >::processNextMessage(), HostPacketDecoder< Handler >::processNextPacket(), and readBits().
template<typename Target > Target Packed7BitArrayReader::read () noexcept
References readBits().
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleConfigMessage(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleFirmwareUpdateACK(), HostPacketDecoder< Handler >::handleLogMessage(), HostPacketDecoder< Handler >::handlePacketACK(), HostPacketDecoder< Handler >::handleTopology(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), HostPacketDecoder< Handler >::handleTopologyEnd(), HostPacketDecoder< Handler >::handleTouch(), HostPacketDecoder< Handler >::handleTouchWithVelocity(), HostPacketDecoder< Handler >::processNextMessage(), and HostPacketDecoder< Handler >::processNextPacket().
uint32 Packed7BitArrayReader::readBits (int numBits) noexcept
References getRemainingBits(), and jassert.
Referenced by HostPacketDecoder< Handler >::handleName(), HostPacketDecoder< Handler >::handleTopologyConnection(), HostPacketDecoder< Handler >::handleTopologyDevice(), HostPacketDecoder< Handler >::handleVersion(), and read().
static bool Packed7BitArrayReader::checksumIsOK (const uint8 * data, uint32 size) static noexcept
Referenced by HostPacketDecoder< Handler >::processNextPacket().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h