JUCE: VST3BufferExchange< FloatType > Struct Template Reference
VST3BufferExchange< FloatType > Struct Template Reference
Public Types
typedef Array< FloatType * > Bus
typedef Array< Bus > BusMap
Static Public Member Functions
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, float **raw)
static void assignRawPointer (Steinberg::Vst::AudioBusBuffers &vstBuffers, double **raw)
static void associateBufferTo (Steinberg::Vst::AudioBusBuffers &vstBuffers, Bus &bus, AudioBuffer< FloatType > &buffer, int numChannels, int channelStartOffset, int sampleOffset=0)
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
static void mapArrangementToBusses (int &channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, Steinberg::Vst::SpeakerArrangement arrangement, AudioBuffer< FloatType > &source)
static void mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > &result, BusMap &busMapToUse, const Array< Steinberg::Vst::SpeakerArrangement > &arrangements, AudioBuffer< FloatType > &source)
static void mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > &result, Steinberg::Vst::IAudioProcessor &processor, BusMap &busMapToUse, bool isInput, int numBusses, AudioBuffer< FloatType > &source)
Member Typedef Documentation
template<typename FloatType> typedef Array<FloatType*> VST3BufferExchange< FloatType >::Bus
template<typename FloatType> typedef Array<Bus> VST3BufferExchange< FloatType >::BusMap
Member Function Documentation
template<typename FloatType> static void VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, float ** raw) static
Referenced by VST3BufferExchange< float >::associateBufferTo().
template<typename FloatType> static void VST3BufferExchange< FloatType >::assignRawPointer (Steinberg::Vst::AudioBusBuffers & vstBuffers, double ** raw) static
template<typename FloatType> static void VST3BufferExchange< FloatType >::associateBufferTo (Steinberg::Vst::AudioBusBuffers & vstBuffers, Bus & bus, AudioBuffer< FloatType > & buffer, int numChannels, int channelStartOffset, int sampleOffset = 0) static
Assigns a series of AudioSampleBuffer's channels to an AudioBusBuffers'.
Warning
For speed, does not check the channel count and offsets according to the AudioSampleBuffer
Referenced by VST3BufferExchange< float >::mapArrangementToBusses().
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapArrangementToBusses (int & channelIndexOffset, int index, Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, Steinberg::Vst::SpeakerArrangement arrangement, AudioBuffer< FloatType > & source) static
Referenced by VST3BufferExchange< float >::mapBufferToBusses().
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > & result, BusMap & busMapToUse, const Array< Steinberg::Vst::SpeakerArrangement > & arrangements, AudioBuffer< FloatType > & source) static
template<typename FloatType> static void VST3BufferExchange< FloatType >::mapBufferToBusses (Array< Steinberg::Vst::AudioBusBuffers > & result, Steinberg::Vst::IAudioProcessor & processor, BusMap & busMapToUse, bool isInput, int numBusses, AudioBuffer< FloatType > & source) static
The documentation for this struct was generated from the following file:
juce_VST3Common.h