JUCE: SIMDFallbackOps< ScalarType, vSIMDType > Struct Template Reference
SIMDFallbackOps< ScalarType, vSIMDType > Struct Template Reference
Useful fallback routines to use if the native SIMD op is not supported.
Classes
struct ScalarAdd
struct ScalarAnd
struct ScalarEq
struct ScalarGeq
struct ScalarGt
struct ScalarMax
struct ScalarMin
struct ScalarMul
struct ScalarNeq
struct ScalarNot
struct ScalarOr
struct ScalarSub
struct ScalarXor
Public Types
typedef
SIMDInternal::MaskTypeFor
< ScalarType >::type MaskType
Static Public Member Functions
static forcedinline vSIMDType add (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType sub (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType mul (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType bit_and (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType bit_or (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType bit_xor (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType bit_notand (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType min (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType max (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType equal (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType notEqual (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType greaterThan (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType greaterThanOrEqual (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType bit_not (vSIMDType a) noexcept
static forcedinline ScalarType sum (vSIMDType a) noexcept
static forcedinline vSIMDType multiplyAdd (vSIMDType a, vSIMDType b, vSIMDType c) noexcept
static forcedinline vSIMDType cmplxmul (vSIMDType a, vSIMDType b) noexcept
template<typename Op >
static forcedinline vSIMDType apply (vSIMDType a, vSIMDType b) noexcept
template<typename Op >
static forcedinline vSIMDType cmp (vSIMDType a, vSIMDType b) noexcept
template<typename Op >
static forcedinline vSIMDType bitapply (vSIMDType a, vSIMDType b) noexcept
static forcedinline vSIMDType expand (ScalarType s) noexcept
template<unsigned int shuffle_idx>
static forcedinline vSIMDType shuffle (vSIMDType a) noexcept
Static Public Attributes
static constexpr size_t n = sizeof (vSIMDType) / sizeof (ScalarType)
static constexpr size_t mask = (sizeof (vSIMDType) / sizeof (ScalarType)) - 1
static constexpr size_t bits = SIMDInternal::Log2Helper<n>::value
Detailed Description
template<typename ScalarType, typename vSIMDType>
struct SIMDFallbackOps< ScalarType, vSIMDType >
Useful fallback routines to use if the native SIMD op is not supported.
You should never need to use this directly. Use juce_SIMDRegister instead.
Member Typedef Documentation
template<typename ScalarType , typename vSIMDType > typedef SIMDInternal::MaskTypeFor<ScalarType>::type SIMDFallbackOps< ScalarType, vSIMDType >::MaskType
Member Function Documentation
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::add (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::sub (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::mul (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bit_and (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bit_or (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bit_xor (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bit_notand (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::min (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::max (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::equal (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::notEqual (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::greaterThan (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::greaterThanOrEqual (vSIMDType a, vSIMDType b) static noexcept
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bit_not (vSIMDType a) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > static forcedinline ScalarType SIMDFallbackOps< ScalarType, vSIMDType >::sum (vSIMDType a) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::multiplyAdd (vSIMDType a, vSIMDType b, vSIMDType c) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::cmplxmul (vSIMDType a, vSIMDType b) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > template<typename Op > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::apply (vSIMDType a, vSIMDType b) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > template<typename Op > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::cmp (vSIMDType a, vSIMDType b) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > template<typename Op > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::bitapply (vSIMDType a, vSIMDType b) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::expand (ScalarType s) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::n.
template<typename ScalarType , typename vSIMDType > template<unsigned int shuffle_idx> static forcedinline vSIMDType SIMDFallbackOps< ScalarType, vSIMDType >::shuffle (vSIMDType a) static noexcept
References SIMDFallbackOps< ScalarType, vSIMDType >::bits, SIMDFallbackOps< ScalarType, vSIMDType >::mask, and SIMDFallbackOps< ScalarType, vSIMDType >::n.
Member Data Documentation
template<typename ScalarType , typename vSIMDType > constexpr size_t SIMDFallbackOps< ScalarType, vSIMDType >::n = sizeof (vSIMDType) / sizeof (ScalarType) static
Referenced by SIMDFallbackOps< ScalarType, vSIMDType >::apply(), SIMDFallbackOps< ScalarType, vSIMDType >::bit_not(), SIMDFallbackOps< ScalarType, vSIMDType >::bitapply(), SIMDFallbackOps< ScalarType, vSIMDType >::cmp(), SIMDFallbackOps< ScalarType, vSIMDType >::cmplxmul(), SIMDFallbackOps< ScalarType, vSIMDType >::expand(), SIMDFallbackOps< ScalarType, vSIMDType >::multiplyAdd(), SIMDFallbackOps< ScalarType, vSIMDType >::shuffle(), and SIMDFallbackOps< ScalarType, vSIMDType >::sum().
template<typename ScalarType , typename vSIMDType > constexpr size_t SIMDFallbackOps< ScalarType, vSIMDType >::mask = (sizeof (vSIMDType) / sizeof (ScalarType)) - 1 static
Referenced by SIMDFallbackOps< ScalarType, vSIMDType >::shuffle().
template<typename ScalarType , typename vSIMDType > constexpr size_t SIMDFallbackOps< ScalarType, vSIMDType >::bits = SIMDInternal::Log2Helper<n>::value static
Referenced by SIMDFallbackOps< ScalarType, vSIMDType >::shuffle().
The documentation for this struct was generated from the following file:
juce_fallback_SIMDNativeOps.h