JUCE: ComponentPeer::DragInfo Struct Reference
ComponentPeer::DragInfo Struct Reference
juce_gui_basics » windows
Structure to describe drag and drop information.
Public Member Functions
bool isEmpty () const noexcept
void clear () noexcept
Public Attributes
StringArray files
String text
Point< int > position
Detailed Description
Structure to describe drag and drop information.
Member Function Documentation
isEmpty()
bool ComponentPeer::DragInfo::isEmpty () const noexcept
References String::isEmpty(), and StringArray::size().
clear()
void ComponentPeer::DragInfo::clear () noexcept
References String::clear(), and StringArray::clear().
Member Data Documentation
files
StringArray ComponentPeer::DragInfo::files
text
String ComponentPeer::DragInfo::text
position
Point<int> ComponentPeer::DragInfo::position
The documentation for this struct was generated from the following file:
juce_ComponentPeer.h