JUCE: ContainerDeletePolicy< ObjectType > Struct Template Reference
ContainerDeletePolicy< ObjectType > Struct Template Reference
Used by container classes as an indirect way to delete an object of a particular type.
Static Public Member Functions
static void destroy (ObjectType *object)
Detailed Description
template<typename ObjectType>
struct ContainerDeletePolicy< ObjectType >
Used by container classes as an indirect way to delete an object of a particular type.
The generic implementation of this class simply calls 'delete', but you can create a specialised version of it for a particular class if you need to delete that type of object in a more appropriate way.
See Also
ScopedPointer, OwnedArray
Member Function Documentation
template<typename ObjectType > static void ContainerDeletePolicy< ObjectType >::destroy (ObjectType * object) static
References ignoreUnused().
Referenced by ScopedPointer< ListViewport >::operator=(), OwnedArray< MidiBuffer >::removeRange(), and ScopedPointer< ListViewport >::~ScopedPointer().
The documentation for this struct was generated from the following file:
juce_ContainerDeletePolicy.h