JUCE: FastMathApproximations Struct Reference
FastMathApproximations Struct Reference
This class contains various fast mathematical function approximations.
Static Public Member Functions
template<typename FloatType >
static FloatType cosh (FloatType x) noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void cosh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType sinh (FloatType x) noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void sinh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType tanh (FloatType x) noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void tanh (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType cos (FloatType x) noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void cos (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType sin (FloatType x) noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void sin (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType tan (FloatType x) noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void tan (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType exp (FloatType x) noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void exp (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated on a whole buffer.
template<typename FloatType >
static FloatType logNPlusOne (FloatType x) noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated sample by sample.
template<typename FloatType >
static void logNPlusOne (FloatType *values, size_t numValues) noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated on a whole buffer.
Detailed Description
This class contains various fast mathematical function approximations.
Member Function Documentation
template<typename FloatType > static FloatType FastMathApproximations::cosh (FloatType x) static noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by cosh().
template<typename FloatType > static void FastMathApproximations::cosh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function cosh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References cosh().
template<typename FloatType > static FloatType FastMathApproximations::sinh (FloatType x) static noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by sinh().
template<typename FloatType > static void FastMathApproximations::sinh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function sinh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References sinh().
template<typename FloatType > static FloatType FastMathApproximations::tanh (FloatType x) static noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
Referenced by tanh().
template<typename FloatType > static void FastMathApproximations::tanh (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function tanh(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -5 and +5 for limiting the error.
References tanh().
template<typename FloatType > static FloatType FastMathApproximations::cos (FloatType x) static noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
Referenced by cos().
template<typename FloatType > static void FastMathApproximations::cos (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function cos(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
References cos().
template<typename FloatType > static FloatType FastMathApproximations::sin (FloatType x) static noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
Referenced by sin().
template<typename FloatType > static void FastMathApproximations::sin (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function sin(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi and +pi for limiting the error.
References sin().
template<typename FloatType > static FloatType FastMathApproximations::tan (FloatType x) static noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi/2 and +pi/2 for limiting the error.
Referenced by tan().
template<typename FloatType > static void FastMathApproximations::tan (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function tan(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -pi/2 and +pi/2 for limiting the error.
References tan().
template<typename FloatType > static FloatType FastMathApproximations::exp (FloatType x) static noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -6 and +4 for limiting the error.
Referenced by exp().
template<typename FloatType > static void FastMathApproximations::exp (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function exp(x) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -6 and +4 for limiting the error.
References exp().
template<typename FloatType > static FloatType FastMathApproximations::logNPlusOne (FloatType x) static noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated sample by sample.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -0.8 and +5 for limiting the error.
Referenced by logNPlusOne().
template<typename FloatType > static void FastMathApproximations::logNPlusOne (FloatType * values, size_t numValues) static noexcept
Provides a fast approximation of the function log(x+1) using a Pade approximant continued fraction, calculated on a whole buffer.
Note : this is an approximation which works on a limited range. You are advised to use input values only between -0.8 and +5 for limiting the error.
References logNPlusOne().
The documentation for this struct was generated from the following file:
juce_FastMathApproximations.h