JUCE: SpeakerMappings Struct Reference
SpeakerMappings Struct Reference
Classes
struct Mapping
Static Public Member Functions
static AudioChannelSet vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels)
static AudioChannelSet vstArrangementTypeToChannelSet (const VstSpeakerConfiguration &arr)
static int32 channelSetToVstArrangementType (AudioChannelSet channels)
static void channelSetToVstArrangement (const AudioChannelSet &channels, VstSpeakerConfiguration &result)
static const Mapping * getMappings () noexcept
static int32 getSpeakerType (AudioChannelSet::ChannelType type) noexcept
static AudioChannelSet::ChannelType getChannelType (int32 type) noexcept
Member Function Documentation
static AudioChannelSet SpeakerMappings::vstArrangementTypeToChannelSet (int32 arr, int fallbackNumChannels) static
References AudioChannelSet::addChannel(), AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::discreteChannels(), getMappings(), AudioChannelSet::mono(), AudioChannelSet::quadraphonic(), AudioChannelSet::stereo(), SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, and vstSpeakerConfigTypeMono.
Referenced by vstArrangementTypeToChannelSet().
static AudioChannelSet SpeakerMappings::vstArrangementTypeToChannelSet (const VstSpeakerConfiguration & arr) static
References VstSpeakerConfiguration::numberOfChannels, VstSpeakerConfiguration::type, and vstArrangementTypeToChannelSet().
static int32 SpeakerMappings::channelSetToVstArrangementType (AudioChannelSet channels) static
References AudioChannelSet::create5point0(), AudioChannelSet::create5point1(), AudioChannelSet::create6point0(), AudioChannelSet::create6point0Music(), AudioChannelSet::create6point1(), AudioChannelSet::create6point1Music(), AudioChannelSet::create7point0(), AudioChannelSet::create7point0SDDS(), AudioChannelSet::create7point1(), AudioChannelSet::create7point1SDDS(), AudioChannelSet::createLCR(), AudioChannelSet::createLCRS(), AudioChannelSet::createLRS(), AudioChannelSet::disabled(), AudioChannelSet::getChannelTypes(), getMappings(), AudioChannelSet::mono(), AudioChannelSet::quadraphonic(), AudioChannelSet::stereo(), SpeakerMappings::Mapping::vst2, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeUser.
Referenced by channelSetToVstArrangement().
static void SpeakerMappings::channelSetToVstArrangement (const AudioChannelSet & channels, VstSpeakerConfiguration & result) static
References channelSetToVstArrangementType(), getSpeakerType(), AudioChannelSet::getTypeOfChannel(), VstSpeakerConfiguration::numberOfChannels, AudioChannelSet::size(), VstSpeakerConfiguration::speakers, VstIndividualSpeakerInfo::type, VstSpeakerConfiguration::type, and zeromem().
static const Mapping* SpeakerMappings::getMappings () static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, vstSpeakerConfigTypeCLfe, vstSpeakerConfigTypeEmpty, vstSpeakerConfigTypeLcRc, vstSpeakerConfigTypeLR, vstSpeakerConfigTypeLRC, vstSpeakerConfigTypeLRCLfe, vstSpeakerConfigTypeLRCLfeLsRs, vstSpeakerConfigTypeLRCLfeLsRsCs, vstSpeakerConfigTypeLRCLfeLsRsCsSlSr, vstSpeakerConfigTypeLRCLfeLsRsLcRc, vstSpeakerConfigTypeLRCLfeLsRsLcRcCs, vstSpeakerConfigTypeLRCLfeLsRsSlSr, vstSpeakerConfigTypeLRCLfeLsRsTflTfcTfrTrlTrrLfe2, vstSpeakerConfigTypeLRCLfeS, vstSpeakerConfigTypeLRCLsRs, vstSpeakerConfigTypeLRCLsRsCs, vstSpeakerConfigTypeLRCLsRsCsSlSr, vstSpeakerConfigTypeLRCLsRsLcRc, vstSpeakerConfigTypeLRCLsRsLcRcCs, vstSpeakerConfigTypeLRCLsRsSlSr, vstSpeakerConfigTypeLRCS, vstSpeakerConfigTypeLRLfeLsRs, vstSpeakerConfigTypeLRLfeLsRsSlSr, vstSpeakerConfigTypeLRLfeS, vstSpeakerConfigTypeLRLsRs, vstSpeakerConfigTypeLRLsRsSlSr, vstSpeakerConfigTypeLRS, vstSpeakerConfigTypeLsRs, vstSpeakerConfigTypeMono, and vstSpeakerConfigTypeSlSr.
Referenced by channelSetToVstArrangementType(), and vstArrangementTypeToChannelSet().
static int32 SpeakerMappings::getSpeakerType (AudioChannelSet::ChannelType type) static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
Referenced by channelSetToVstArrangement().
static AudioChannelSet::ChannelType SpeakerMappings::getChannelType (int32 type) static noexcept
References AudioChannelSet::centre, AudioChannelSet::left, AudioChannelSet::leftCentre, AudioChannelSet::leftSurround, AudioChannelSet::leftSurroundRear, AudioChannelSet::LFE, AudioChannelSet::LFE2, AudioChannelSet::right, AudioChannelSet::rightCentre, AudioChannelSet::rightSurround, AudioChannelSet::rightSurroundRear, AudioChannelSet::surround, AudioChannelSet::topFrontCentre, AudioChannelSet::topFrontLeft, AudioChannelSet::topFrontRight, AudioChannelSet::topMiddle, AudioChannelSet::topRearCentre, AudioChannelSet::topRearLeft, AudioChannelSet::topRearRight, AudioChannelSet::unknown, vstIndividualSpeakerTypeCentre, vstIndividualSpeakerTypeLeft, vstIndividualSpeakerTypeLeftCentre, vstIndividualSpeakerTypeLeftRearSurround, vstIndividualSpeakerTypeLeftSurround, vstIndividualSpeakerTypeLFE, vstIndividualSpeakerTypeLFE2, vstIndividualSpeakerTypeRight, vstIndividualSpeakerTypeRightCentre, vstIndividualSpeakerTypeRightRearSurround, vstIndividualSpeakerTypeRightSurround, vstIndividualSpeakerTypeSurround, vstIndividualSpeakerTypeTopFrontCentre, vstIndividualSpeakerTypeTopFrontLeft, vstIndividualSpeakerTypeTopFrontRight, vstIndividualSpeakerTypeTopMiddle, vstIndividualSpeakerTypeTopRearCentre, vstIndividualSpeakerTypeTopRearLeft, and vstIndividualSpeakerTypeTopRearRight.
The documentation for this struct was generated from the following file:
juce_VSTCommon.h