JUCE: Packed7BitArrayBuilder< allocatedBytes > Struct Template Reference
Packed7BitArrayBuilder< allocatedBytes > Struct Template Reference
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
Classes
struct State
Public Member Functions
const void * getData () const noexcept
int size () const noexcept
bool hasCapacity (int bitsNeeded) const noexcept
void writeHeaderSysexBytes (uint8 deviceIndex) noexcept
void writePacketSysexFooter () noexcept
template<int numBits>
Packed7BitArrayBuilder & operator<< (IntegerWithBitSize< numBits > value) noexcept
void writeBits (uint32 value, int numBits) noexcept
State getState () const noexcept
void restore (State state) noexcept
Detailed Description
template<int allocatedBytes>
struct Packed7BitArrayBuilder< allocatedBytes >
This helper class allocates a block of 7-bit bytes and can push sequences of bits into it.
See Also
Packed7BitArrayReader
Member Function Documentation
template<int allocatedBytes> const void* Packed7BitArrayBuilder< allocatedBytes >::getData () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::getData().
template<int allocatedBytes> int Packed7BitArrayBuilder< allocatedBytes >::size () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::size().
template<int allocatedBytes> bool Packed7BitArrayBuilder< allocatedBytes >::hasCapacity (int bitsNeeded) const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), HostPacketBuilder< maxPacketBytes >::addProgramEventMessage(), HostPacketBuilder< maxPacketBytes >::beginDataChanges(), HostPacketBuilder< maxPacketBytes >::deviceControlMessage(), HostPacketBuilder< maxPacketBytes >::endDataChanges(), HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), HostPacketBuilder< maxPacketBytes >::skipBytes(), Packed7BitArrayBuilder< maxPacketBytes >::writeBits(), and Packed7BitArrayBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes (uint8 deviceIndex) noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter () noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter().
template<int allocatedBytes> template<int numBits> Packed7BitArrayBuilder& Packed7BitArrayBuilder< allocatedBytes >::operator<< (IntegerWithBitSize< numBits > value) noexcept
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::writeBits (uint32 value, int numBits) noexcept
Referenced by Packed7BitArrayBuilder< maxPacketBytes >::operator<<().
template<int allocatedBytes> State Packed7BitArrayBuilder< allocatedBytes >::getState () const noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and HostPacketBuilder< maxPacketBytes >::skipBytes().
template<int allocatedBytes> void Packed7BitArrayBuilder< allocatedBytes >::restore (State state) noexcept
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes(), and HostPacketBuilder< maxPacketBytes >::skipBytes().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h