JUCE: HostPacketBuilder< maxPacketBytes > Struct Template Reference
HostPacketBuilder< maxPacketBytes > Struct Template Reference
Helper class for constructing a packet for sending to a BLOCKS device.
Public Member Functions
HostPacketBuilder () noexcept
HostPacketBuilder (const HostPacketBuilder &)=delete
HostPacketBuilder (HostPacketBuilder &&)=default
const void * getData () const noexcept
int size () const noexcept
void writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
void writePacketSysexFooter () noexcept
bool deviceControlMessage (DeviceCommand command) noexcept
bool beginDataChanges (PacketIndex packetIndex) noexcept
bool endDataChanges (bool isLastChange) noexcept
bool skipBytes (int numToSkip) noexcept
bool setMultipleBytes (const uint8 *values, int num) noexcept
bool setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
bool addProgramEventMessage (const int32 *messageData)
bool addFirmwareUpdatePacket (const uint8 *packetData, uint8 size)
bool addConfigSetMessage (int32 item, int32 value)
bool addRequestMessage (int32 item)
bool addRequestFactorySyncMessage ()
bool addRequestUserSyncMessage ()
bool addFactoryReset ()
bool addBlockReset ()
bool addSetBlockName (const juce::String &name)
Detailed Description
template<int maxPacketBytes>
struct HostPacketBuilder< maxPacketBytes >
Helper class for constructing a packet for sending to a BLOCKS device.
Constructor & Destructor Documentation
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder () noexcept
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (const HostPacketBuilder< maxPacketBytes > &) delete
template<int maxPacketBytes> HostPacketBuilder< maxPacketBytes >::HostPacketBuilder (HostPacketBuilder< maxPacketBytes > &&) default
Member Function Documentation
template<int maxPacketBytes> const void* HostPacketBuilder< maxPacketBytes >::getData () const noexcept
References Packed7BitArrayBuilder< allocatedBytes >::getData().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> int HostPacketBuilder< maxPacketBytes >::size () const noexcept
References Packed7BitArrayBuilder< allocatedBytes >::size().
Referenced by HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket(), BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void HostPacketBuilder< maxPacketBytes >::writePacketSysexHeaderBytes (TopologyIndex deviceIndex) noexcept
References jassert, and Packed7BitArrayBuilder< allocatedBytes >::writeHeaderSysexBytes().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> void HostPacketBuilder< maxPacketBytes >::writePacketSysexFooter () noexcept
References Packed7BitArrayBuilder< allocatedBytes >::writePacketSysexFooter().
Referenced by BlockConfigManager::requestBlockConfig(), BlockConfigManager::requestFactoryConfigSync(), BlockConfigManager::requestUserConfigSync(), and BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::deviceControlMessage (DeviceCommand command) noexcept
References IntegerWithBitSize< numBits >::bits, deviceCommandMessage, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::beginDataChanges (PacketIndex packetIndex) noexcept
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and sharedDataChange.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::endDataChanges (bool isLastChange) noexcept
References IntegerWithBitSize< numBits >::bits, endOfChanges, endOfPacket, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::skipBytes (int numToSkip) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::getState(), Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), IntegerWithBitSize< numBits >::maxValue, IntegerWithBitSize< 8 >::maxValue, Packed7BitArrayBuilder< allocatedBytes >::restore(), skipBytesFew, and skipBytesMany.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::setMultipleBytes (const uint8 * values, int num) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setSequenceOfBytes.
Referenced by HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::setMultipleBytes (uint8 value, uint8 lastValue, int num) noexcept
References IntegerWithBitSize< numBits >::bits, IntegerWithBitSize< 8 >::bits, Packed7BitArrayBuilder< allocatedBytes >::getState(), Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), IntegerWithBitSize< numBits >::maxValue, IntegerWithBitSize< 8 >::maxValue, Packed7BitArrayBuilder< allocatedBytes >::restore(), setFewBytesWithLastValue, setFewBytesWithValue, setManyBytesWithValue, and HostPacketBuilder< maxPacketBytes >::setMultipleBytes().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addProgramEventMessage (const int32 * messageData)
References Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and programEventMessage.
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addFirmwareUpdatePacket (const uint8 * packetData, uint8 size)
References IntegerWithBitSize< numBits >::bits, firmwareUpdatePacket, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and HostPacketBuilder< maxPacketBytes >::size().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addConfigSetMessage (int32 item, int32 value)
References configMessage, configSetMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setConfig.
Referenced by BlockConfigManager::setBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestMessage (int32 item)
References configMessage, configSetMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestConfig.
Referenced by BlockConfigManager::requestBlockConfig().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestFactorySyncMessage ()
References IntegerWithBitSize< numBits >::bits, configMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestFactorySync.
Referenced by BlockConfigManager::requestFactoryConfigSync().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addRequestUserSyncMessage ()
References IntegerWithBitSize< numBits >::bits, configMessage, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and requestUserSync.
Referenced by BlockConfigManager::requestUserConfigSync().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addFactoryReset ()
References IntegerWithBitSize< numBits >::bits, factoryReset, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addBlockReset ()
References IntegerWithBitSize< numBits >::bits, blockReset, and Packed7BitArrayBuilder< allocatedBytes >::hasCapacity().
template<int maxPacketBytes> bool HostPacketBuilder< maxPacketBytes >::addSetBlockName (const juce::String & name)
References IntegerWithBitSize< numBits >::bits, Packed7BitArrayBuilder< allocatedBytes >::hasCapacity(), and setName.
The documentation for this struct was generated from the following file:
juce_HostPacketBuilder.h