JUCE: Block::ProgramEventListener Struct Reference
Block::ProgramEventListener Struct Reference abstract
juce_blocks_basics » blocks
Interface for objects listening to custom program events.
Public Member Functions
virtual ~ProgramEventListener ()
virtual void handleProgramEvent (Block &source, const ProgramEventMessage &)=0
Called whenever a message from a block is received.
Detailed Description
Interface for objects listening to custom program events.
Constructor & Destructor Documentation
~ProgramEventListener()
virtual Block::ProgramEventListener::~ProgramEventListener () virtual
References Block::addProgramEventListener(), Block::getDataByte(), Block::getHeapMemorySize(), Block::getMemorySize(), Block::removeProgramEventListener(), Block::saveProgramAsDefault(), Block::setDataBits(), Block::setDataByte(), and Block::setDataBytes().
Member Function Documentation
handleProgramEvent()
virtual void Block::ProgramEventListener::handleProgramEvent (Block & source, const ProgramEventMessage &) pure virtual
Called whenever a message from a block is received.
The documentation for this struct was generated from the following file:
juce_Block.h