JUCE: IntegerWithBitSize< numBits > Struct Template Reference
IntegerWithBitSize< numBits > Struct Template Reference
Public Types
enum { bits = numBits, maxValue = static_cast<uint32> ((1ULL << numBits) - 1ULL) }
Public Member Functions
IntegerWithBitSize () noexcept=default
IntegerWithBitSize (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize & operator= (const IntegerWithBitSize &) noexcept=default
IntegerWithBitSize (uint32 v) noexcept
operator uint32 () const noexcept
uint32 get () const noexcept
uint8 getScaledToByte () const noexcept
float toUnipolarFloat () const noexcept
float toBipolarFloat () const noexcept
Static Public Member Functions
static IntegerWithBitSize fromUnipolarFloat (float value) noexcept
static IntegerWithBitSize fromBipolarFloat (float value) noexcept
Public Attributes
uint32 value = 0
Member Enumeration Documentation
template<int numBits> anonymous enum
Enumerator
bits
maxValue
Constructor & Destructor Documentation
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize () default noexcept
Referenced by IntegerWithBitSize< 8 >::fromBipolarFloat(), and IntegerWithBitSize< 8 >::fromUnipolarFloat().
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> IntegerWithBitSize< numBits >::IntegerWithBitSize (uint32 v) noexcept
Member Function Documentation
template<int numBits> IntegerWithBitSize& IntegerWithBitSize< numBits >::operator= (const IntegerWithBitSize< numBits > &) default noexcept
template<int numBits> IntegerWithBitSize< numBits >::operator uint32 () const noexcept
template<int numBits> uint32 IntegerWithBitSize< numBits >::get () const noexcept
Referenced by HostPacketDecoder< Handler >::handleButtonDownOrUp(), HostPacketDecoder< Handler >::handleCustomMessage(), HostPacketDecoder< Handler >::handleTouch(), and HostPacketDecoder< Handler >::handleTouchWithVelocity().
template<int numBits> uint8 IntegerWithBitSize< numBits >::getScaledToByte () const noexcept
template<int numBits> float IntegerWithBitSize< numBits >::toUnipolarFloat () const noexcept
template<int numBits> float IntegerWithBitSize< numBits >::toBipolarFloat () const noexcept
template<int numBits> static IntegerWithBitSize IntegerWithBitSize< numBits >::fromUnipolarFloat (float value) static noexcept
template<int numBits> static IntegerWithBitSize IntegerWithBitSize< numBits >::fromBipolarFloat (float value) static noexcept
Member Data Documentation
template<int numBits> uint32 IntegerWithBitSize< numBits >::value = 0
Referenced by IntegerWithBitSize< 8 >::get(), and IntegerWithBitSize< 8 >::operator uint32().
The documentation for this struct was generated from the following file:
juce_BitPackingUtilities.h