JUCE: CoreAudioLayouts Struct Reference
CoreAudioLayouts Struct Reference
Static Public Member Functions
static AudioChannelSet fromCoreAudio (const AudioChannelLayout &layout)
Convert CoreAudio's native AudioChannelLayout to JUCE's AudioChannelSet.
static AudioChannelLayoutTag toCoreAudio (const AudioChannelSet &set)
Convert JUCE's AudioChannelSet to CoreAudio's AudioChannelLayoutTag.
static const Array
< AudioChannelLayoutTag > & getKnownCoreAudioTags ()
static Array
< AudioChannelSet::ChannelType > getCoreAudioLayoutChannels (const AudioChannelLayout &layout)
Convert CoreAudio's native AudioChannelLayout to an array of JUCE ChannelTypes.
Member Function Documentation
static AudioChannelSet CoreAudioLayouts::fromCoreAudio (const AudioChannelLayout & layout) static
Convert CoreAudio's native AudioChannelLayout to JUCE's AudioChannelSet.
Note that this method cannot preserve the order of channels.
References AudioChannelSet::channelSetWithChannels(), and getCoreAudioLayoutChannels().
static AudioChannelLayoutTag CoreAudioLayouts::toCoreAudio (const AudioChannelSet & set) static
Convert JUCE's AudioChannelSet to CoreAudio's AudioChannelLayoutTag.
Note that this method cannot preserve the order of channels.
References AudioChannelSet::addChannel(), numElementsInArray(), AudioChannelSet::size(), and AudioChannelSet::unknown.
static const Array<AudioChannelLayoutTag>& CoreAudioLayouts::getKnownCoreAudioTags () static
static Array<AudioChannelSet::ChannelType> CoreAudioLayouts::getCoreAudioLayoutChannels (const AudioChannelLayout & layout) static
Convert CoreAudio's native AudioChannelLayout to an array of JUCE ChannelTypes.
References Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::addIfNotAlreadyThere(), AudioChannelSet::discreteChannel0, AudioChannelSet::discreteChannels(), AudioChannelSet::fromWaveChannelMask(), AudioChannelSet::getChannelTypes(), and Array< ElementType, TypeOfCriticalSectionToUse, minimumAllocatedSize >::size().
Referenced by fromCoreAudio().
The documentation for this struct was generated from the following file:
juce_mac_CoreAudioLayouts.h